## Library Imports

In [3]:
import os
import time
import warnings
from collections import Counter
from functools import reduce
from itertools import combinations

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
from matplotlib.colors import to_rgba

from sklearn.decomposition import PCA, FastICA, IncrementalPCA, KernelPCA
from sklearn.cross_decomposition import CCA
from sklearn.kernel_approximation import RBFSampler
from sklearn.manifold import Isomap, TSNE, SpectralEmbedding, LocallyLinearEmbedding
from sklearn.feature_selection import SelectFromModel
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.preprocessing import (StandardScaler, MinMaxScaler, RobustScaler, PowerTransformer,
                                   QuantileTransformer, normalize)
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import (LogisticRegression, RidgeClassifier, SGDClassifier,
                                  PassiveAggressiveClassifier, Perceptron, LinearRegression,
                                  Ridge, Lasso, ElasticNet)
from sklearn.svm import SVC, SVR
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import (RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier,
                             RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor)
from sklearn.metrics import (accuracy_score, f1_score, precision_score, recall_score,
                            roc_auc_score, cohen_kappa_score, balanced_accuracy_score,
                            r2_score, mean_absolute_error, mean_squared_error)
from sklearn.experimental import enable_iterative_imputer
from xgboost import XGBClassifier, XGBRegressor
from lightgbm import LGBMRegressor, LGBMClassifier
from catboost import CatBoostRegressor, CatBoostClassifier
from imblearn.over_sampling import SMOTE, ADASYN, BorderlineSMOTE
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.metrics import confusion_matrix

## Dataset Loading and Preprocessing

In [4]:
dataset = "ppbr_az"
labels_df_file = f"../data/Benchmarking_Datasets/TDC/ADME/{dataset}.tab"
target_column_name = "Y"
labels_df = pd.read_csv(labels_df_file,sep="\t")
labels_df = labels_df.rename(columns={"Drug": "SMILES"})
labels_df

,Drug_ID,SMILES,Y,Species
0,CHEMBL1017,CCCc1nc2c(C)cc(-c3nc4ccccc4n3C)cc2n1Cc1ccc(-c2...,98.25,Canis lupus familiaris
1,CHEMBL2337981,CC(C)(C)NC(=O)NCCN1CCC(CO)(CNC(=O)c2cc(Cl)cc(C...,82.05,Canis lupus familiaris
2,CHEMBL401158,CCCCNc1nc(SCCC)nc2c1nnn2[C@@H]1C[C@H](CO)[C@@H...,95.33,Canis lupus familiaris
3,CHEMBL2337980,CC(C)(C)NC(=O)NCCN1CCC(O)(CNC(=O)c2cc(Cl)cc(Cl...,64.01,Canis lupus familiaris
4,CHEMBL914,CC(C)(C(=O)O)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)...,84.90,Canis lupus familiaris
...,...,...,...,...
2823,CHEMBL2088414,O=S(=O)(Nc1ccc2sc(CO)nc2c1)c1ccc(Br)cc1,99.82,Rattus norvegicus
2824,CHEMBL1628227,CN(C)CCC=C1c2ccccc2COc2ccccc21,79.55,Rattus norvegicus
2825,CHEMBL1287853,Cc1cnc(Nc2ccc(OCCN3CCCC3)cc2)nc1Nc1cccc(S(=O)(...,79.55,Rattus norvegicus
2826,CHEMBL1289283,O=c1cc(OCc2ccccc2)ccn1-c1ccc2c(cnn2CCN2CCCC2)c1,88.11,Rattus norvegicus
2827,CHEMBL1934414,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,97.32,Rattus norvegicus

## Data Quality Checks

In [5]:
conflicting_smiles = labels_df.groupby('SMILES')[target_column_name].nunique()
conflicting_smiles = conflicting_smiles[conflicting_smiles > 1].index.tolist()

if conflicting_smiles:
    print(len(conflicting_smiles),"Conflicting SMILES found:")
    for smiles in conflicting_smiles:
        print(smiles)
        display(labels_df[labels_df['SMILES'] == smiles])
else:
    print("No conflicting SMILES found.")

conflicting_smiles = labels_df.groupby('SMILES')[target_column_name].nunique()

691 Conflicting SMILES found:
C#CC[C@@H](C(=O)N[C@H](/C=C/C(=O)OCC)C[C@@H]1CCNC1=O)n1cccc(NC(=O)c2cc(C)on2)c1=O

,Drug_ID,SMILES,Y,Species
50,CHEMBL141157,C#CC[C@@H](C(=O)N[C@H](/C=C/C(=O)OCC)C[C@@H]1C...,46.55,Canis lupus familiaris
1667,CHEMBL141157,C#CC[C@@H](C(=O)N[C@H](/C=C/C(=O)OCC)C[C@@H]1C...,55.73,Homo sapiens

C/C=C/c1ccc(Oc2nnnn2-c2ccc(C(N)=O)cc2)c(OC)c1

,Drug_ID,SMILES,Y,Species
575,CHEMBL1320158,C/C=C/c1ccc(Oc2nnnn2-c2ccc(C(N)=O)cc2)c(OC)c1,97.32,Homo sapiens
2071,CHEMBL1320158,C/C=C/c1ccc(Oc2nnnn2-c2ccc(C(N)=O)cc2)c(OC)c1,95.72,Mus musculus

C1Cc2[nH]nc(-c3nn[nH]n3)c2C1

           Drug_ID                        SMILES      Y            Species
767   CHEMBL456145  C1Cc2[nH]nc(-c3nn[nH]n3)c2C1  89.91       Homo sapiens
1965  CHEMBL456145  C1Cc2[nH]nc(-c3nn[nH]n3)c2C1  62.94       Mus musculus
2614  CHEMBL456145  C1Cc2[nH]nc(-c3nn[nH]n3)c2C1  92.80  Rattus norvegicus

C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@@H](O)c1ccnc2ccc(OC)cc12

,Drug_ID,SMILES,Y,Species
123,CHEMBL1294,C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@@H](O)c1ccnc2cc...,93.80,Canis lupus familiaris
923,CHEMBL1294,C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@@H](O)c1ccnc2cc...,85.48,Homo sapiens
2771,CHEMBL1294,C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@@H](O)c1ccnc2cc...,60.77,Rattus norvegicus

CC#Cc1ccnc(-c2cc(C3(C4CC4)N=C(C)C(N)=N3)ccc2O)c1

,Drug_ID,SMILES,Y,Species
1632,CHEMBL2180015,CC#Cc1ccnc(-c2cc(C3(C4CC4)N=C(C)C(N)=N3)ccc2O)c1,99.4,Homo sapiens
2026,CHEMBL2180015,CC#Cc1ccnc(-c2cc(C3(C4CC4)N=C(C)C(N)=N3)ccc2O)c1,97.6,Mus musculus

CC#Cc1cncc(-c2ccc3c(c2)C2(N=C(C)C(N)=N2)[C@]2(CC[C@H](OC)CC2)C3)c1

,Drug_ID,SMILES,Y,Species
319,CHEMBL2152914,CC#Cc1cncc(-c2ccc3c(c2)C2(N=C(C)C(N)=N2)[C@]2(...,92.80,Cavia porcellus
1224,CHEMBL2152914,CC#Cc1cncc(-c2ccc3c(c2)C2(N=C(C)C(N)=N2)[C@]2(...,91.99,Homo sapiens
2043,CHEMBL2152914,CC#Cc1cncc(-c2ccc3c(c2)C2(N=C(C)C(N)=N2)[C@]2(...,99.59,Mus musculus

CC#Cc1cncc(-c2cccc(C3(C4CC4)N=C(C)C(N)=N3)c2)c1

,Drug_ID,SMILES,Y,Species
1447,CHEMBL2180037,CC#Cc1cncc(-c2cccc(C3(C4CC4)N=C(C)C(N)=N3)c2)c1,95.01,Homo sapiens
1971,CHEMBL2180037,CC#Cc1cncc(-c2cccc(C3(C4CC4)N=C(C)C(N)=N3)c2)c1,91.82,Mus musculus
2540,CHEMBL2180037,CC#Cc1cncc(-c2cccc(C3(C4CC4)N=C(C)C(N)=N3)c2)c1,93.67,Rattus norvegicus

CC#Cc1cncc(-c2cccc(C3(c4cc(C)c(OC)c(C)c4)N=C(C)C(N)=N3)c2)c1

,Drug_ID,SMILES,Y,Species
1010,CHEMBL2180031,CC#Cc1cncc(-c2cccc(C3(c4cc(C)c(OC)c(C)c4)N=C(C...,99.8,Homo sapiens
1979,CHEMBL2180031,CC#Cc1cncc(-c2cccc(C3(c4cc(C)c(OC)c(C)c4)N=C(C...,99.4,Mus musculus

CC#Cc1cncc(-c2cccc([C@@]3(c4cc(C)c(=O)n(CC)c4)N=C(N)c4c(F)cccc43)c2)c1

,Drug_ID,SMILES,Y,Species
127,CHEMBL2152903,CC#Cc1cncc(-c2cccc([C@@]3(c4cc(C)c(=O)n(CC)c4)...,99.74,Canis lupus familiaris
262,CHEMBL2152903,CC#Cc1cncc(-c2cccc([C@@]3(c4cc(C)c(=O)n(CC)c4)...,99.14,Cavia porcellus
1369,CHEMBL2152903,CC#Cc1cncc(-c2cccc([C@@]3(c4cc(C)c(=O)n(CC)c4)...,98.92,Homo sapiens
1997,CHEMBL2152903,CC#Cc1cncc(-c2cccc([C@@]3(c4cc(C)c(=O)n(CC)c4)...,98.51,Mus musculus
2627,CHEMBL2152903,CC#Cc1cncc(-c2cccc([C@@]3(c4cc(C)c(=O)n(CC)c4)...,98.64,Rattus norvegicus

CC#Cc1cncc(-c2csc([C@]3(C)CC(=O)N(C)C(=N)N3)c2)c1

,Drug_ID,SMILES,Y,Species
737,CHEMBL2151141,CC#Cc1cncc(-c2csc([C@]3(C)CC(=O)N(C)C(=N)N3)c2)c1,88.11,Homo sapiens
2024,CHEMBL2151141,CC#Cc1cncc(-c2csc([C@]3(C)CC(=O)N(C)C(=N)N3)c2)c1,83.04,Mus musculus

CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O

,Drug_ID,SMILES,Y,Species
86,CHEMBL1464,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,96.79,Canis lupus familiaris
278,CHEMBL1464,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,96.87,Cavia porcellus
956,CHEMBL1464,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,99.31,Homo sapiens
2598,CHEMBL1464,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,99.21,Rattus norvegicus

CC(=O)N1CCN(c2nc(NC(C)(C)Cc3ccc(Cl)cc3)c3c(n2)C(=O)N(C(C)C)C3)CC1

,Drug_ID,SMILES,Y,Species
1327,CHEMBL2011112,CC(=O)N1CCN(c2nc(NC(C)(C)Cc3ccc(Cl)cc3)c3c(n2)...,96.79,Homo sapiens
2811,CHEMBL2011112,CC(=O)N1CCN(c2nc(NC(C)(C)Cc3ccc(Cl)cc3)c3c(n2)...,96.17,Rattus norvegicus

CC(=O)NC[C@H]1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1

,Drug_ID,SMILES,Y,Species
5,CHEMBL126,CC(=O)NC[C@H]1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1,52.30,Canis lupus familiaris
518,CHEMBL126,CC(=O)NC[C@H]1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1,22.79,Homo sapiens
2079,CHEMBL126,CC(=O)NC[C@H]1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1,23.19,Mus musculus
2212,CHEMBL126,CC(=O)NC[C@H]1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1,22.38,Rattus norvegicus

CC(=O)N[C@H](C)c1ccc(Nc2ncc3cc(-c4ccncc4)ccc3n2)cc1

,Drug_ID,SMILES,Y,Species
183,CHEMBL2335896,CC(=O)N[C@H](C)c1ccc(Nc2ncc3cc(-c4ccncc4)ccc3n...,90.32,Canis lupus familiaris
1484,CHEMBL2335896,CC(=O)N[C@H](C)c1ccc(Nc2ncc3cc(-c4ccncc4)ccc3n...,97.55,Homo sapiens
2125,CHEMBL2335896,CC(=O)N[C@H](C)c1ccc(Nc2ncc3cc(-c4ccncc4)ccc3n...,94.68,Rattus norvegicus

CC(=O)Nc1cccc(Nc2ncnc(N3CCC(OCc4ccc(OC(F)(F)F)cc4)CC3)n2)c1C

,Drug_ID,SMILES,Y,Species
665,CHEMBL1813048,CC(=O)Nc1cccc(Nc2ncnc(N3CCC(OCc4ccc(OC(F)(F)F)...,98.81,Homo sapiens
2353,CHEMBL1813048,CC(=O)Nc1cccc(Nc2ncnc(N3CCC(OCc4ccc(OC(F)(F)F)...,99.05,Rattus norvegicus

CC(=O)Nc1nc2c(Oc3cc(-c4ccc(C(F)(F)F)cc4)ncn3)cccc2s1

,Drug_ID,SMILES,Y,Species
285,CHEMBL229430,CC(=O)Nc1nc2c(Oc3cc(-c4ccc(C(F)(F)F)cc4)ncn3)c...,98.61,Cavia porcellus
887,CHEMBL229430,CC(=O)Nc1nc2c(Oc3cc(-c4ccc(C(F)(F)F)cc4)ncn3)c...,99.90,Homo sapiens
2222,CHEMBL229430,CC(=O)Nc1nc2c(Oc3cc(-c4ccc(C(F)(F)F)cc4)ncn3)c...,99.80,Rattus norvegicus

CC(C(=O)O)c1cccc(C(=O)c2ccccc2)c1

        Drug_ID                             SMILES      Y            Species
666   CHEMBL571  CC(C(=O)O)c1cccc(C(=O)c2ccccc2)c1  98.73       Homo sapiens
2347  CHEMBL571  CC(C(=O)O)c1cccc(C(=O)c2ccccc2)c1  99.36  Rattus norvegicus

CC(C(=O)O[C@@H]1CC[N+](C)(C)C1)(c1ccccc1)C1CCCC1

,Drug_ID,SMILES,Y,Species
708,CHEMBL1963231,CC(C(=O)O[C@@H]1CC[N+](C)(C)C1)(c1ccccc1)C1CCCC1,77.21,Homo sapiens
2662,CHEMBL1963231,CC(C(=O)O[C@@H]1CC[N+](C)(C)C1)(c1ccccc1)C1CCCC1,70.10,Rattus norvegicus

CC(C)(C(=O)O)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)c3ccccc3)CC2)cc1

,Drug_ID,SMILES,Y,Species
4,CHEMBL914,CC(C)(C(=O)O)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)...,84.90,Canis lupus familiaris
791,CHEMBL914,CC(C)(C(=O)O)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)...,62.94,Homo sapiens
2665,CHEMBL914,CC(C)(C(=O)O)c1ccc(C(O)CCCN2CCC(C(O)(c3ccccc3)...,76.81,Rattus norvegicus

CC(C)(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(Cl)cc1

,Drug_ID,SMILES,Y,Species
1876,CHEMBL2071592,CC(C)(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(Cl)cc1,99.40,Homo sapiens
2165,CHEMBL2071592,CC(C)(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(Cl)cc1,99.19,Rattus norvegicus

CC(C)(C)CCN1CC[C@H](CNC(=O)c2cc(Cl)cc(Cl)c2)[C@H](F)C1

,Drug_ID,SMILES,Y,Species
314,CHEMBL493677,CC(C)(C)CCN1CC[C@H](CNC(=O)c2cc(Cl)cc(Cl)c2)[C...,88.11,Cavia porcellus
1743,CHEMBL493677,CC(C)(C)CCN1CC[C@H](CNC(=O)c2cc(Cl)cc(Cl)c2)[C...,95.53,Homo sapiens
1952,CHEMBL493677,CC(C)(C)CCN1CC[C@H](CNC(=O)c2cc(Cl)cc(Cl)c2)[C...,88.11,Mus musculus
2761,CHEMBL493677,CC(C)(C)CCN1CC[C@H](CNC(=O)c2cc(Cl)cc(Cl)c2)[C...,91.64,Rattus norvegicus

CC(C)(C)CS(=O)(=O)NCCN1CCN(CC(=O)NC23CC4CC(CC(C4)C2)C3)CC1

,Drug_ID,SMILES,Y,Species
830,CHEMBL2338404,CC(C)(C)CS(=O)(=O)NCCN1CCN(CC(=O)NC23CC4CC(CC(...,86.05,Homo sapiens
2807,CHEMBL2338404,CC(C)(C)CS(=O)(=O)NCCN1CCN(CC(=O)NC23CC4CC(CC(...,87.11,Rattus norvegicus

CC(C)(C)NC(=O)CN1CCN(CC(=O)NC23CC4CC(CC(C4)C2)C3)CC1

,Drug_ID,SMILES,Y,Species
433,CHEMBL2337984,CC(C)(C)NC(=O)CN1CCN(CC(=O)NC23CC4CC(CC(C4)C2)...,70.10,Homo sapiens
2491,CHEMBL2337984,CC(C)(C)NC(=O)CN1CCN(CC(=O)NC23CC4CC(CC(C4)C2)...,69.12,Rattus norvegicus

CC(C)(C)NC(=O)NCCN1CC(NC(=O)c2cc(Cl)cc(Cl)c2)C1

,Drug_ID,SMILES,Y,Species
110,CHEMBL2337977,CC(C)(C)NC(=O)NCCN1CC(NC(=O)c2cc(Cl)cc(Cl)c2)C1,92.16,Canis lupus familiaris
1131,CHEMBL2337977,CC(C)(C)NC(=O)NCCN1CC(NC(=O)c2cc(Cl)cc(Cl)c2)C1,90.72,Homo sapiens
2179,CHEMBL2337977,CC(C)(C)NC(=O)NCCN1CC(NC(=O)c2cc(Cl)cc(Cl)c2)C1,89.91,Rattus norvegicus

CC(C)(C)NC(=O)NCCN1CCC(CNC(=O)c2cc(Cl)cc(Cl)c2)C1

,Drug_ID,SMILES,Y,Species
64,CHEMBL2338409,CC(C)(C)NC(=O)NCCN1CCC(CNC(=O)c2cc(Cl)cc(Cl)c2)C1,90.91,Canis lupus familiaris
1038,CHEMBL2338409,CC(C)(C)NC(=O)NCCN1CCC(CNC(=O)c2cc(Cl)cc(Cl)c2)C1,90.32,Homo sapiens
2817,CHEMBL2338409,CC(C)(C)NC(=O)NCCN1CCC(CNC(=O)c2cc(Cl)cc(Cl)c2)C1,86.05,Rattus norvegicus

CC(C)(C)NC(=O)NCCN1CCC(CNC(=O)c2cc(Cl)cc(Cl)c2)CC1

,Drug_ID,SMILES,Y,Species
48,CHEMBL2338406,CC(C)(C)NC(=O)NCCN1CCC(CNC(=O)c2cc(Cl)cc(Cl)c2...,89.05,Canis lupus familiaris
1322,CHEMBL2338406,CC(C)(C)NC(=O)NCCN1CCC(CNC(=O)c2cc(Cl)cc(Cl)c2...,89.05,Homo sapiens
2586,CHEMBL2338406,CC(C)(C)NC(=O)NCCN1CCC(CNC(=O)c2cc(Cl)cc(Cl)c2...,83.04,Rattus norvegicus

CC(C)(C)NC(=O)NCCN1CCC(CO)(CNC(=O)c2cc(Cl)cc(Cl)c2)CC1

,Drug_ID,SMILES,Y,Species
1,CHEMBL2337981,CC(C)(C)NC(=O)NCCN1CCC(CO)(CNC(=O)c2cc(Cl)cc(C...,82.05,Canis lupus familiaris
1182,CHEMBL2337981,CC(C)(C)NC(=O)NCCN1CCC(CO)(CNC(=O)c2cc(Cl)cc(C...,82.05,Homo sapiens
2515,CHEMBL2337981,CC(C)(C)NC(=O)NCCN1CCC(CO)(CNC(=O)c2cc(Cl)cc(C...,79.92,Rattus norvegicus

CC(C)(C)NC(=O)NCCN1CCC(O)(CNC(=O)c2cc(Cl)cc(Cl)c2)CC1

,Drug_ID,SMILES,Y,Species
3,CHEMBL2337980,CC(C)(C)NC(=O)NCCN1CCC(O)(CNC(=O)c2cc(Cl)cc(Cl...,64.01,Canis lupus familiaris
1210,CHEMBL2337980,CC(C)(C)NC(=O)NCCN1CCC(O)(CNC(=O)c2cc(Cl)cc(Cl...,76.81,Homo sapiens
2567,CHEMBL2337980,CC(C)(C)NC(=O)NCCN1CCC(O)(CNC(=O)c2cc(Cl)cc(Cl...,76.81,Rattus norvegicus

CC(C)(C)NC(=O)NCCN1CCCC(NC(=O)c2cc(Cl)cc(Cl)c2)C1

,Drug_ID,SMILES,Y,Species
68,CHEMBL2337979,CC(C)(C)NC(=O)NCCN1CCCC(NC(=O)c2cc(Cl)cc(Cl)c2)C1,93.67,Canis lupus familiaris
1053,CHEMBL2337979,CC(C)(C)NC(=O)NCCN1CCCC(NC(=O)c2cc(Cl)cc(Cl)c2)C1,97.20,Homo sapiens
2704,CHEMBL2337979,CC(C)(C)NC(=O)NCCN1CCCC(NC(=O)c2cc(Cl)cc(Cl)c2)C1,96.09,Rattus norvegicus

CC(C)(C)NC(=O)NCCN1CCN(CC(=O)NC23CC4CC(CC(C4)C2)C3)CC1

,Drug_ID,SMILES,Y,Species
215,CHEMBL2338400,CC(C)(C)NC(=O)NCCN1CCN(CC(=O)NC23CC4CC(CC(C4)C...,75.97,Canis lupus familiaris
1570,CHEMBL2338400,CC(C)(C)NC(=O)NCCN1CCN(CC(=O)NC23CC4CC(CC(C4)C...,69.12,Homo sapiens
2262,CHEMBL2338400,CC(C)(C)NC(=O)NCCN1CCN(CC(=O)NC23CC4CC(CC(C4)C...,69.12,Rattus norvegicus

CC(C)(C)NC(=O)NCCN1CCN(CC(=O)Nc2cc(Cl)cc(Cl)c2)CC1

,Drug_ID,SMILES,Y,Species
174,CHEMBL2338405,CC(C)(C)NC(=O)NCCN1CCN(CC(=O)Nc2cc(Cl)cc(Cl)c2...,94.44,Canis lupus familiaris
633,CHEMBL2338405,CC(C)(C)NC(=O)NCCN1CCN(CC(=O)Nc2cc(Cl)cc(Cl)c2...,94.79,Homo sapiens

CC(C)(C)NC(=O)NCCN1CCOC(CNC(=O)c2cc(Cl)cc(Cl)c2)C1

,Drug_ID,SMILES,Y,Species
125,CHEMBL2338408,CC(C)(C)NC(=O)NCCN1CCOC(CNC(=O)c2cc(Cl)cc(Cl)c...,91.82,Canis lupus familiaris
1819,CHEMBL2338408,CC(C)(C)NC(=O)NCCN1CCOC(CNC(=O)c2cc(Cl)cc(Cl)c...,93.94,Homo sapiens
2706,CHEMBL2338408,CC(C)(C)NC(=O)NCCN1CCOC(CNC(=O)c2cc(Cl)cc(Cl)c...,93.24,Rattus norvegicus

CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](O)C[C@@H](Cc1ccccc1)C(=O)N[C@H]1c2ccccc2C[C@H]1O

,Drug_ID,SMILES,Y,Species
1909,CHEMBL115,CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...,62.94,Homo sapiens
2287,CHEMBL115,CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...,78.79,Rattus norvegicus

CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C@@H](O)[C@H](Cc1ccccc1)NC(=O)[C@H](CC(N)=O)NC(=O)c1ccc2ccccc2n1

,Drug_ID,SMILES,Y,Species
662,CHEMBL114,CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C...,98.86,Homo sapiens
2341,CHEMBL114,CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C...,99.52,Rattus norvegicus

CC(C)(C)NC(=O)c1ccc(Oc2cc(F)c(CC(=O)O)cc2Cl)c(NS(=O)(=O)c2ccc(C3CC3)cc2Cl)c1

,Drug_ID,SMILES,Y,Species
156,CHEMBL1951575,CC(C)(C)NC(=O)c1ccc(Oc2cc(F)c(CC(=O)O)cc2Cl)c(...,99.61,Canis lupus familiaris
1237,CHEMBL1951575,CC(C)(C)NC(=O)c1ccc(Oc2cc(F)c(CC(=O)O)cc2Cl)c(...,99.85,Homo sapiens

CC(C)(C)NCC(O)c1ccc(O)c(CO)c1

        Drug_ID                         SMILES      Y            Species
256   CHEMBL714  CC(C)(C)NCC(O)c1ccc(O)c(CO)c1  14.52    Cavia porcellus
1619  CHEMBL714  CC(C)(C)NCC(O)c1ccc(O)c(CO)c1  22.79       Homo sapiens
2370  CHEMBL714  CC(C)(C)NCC(O)c1ccc(O)c(CO)c1  34.42  Rattus norvegicus

CC(C)(C)NS(=O)(=O)c1cncc(-c2ccc3nc(NC(=O)NCC(=O)N4CCCC4)nn3c2)c1

,Drug_ID,SMILES,Y,Species
790,CHEMBL2057371,CC(C)(C)NS(=O)(=O)c1cncc(-c2ccc3nc(NC(=O)NCC(=...,67.12,Homo sapiens
2499,CHEMBL2057371,CC(C)(C)NS(=O)(=O)c1cncc(-c2ccc3nc(NC(=O)NCC(=...,76.81,Rattus norvegicus

CC(C)(C)NS(=O)(=O)c1cncc(-c2ccc3nc(NC(=O)NCC(=O)N4CCOCC4)nn3c2)c1

,Drug_ID,SMILES,Y,Species
1657,CHEMBL2057372,CC(C)(C)NS(=O)(=O)c1cncc(-c2ccc3nc(NC(=O)NCC(=...,54.02,Homo sapiens
2524,CHEMBL2057372,CC(C)(C)NS(=O)(=O)c1cncc(-c2ccc3nc(NC(=O)NCC(=...,46.55,Rattus norvegicus

CC(C)(C)OC(=O)N1CCC(OCc2nc(-c3ccncc3)no2)CC1

,Drug_ID,SMILES,Y,Species
964,CHEMBL1081913,CC(C)(C)OC(=O)N1CCC(OCc2nc(-c3ccncc3)no2)CC1,99.16,Homo sapiens
2718,CHEMBL1081913,CC(C)(C)OC(=O)N1CCC(OCc2nc(-c3ccncc3)no2)CC1,92.48,Rattus norvegicus

CC(C)(C)OC(=O)N1CCN(c2ncc(OCc3ccncc3)cn2)CC1

,Drug_ID,SMILES,Y,Species
1142,CHEMBL2086675,CC(C)(C)OC(=O)N1CCN(c2ncc(OCc3ccncc3)cn2)CC1,99.03,Homo sapiens
2789,CHEMBL2086675,CC(C)(C)OC(=O)N1CCN(c2ncc(OCc3ccncc3)cn2)CC1,96.42,Rattus norvegicus

CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(-c3cccc(CN)c3)nc3ccccc23)CC1

,Drug_ID,SMILES,Y,Species
394,CHEMBL1818291,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(-c3c...,98.61,Homo sapiens
2784,CHEMBL1818291,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(-c3c...,98.29,Rattus norvegicus

CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(-c3ccccc3)nc3ccccc23)CC1

,Drug_ID,SMILES,Y,Species
765,CHEMBL1818187,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(-c3c...,99.92,Homo sapiens
2679,CHEMBL1818187,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(-c3c...,99.50,Rattus norvegicus

CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(N3CCC(CCN4CC(O)C4)CC3)nc3ccccc23)CC1

,Drug_ID,SMILES,Y,Species
1687,CHEMBL1818300,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(N3CC...,97.00,Homo sapiens
2097,CHEMBL1818300,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(N3CC...,98.61,Mus musculus
2112,CHEMBL1818300,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(N3CC...,96.72,Rattus norvegicus

CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(N3CCC(CCO)CC3)nc3ccccc23)CC1

,Drug_ID,SMILES,Y,Species
34,CHEMBL1818295,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(N3CC...,99.16,Canis lupus familiaris
958,CHEMBL1818295,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(N3CC...,99.30,Homo sapiens
2195,CHEMBL1818295,CC(C)(C)OC(=O)NC[C@H]1CC[C@H](CNC(=O)c2cc(N3CC...,99.01,Rattus norvegicus

CC(C)(C)OC(=O)N[C@H](Cc1ccccc1C(F)(F)F)C(=O)NCc1nc2cccnc2n1Cc1ccccc1

,Drug_ID,SMILES,Y,Species
1641,CHEMBL254497,CC(C)(C)OC(=O)N[C@H](Cc1ccccc1C(F)(F)F)C(=O)NC...,98.89,Homo sapiens
2794,CHEMBL254497,CC(C)(C)OC(=O)N[C@H](Cc1ccccc1C(F)(F)F)C(=O)NC...,99.80,Rattus norvegicus

CC(C)(C)S(=O)(=O)CCCN1CCN(CC(=O)NC23CC4CC(CC(C4)C2)C3)CC1

,Drug_ID,SMILES,Y,Species
140,CHEMBL2338403,CC(C)(C)S(=O)(=O)CCCN1CCN(CC(=O)NC23CC4CC(CC(C...,71.05,Canis lupus familiaris
382,CHEMBL2338403,CC(C)(C)S(=O)(=O)CCCN1CCN(CC(=O)NC23CC4CC(CC(C...,65.06,Homo sapiens
2352,CHEMBL2338403,CC(C)(C)S(=O)(=O)CCCN1CCN(CC(=O)NC23CC4CC(CC(C...,69.12,Rattus norvegicus

CC(C)(C)[C@@H](O)C(=O)N1CCC[C@H]1C(=O)NCc1cc(Cl)ccc1CN

,Drug_ID,SMILES,Y,Species
396,CHEMBL182997,CC(C)(C)[C@@H](O)C(=O)N1CCC[C@H]1C(=O)NCc1cc(C...,42.01,Homo sapiens
2444,CHEMBL182997,CC(C)(C)[C@@H](O)C(=O)N1CCC[C@H]1C(=O)NCc1cc(C...,50.00,Rattus norvegicus

CC(C)(Cc1cccc(CC(=O)NCc2cccc(-c3ccc(O)cc3)c2)c1)NC[C@H](O)c1ccc(O)c(NS(C)(=O)=O)c1

,Drug_ID,SMILES,Y,Species
618,CHEMBL1240967,CC(C)(Cc1cccc(CC(=O)NCc2cccc(-c3ccc(O)cc3)c2)c...,99.47,Homo sapiens
2735,CHEMBL1240967,CC(C)(Cc1cccc(CC(=O)NCc2cccc(-c3ccc(O)cc3)c2)c...,91.82,Rattus norvegicus

CC(C)(F)C[C@H](N[C@@H](c1ccc(-c2ccc(S(C)(=O)=O)cc2)cc1)C(F)(F)F)C(=O)NC1(C#N)CC1

,Drug_ID,SMILES,Y,Species
421,CHEMBL481611,CC(C)(F)C[C@H](N[C@@H](c1ccc(-c2ccc(S(C)(=O)=O...,93.94,Homo sapiens
1964,CHEMBL481611,CC(C)(F)C[C@H](N[C@@H](c1ccc(-c2ccc(S(C)(=O)=O...,98.40,Mus musculus
2455,CHEMBL481611,CC(C)(F)C[C@H](N[C@@H](c1ccc(-c2ccc(S(C)(=O)=O...,96.34,Rattus norvegicus

CC(C)(N)C(=O)N[C@H](COCc1ccc(F)cc1F)C(=O)N1CCC2=NN(CC(F)(F)F)C(=O)[C@]2(Cc2ccccn2)C1

,Drug_ID,SMILES,Y,Species
133,CHEMBL109980,CC(C)(N)C(=O)N[C@H](COCc1ccc(F)cc1F)C(=O)N1CCC...,54.59,Canis lupus familiaris
1766,CHEMBL109980,CC(C)(N)C(=O)N[C@H](COCc1ccc(F)cc1F)C(=O)N1CCC...,74.69,Homo sapiens
2788,CHEMBL109980,CC(C)(N)C(=O)N[C@H](COCc1ccc(F)cc1F)C(=O)N1CCC...,48.85,Rattus norvegicus

CC(C)(N)C(=O)N[C@H](COCc1ccccc1)C(=O)N1CCC2(CC1)CN(S(C)(=O)=O)c1ccccc12

,Drug_ID,SMILES,Y,Species
187,CHEMBL13817,CC(C)(N)C(=O)N[C@H](COCc1ccccc1)C(=O)N1CCC2(CC...,78.79,Canis lupus familiaris
1785,CHEMBL13817,CC(C)(N)C(=O)N[C@H](COCc1ccccc1)C(=O)N1CCC2(CC...,76.81,Homo sapiens
2198,CHEMBL13817,CC(C)(N)C(=O)N[C@H](COCc1ccccc1)C(=O)N1CCC2(CC...,74.69,Rattus norvegicus

CC(C)(Oc1ccc(Cl)cc1)C(=O)N1CCN(c2ccccn2)CC1

,Drug_ID,SMILES,Y,Species
1774,CHEMBL1352569,CC(C)(Oc1ccc(Cl)cc1)C(=O)N1CCN(c2ccccn2)CC1,99.23,Homo sapiens
2350,CHEMBL1352569,CC(C)(Oc1ccc(Cl)cc1)C(=O)N1CCN(c2ccccn2)CC1,99.08,Rattus norvegicus

CC(C)C(NC(=O)c1cc(Cl)ccc1C(F)(F)F)C(=O)c1ccc(C#N)cc1

,Drug_ID,SMILES,Y,Species
1268,CHEMBL2071507,CC(C)C(NC(=O)c1cc(Cl)ccc1C(F)(F)F)C(=O)c1ccc(C...,97.38,Homo sapiens
2325,CHEMBL2071507,CC(C)C(NC(=O)c1cc(Cl)ccc1C(F)(F)F)C(=O)c1ccc(C...,95.72,Rattus norvegicus

CC(C)C(NC(=O)c1cc(Cl)ccc1C(F)(F)F)C(=O)c1ccc([N+](=O)[O-])cc1

,Drug_ID,SMILES,Y,Species
444,CHEMBL2071601,CC(C)C(NC(=O)c1cc(Cl)ccc1C(F)(F)F)C(=O)c1ccc([...,98.81,Homo sapiens
2492,CHEMBL2071601,CC(C)C(NC(=O)c1cc(Cl)ccc1C(F)(F)F)C(=O)c1ccc([...,97.60,Rattus norvegicus

CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(C#N)cc1

,Drug_ID,SMILES,Y,Species
1551,CHEMBL2071498,CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(C#N)cc1,90.72,Homo sapiens
2159,CHEMBL2071498,CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(C#N)cc1,87.62,Rattus norvegicus

CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
702,CHEMBL2071493,CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(F)cc1,95.01,Homo sapiens
2533,CHEMBL2071493,CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc(F)cc1,91.64,Rattus norvegicus

CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc([N+](=O)[O-])cc1

,Drug_ID,SMILES,Y,Species
1614,CHEMBL2071491,CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc([N+](=O)[O-])cc1,95.82,Homo sapiens
2183,CHEMBL2071491,CC(C)C(NC(=O)c1ccccc1)C(=O)c1ccc([N+](=O)[O-])cc1,93.10,Rattus norvegicus

CC(C)C[C@H](CO)Nc1nc(S[C@@H](C)c2ccccc2)nc2[nH]c(=O)sc12

,Drug_ID,SMILES,Y,Species
124,CHEMBL2349312,CC(C)C[C@H](CO)Nc1nc(S[C@@H](C)c2ccccc2)nc2[nH...,99.81,Canis lupus familiaris
1599,CHEMBL2349312,CC(C)C[C@H](CO)Nc1nc(S[C@@H](C)c2ccccc2)nc2[nH...,99.90,Homo sapiens
1960,CHEMBL2349312,CC(C)C[C@H](CO)Nc1nc(S[C@@H](C)c2ccccc2)nc2[nH...,99.91,Mus musculus

CC(C)C[C@H](CO)Nc1nc(S[C@@H](C)c2ccccc2F)nc2nc(N)sc12

,Drug_ID,SMILES,Y,Species
196,CHEMBL2349316,CC(C)C[C@H](CO)Nc1nc(S[C@@H](C)c2ccccc2F)nc2nc...,99.80,Canis lupus familiaris
1248,CHEMBL2349316,CC(C)C[C@H](CO)Nc1nc(S[C@@H](C)c2ccccc2F)nc2nc...,99.89,Homo sapiens
2081,CHEMBL2349316,CC(C)C[C@H](CO)Nc1nc(S[C@@H](C)c2ccccc2F)nc2nc...,99.80,Mus musculus

CC(C)Cc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1ccccc1

,Drug_ID,SMILES,Y,Species
1443,CHEMBL504813,CC(C)Cc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1c...,96.87,Homo sapiens
2030,CHEMBL504813,CC(C)Cc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1c...,96.34,Mus musculus
2783,CHEMBL504813,CC(C)Cc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1c...,98.13,Rattus norvegicus

CC(C)Cc1nn(C)c(=O)c2c(SCCCO)n(Cc3cccc4ccccc34)cc12

,Drug_ID,SMILES,Y,Species
52,CHEMBL380192,CC(C)Cc1nn(C)c(=O)c2c(SCCCO)n(Cc3cccc4ccccc34)...,99.87,Canis lupus familiaris
1162,CHEMBL380192,CC(C)Cc1nn(C)c(=O)c2c(SCCCO)n(Cc3cccc4ccccc34)...,99.73,Homo sapiens

CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC(C)(O)C3)c(Cc3ccccc3C(F)(F)F)sc21

,Drug_ID,SMILES,Y,Species
10,CHEMBL439871,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC(C)(O)C3)c(...,83.04,Canis lupus familiaris
1712,CHEMBL439871,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC(C)(O)C3)c(...,93.10,Homo sapiens

CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC[C@@H](O)C3)c(Cc3c[nH]c4ccccc34)sc21

,Drug_ID,SMILES,Y,Species
56,CHEMBL205807,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC[C@@H](O)C3...,55.73,Canis lupus familiaris
1230,CHEMBL205807,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC[C@@H](O)C3...,91.46,Homo sapiens

CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC[C@@H](O)C3)c(Cc3ccnc4ccccc34)sc21

,Drug_ID,SMILES,Y,Species
88,CHEMBL205742,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC[C@@H](O)C3...,16.96,Canis lupus familiaris
1417,CHEMBL205742,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3CC[C@@H](O)C3...,64.54,Homo sapiens

CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3C[C@H](O)CO3)c(Cc3c[nH]c4ncccc34)sc21

,Drug_ID,SMILES,Y,Species
21,CHEMBL384536,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3C[C@H](O)CO3)...,62.94,Canis lupus familiaris
903,CHEMBL384536,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3C[C@H](O)CO3)...,75.55,Homo sapiens

CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3C[C@H](O)CO3)c(Cc3ccnc4ccccc34)sc21

,Drug_ID,SMILES,Y,Species
181,CHEMBL219861,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3C[C@H](O)CO3)...,72.45,Canis lupus familiaris
1425,CHEMBL219861,CC(C)Cn1c(=O)n(C)c(=O)c2c(C(=O)N3C[C@H](O)CO3)...,75.12,Homo sapiens

CC(C)Cn1cnc2c(N)nc3ccccc3c21

         Drug_ID                        SMILES      Y            Species
1539  CHEMBL1282  CC(C)Cn1cnc2c(N)nc3ccccc3c21  85.19       Homo sapiens
2102  CHEMBL1282  CC(C)Cn1cnc2c(N)nc3ccccc3c21  99.25       Mus musculus
2594  CHEMBL1282  CC(C)Cn1cnc2c(N)nc3ccccc3c21  82.05  Rattus norvegicus

CC(C)N(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc1ccccc1

,Drug_ID,SMILES,Y,Species
322,CHEMBL1800658,CC(C)N(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCC...,92.48,Cavia porcellus
1830,CHEMBL1800658,CC(C)N(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCC...,97.20,Homo sapiens

CC(C)N1CCN(Cc2cnc(-c3cc(-c4cccc5[nH]ccc45)cc4[nH]ncc34)o2)CC1

,Drug_ID,SMILES,Y,Species
714,CHEMBL2216859,CC(C)N1CCN(Cc2cnc(-c3cc(-c4cccc5[nH]ccc45)cc4[...,97.00,Homo sapiens
2321,CHEMBL2216859,CC(C)N1CCN(Cc2cnc(-c3cc(-c4cccc5[nH]ccc45)cc4[...,96.42,Rattus norvegicus

CC(C)NC(=O)c1nn(-c2ccc(Cl)cc2)c(=O)c2c(N)scc12

,Drug_ID,SMILES,Y,Species
1908,CHEMBL1097062,CC(C)NC(=O)c1nn(-c2ccc(Cl)cc2)c(=O)c2c(N)scc12,99.01,Homo sapiens
2066,CHEMBL1097062,CC(C)NC(=O)c1nn(-c2ccc(Cl)cc2)c(=O)c2c(N)scc12,97.81,Mus musculus

CC(C)NCC(O)COc1ccc(CCOCC2CC2)cc1

        Drug_ID                            SMILES      Y            Species
548   CHEMBL423  CC(C)NCC(O)COc1ccc(CCOCC2CC2)cc1  27.55       Homo sapiens
2390  CHEMBL423  CC(C)NCC(O)COc1ccc(CCOCC2CC2)cc1  59.11  Rattus norvegicus

CC(C)NCC(O)COc1ccc(COCCOC(C)C)cc1

,Drug_ID,SMILES,Y,Species
46,CHEMBL645,CC(C)NCC(O)COc1ccc(COCCOC(C)C)cc1,25.75,Canis lupus familiaris
2773,CHEMBL645,CC(C)NCC(O)COc1ccc(COCCOC(C)C)cc1,23.19,Rattus norvegicus

CC(C)NC[C@@H](O)COc1cccc2ccccc12

           Drug_ID                            SMILES      Y            Species
1847  CHEMBL275742  CC(C)NC[C@@H](O)COc1cccc2ccccc12  82.39       Homo sapiens
1976  CHEMBL275742  CC(C)NC[C@@H](O)COc1cccc2ccccc12  82.05       Mus musculus
2344  CHEMBL275742  CC(C)NC[C@@H](O)COc1cccc2ccccc12  82.05  Rattus norvegicus

CC(C)NC[C@H](O)COc1cccc2ccccc12

           Drug_ID                           SMILES      Y            Species
1543  CHEMBL452861  CC(C)NC[C@H](O)COc1cccc2ccccc12  86.05       Homo sapiens
2591  CHEMBL452861  CC(C)NC[C@H](O)COc1cccc2ccccc12  79.55  Rattus norvegicus

CC(C)Oc1cc(-n2cnc3ccc(N[C@@H](CO)c4ccc(F)cn4)nc32)n[nH]1

,Drug_ID,SMILES,Y,Species
175,CHEMBL2151322,CC(C)Oc1cc(-n2cnc3ccc(N[C@@H](CO)c4ccc(F)cn4)n...,69.61,Canis lupus familiaris
911,CHEMBL2151322,CC(C)Oc1cc(-n2cnc3ccc(N[C@@H](CO)c4ccc(F)cn4)n...,91.82,Homo sapiens
2345,CHEMBL2151322,CC(C)Oc1cc(-n2cnc3ccc(N[C@@H](CO)c4ccc(F)cn4)n...,81.36,Rattus norvegicus

CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cc3)nc(NC(CO)CO)c2Cl)n[nH]1

,Drug_ID,SMILES,Y,Species
699,CHEMBL456324,CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cc3)nc(NC(C...,96.42,Homo sapiens
2405,CHEMBL456324,CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cc3)nc(NC(C...,95.72,Rattus norvegicus

CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cn3)nc(OC(CO)CO)c2Cl)n[nH]1

,Drug_ID,SMILES,Y,Species
976,CHEMBL515062,CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cn3)nc(OC(C...,82.39,Homo sapiens
2123,CHEMBL515062,CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cn3)nc(OC(C...,82.72,Rattus norvegicus

CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ncc(F)cn3)ncc2Cl)n[nH]1

,Drug_ID,SMILES,Y,Species
22,CHEMBL455920,CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ncc(F)cn3)ncc2Cl)...,79.55,Canis lupus familiaris
1342,CHEMBL455920,CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ncc(F)cn3)ncc2Cl)...,88.82,Homo sapiens
1951,CHEMBL455920,CC(C)Oc1cc(Nc2nc(N[C@@H](C)c3ncc(F)cn3)ncc2Cl)...,92.64,Mus musculus

CC(C)Oc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2)n[nH]1

,Drug_ID,SMILES,Y,Species
79,CHEMBL2151324,CC(C)Oc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)...,75.12,Canis lupus familiaris
687,CHEMBL2151324,CC(C)Oc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)...,94.90,Homo sapiens
2719,CHEMBL2151324,CC(C)Oc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)...,88.11,Rattus norvegicus

CC(C)Oc1ccc2c(=O)c(-c3ccccc3)coc2c1

,Drug_ID,SMILES,Y,Species
192,CHEMBL165790,CC(C)Oc1ccc2c(=O)c(-c3ccccc3)coc2c1,99.49,Canis lupus familiaris
951,CHEMBL165790,CC(C)Oc1ccc2c(=O)c(-c3ccccc3)coc2c1,99.47,Homo sapiens
2676,CHEMBL165790,CC(C)Oc1ccc2c(=O)c(-c3ccccc3)coc2c1,99.44,Rattus norvegicus

CC(C)S(=O)(=O)N(C)c1cc(C(=O)N[C@@H](Cc2ccccc2)[C@@H](N)CF)cc(NC[C@H]2C[C@@H]2C)n1

,Drug_ID,SMILES,Y,Species
916,CHEMBL230245,CC(C)S(=O)(=O)N(C)c1cc(C(=O)N[C@@H](Cc2ccccc2)...,95.53,Homo sapiens
1957,CHEMBL230245,CC(C)S(=O)(=O)N(C)c1cc(C(=O)N[C@@H](Cc2ccccc2)...,98.09,Mus musculus

CC(C)[C@H](C(=O)Nc1nccs1)c1ccc(Cl)cc1

,Drug_ID,SMILES,Y,Species
960,CHEMBL594671,CC(C)[C@H](C(=O)Nc1nccs1)c1ccc(Cl)cc1,99.26,Homo sapiens
2001,CHEMBL594671,CC(C)[C@H](C(=O)Nc1nccs1)c1ccc(Cl)cc1,98.89,Mus musculus
2272,CHEMBL594671,CC(C)[C@H](C(=O)Nc1nccs1)c1ccc(Cl)cc1,98.94,Rattus norvegicus

CC(C)[C@H](O)C(=O)N[C@@H](C)C(=O)N[C@@H]1C(=O)N(C)CCc2ccccc21

,Drug_ID,SMILES,Y,Species
1263,CHEMBL520733,CC(C)[C@H](O)C(=O)N[C@@H](C)C(=O)N[C@@H]1C(=O)...,19.71,Homo sapiens
2012,CHEMBL520733,CC(C)[C@H](O)C(=O)N[C@@H](C)C(=O)N[C@@H]1C(=O)...,14.23,Mus musculus
2417,CHEMBL520733,CC(C)[C@H](O)C(=O)N[C@@H](C)C(=O)N[C@@H]1C(=O)...,20.83,Rattus norvegicus

CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1

,Drug_ID,SMILES,Y,Species
1336,CHEMBL1086310,CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1,87.37,Homo sapiens
2651,CHEMBL1086310,CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1,87.62,Rattus norvegicus

CC(C)c1noc(C2CCN(c3ncnc(Nc4ccc(S(C)(=O)=O)cc4F)c3[N+](=O)[O-])CC2)n1

,Drug_ID,SMILES,Y,Species
1178,CHEMBL461384,CC(C)c1noc(C2CCN(c3ncnc(Nc4ccc(S(C)(=O)=O)cc4F...,99.01,Homo sapiens
2522,CHEMBL461384,CC(C)c1noc(C2CCN(c3ncnc(Nc4ccc(S(C)(=O)=O)cc4F...,98.40,Rattus norvegicus

CC(C)n1c(/C=C/C(O)CC(O)CC(=O)O)c(-c2ccc(F)cc2)c2ccccc21

,Drug_ID,SMILES,Y,Species
218,CHEMBL2220442,CC(C)n1c(/C=C/C(O)CC(O)CC(=O)O)c(-c2ccc(F)cc2)...,99.72,Canis lupus familiaris
1856,CHEMBL2220442,CC(C)n1c(/C=C/C(O)CC(O)CC(=O)O)c(-c2ccc(F)cc2)...,99.52,Homo sapiens

CC(CC(=O)OC(C)(C)C)NC(=O)C1=NOC(C(O)(C(F)(F)F)C(F)(F)F)C1

,Drug_ID,SMILES,Y,Species
1086,CHEMBL213556,CC(CC(=O)OC(C)(C)C)NC(=O)C1=NOC(C(O)(C(F)(F)F)...,80.65,Homo sapiens
2053,CHEMBL213556,CC(CC(=O)OC(C)(C)C)NC(=O)C1=NOC(C(O)(C(F)(F)F)...,81.01,Mus musculus

CC(Cc1ccccn1)N1C(=O)c2ccccc2C1C(=O)NCc1ccc(OC(F)(F)F)cc1

,Drug_ID,SMILES,Y,Species
1895,CHEMBL2164360,CC(Cc1ccccn1)N1C(=O)c2ccccc2C1C(=O)NCc1ccc(OC(...,98.89,Homo sapiens
2147,CHEMBL2164360,CC(Cc1ccccn1)N1C(=O)c2ccccc2C1C(=O)NCc1ccc(OC(...,96.34,Rattus norvegicus

CC(NC(=O)c1cc2ccccc2[nH]1)c1ccccc1

,Drug_ID,SMILES,Y,Species
472,CHEMBL509973,CC(NC(=O)c1cc2ccccc2[nH]1)c1ccccc1,97.81,Homo sapiens
2304,CHEMBL509973,CC(NC(=O)c1cc2ccccc2[nH]1)c1ccccc1,96.34,Rattus norvegicus

CC(O)(C(=O)Nc1ccc(S(=O)(=O)N2CCCC2)cc1)C(F)(F)F

,Drug_ID,SMILES,Y,Species
1088,CHEMBL262273,CC(O)(C(=O)Nc1ccc(S(=O)(=O)N2CCCC2)cc1)C(F)(F)F,78.01,Homo sapiens
2019,CHEMBL262273,CC(O)(C(=O)Nc1ccc(S(=O)(=O)N2CCCC2)cc1)C(F)(F)F,91.82,Mus musculus
2393,CHEMBL262273,CC(O)(C(=O)Nc1ccc(S(=O)(=O)N2CCCC2)cc1)C(F)(F)F,88.11,Rattus norvegicus

CC(O)(C(=O)Nc1ccc(S(=O)(=O)N2CCOCC2)cc1)C(F)(F)F

,Drug_ID,SMILES,Y,Species
584,CHEMBL165330,CC(O)(C(=O)Nc1ccc(S(=O)(=O)N2CCOCC2)cc1)C(F)(F)F,62.94,Homo sapiens
2317,CHEMBL165330,CC(O)(C(=O)Nc1ccc(S(=O)(=O)N2CCOCC2)cc1)C(F)(F)F,84.90,Rattus norvegicus

CC(O)(C(=O)Nc1cccc(S(=O)(=O)c2ccccc2)c1)C(F)(F)F

,Drug_ID,SMILES,Y,Species
593,CHEMBL422649,CC(O)(C(=O)Nc1cccc(S(=O)(=O)c2ccccc2)c1)C(F)(F)F,90.91,Homo sapiens
2074,CHEMBL422649,CC(O)(C(=O)Nc1cccc(S(=O)(=O)c2ccccc2)c1)C(F)(F)F,93.39,Mus musculus
2537,CHEMBL422649,CC(O)(C(=O)Nc1cccc(S(=O)(=O)c2ccccc2)c1)C(F)(F)F,94.06,Rattus norvegicus

CC1(C)CNC(=O)c2sc(N3CCOCC3)nc2C1

,Drug_ID,SMILES,Y,Species
1502,CHEMBL1381989,CC1(C)CNC(=O)c2sc(N3CCOCC3)nc2C1,29.90,Homo sapiens
2574,CHEMBL1381989,CC1(C)CNC(=O)c2sc(N3CCOCC3)nc2C1,48.27,Rattus norvegicus

CC1(C)[C@@H]2CC[C@@]1(CS(=O)(=O)N1CCN(c3ccc(C(F)(F)F)cn3)CC1)C(=O)C2

,Drug_ID,SMILES,Y,Species
1855,CHEMBL464081,CC1(C)[C@@H]2CC[C@@]1(CS(=O)(=O)N1CCN(c3ccc(C(...,99.08,Homo sapiens
2360,CHEMBL464081,CC1(C)[C@@H]2CC[C@@]1(CS(=O)(=O)N1CCN(c3ccc(C(...,98.09,Rattus norvegicus

CC1(C)[C@H](NC(=O)/C(=N\OCc2cc(=O)c(O)cn2O)c2csc(N)n2)C(=O)N1OS(=O)(=O)O

,Drug_ID,SMILES,Y,Species
1734,CHEMBL1256967,CC1(C)[C@H](NC(=O)/C(=N\OCc2cc(=O)c(O)cn2O)c2c...,69.12,Homo sapiens
2228,CHEMBL1256967,CC1(C)[C@H](NC(=O)/C(=N\OCc2cc(=O)c(O)cn2O)c2c...,87.62,Rattus norvegicus

CC1(CCCc2cc(=O)oc3[nH]c(=O)[nH]c(=O)c23)CC1

,Drug_ID,SMILES,Y,Species
1602,CHEMBL2036958,CC1(CCCc2cc(=O)oc3[nH]c(=O)[nH]c(=O)c23)CC1,98.51,Homo sapiens
2004,CHEMBL2036958,CC1(CCCc2cc(=O)oc3[nH]c(=O)[nH]c(=O)c23)CC1,97.32,Mus musculus
2152,CHEMBL2036958,CC1(CCCc2cc(=O)oc3[nH]c(=O)[nH]c(=O)c23)CC1,98.51,Rattus norvegicus

CC1=C(C(=O)OCc2ccccc2)C(c2cccs2)NC(=O)N1

,Drug_ID,SMILES,Y,Species
406,CHEMBL239336,CC1=C(C(=O)OCc2ccccc2)C(c2cccs2)NC(=O)N1,97.32,Homo sapiens
2055,CHEMBL239336,CC1=C(C(=O)OCc2ccccc2)C(c2cccs2)NC(=O)N1,97.00,Mus musculus
2503,CHEMBL239336,CC1=C(C(=O)OCc2ccccc2)C(c2cccs2)NC(=O)N1,98.29,Rattus norvegicus

CC1=NC(c2ccc(F)cc2)(c2cccc(-c3cccnc3)c2)N=C1N

,Drug_ID,SMILES,Y,Species
636,CHEMBL2180024,CC1=NC(c2ccc(F)cc2)(c2cccc(-c3cccnc3)c2)N=C1N,95.12,Homo sapiens
2083,CHEMBL2180024,CC1=NC(c2ccc(F)cc2)(c2cccc(-c3cccnc3)c2)N=C1N,93.24,Mus musculus
2178,CHEMBL2180024,CC1=NC(c2ccc(F)cc2)(c2cccc(-c3cccnc3)c2)N=C1N,91.28,Rattus norvegicus

CC1=NC(c2cccc(-c3cncc(Cl)c3)c2)(C2CC2)N=C1N

,Drug_ID,SMILES,Y,Species
913,CHEMBL2180033,CC1=NC(c2cccc(-c3cncc(Cl)c3)c2)(C2CC2)N=C1N,93.53,Homo sapiens
1962,CHEMBL2180033,CC1=NC(c2cccc(-c3cncc(Cl)c3)c2)(C2CC2)N=C1N,95.43,Mus musculus
2631,CHEMBL2180033,CC1=NC(c2cccc(-c3cncc(Cl)c3)c2)(C2CC2)N=C1N,89.91,Rattus norvegicus

CC1CN(c2cc(=O)[nH]c(NCc3cccc4ccccc34)n2)CCO1

,Drug_ID,SMILES,Y,Species
438,CHEMBL2165192,CC1CN(c2cc(=O)[nH]c(NCc3cccc4ccccc34)n2)CCO1,98.7,Homo sapiens
2157,CHEMBL2165192,CC1CN(c2cc(=O)[nH]c(NCc3cccc4ccccc34)n2)CCO1,97.6,Rattus norvegicus

CCC#Cc1cncc(-c2ccc3c(c2)C2(N=C(C)C(N)=N2)[C@]2(CC[C@H](OC)CC2)C3)c1

,Drug_ID,SMILES,Y,Species
572,CHEMBL2152920,CCC#Cc1cncc(-c2ccc3c(c2)C2(N=C(C)C(N)=N2)[C@]2...,96.17,Homo sapiens
2057,CHEMBL2152920,CCC#Cc1cncc(-c2ccc3c(c2)C2(N=C(C)C(N)=N2)[C@]2...,98.00,Mus musculus

CCC(=O)O[C@]1(C(=O)SCF)[C@H](C)C[C@H]2[C@@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@@]21C

,Drug_ID,SMILES,Y,Species
35,CHEMBL1473,CCC(=O)O[C@]1(C(=O)SCF)[C@H](C)C[C@H]2[C@@H]3C...,98.84,Canis lupus familiaris
602,CHEMBL1473,CCC(=O)O[C@]1(C(=O)SCF)[C@H](C)C[C@H]2[C@@H]3C...,98.09,Homo sapiens
2563,CHEMBL1473,CCC(=O)O[C@]1(C(=O)SCF)[C@H](C)C[C@H]2[C@@H]3C...,98.47,Rattus norvegicus

CCC(C)NC(=O)c1c(C)nn(-c2ccccc2)c1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
1843,CHEMBL1916280,CCC(C)NC(=O)c1c(C)nn(-c2ccccc2)c1NS(=O)(=O)c1c...,99.41,Homo sapiens
2776,CHEMBL1916280,CCC(C)NC(=O)c1c(C)nn(-c2ccccc2)c1NS(=O)(=O)c1c...,96.65,Rattus norvegicus

CCC(CC)NC(=O)c1c(C)nn(-c2ccccc2)c1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
107,CHEMBL1916272,CCC(CC)NC(=O)c1c(C)nn(-c2ccccc2)c1NS(=O)(=O)c1...,95.82,Canis lupus familiaris
1840,CHEMBL1916272,CCC(CC)NC(=O)c1c(C)nn(-c2ccccc2)c1NS(=O)(=O)c1...,99.51,Homo sapiens
2799,CHEMBL1916272,CCC(CC)NC(=O)c1c(C)nn(-c2ccccc2)c1NS(=O)(=O)c1...,97.00,Rattus norvegicus

CCC(CC)NC(=O)c1c(C)nn(C(C)C)c1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
683,CHEMBL1934266,CCC(CC)NC(=O)c1c(C)nn(C(C)C)c1NS(=O)(=O)c1ccc(...,96.5,Homo sapiens
2322,CHEMBL1934266,CCC(CC)NC(=O)c1c(C)nn(C(C)C)c1NS(=O)(=O)c1ccc(...,91.1,Rattus norvegicus

CCC(CC)NC(=O)c1cn(-c2ccccc2)nc1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
1607,CHEMBL1916263,CCC(CC)NC(=O)c1cn(-c2ccccc2)nc1NS(=O)(=O)c1ccc...,99.87,Homo sapiens
2772,CHEMBL1916263,CCC(CC)NC(=O)c1cn(-c2ccccc2)nc1NS(=O)(=O)c1ccc...,99.67,Rattus norvegicus

CCC(CC)NC(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)C1CCCC1

,Drug_ID,SMILES,Y,Species
202,CHEMBL1916260,CCC(CC)NC(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)C1CCCC1,96.57,Canis lupus familiaris
607,CHEMBL1916260,CCC(CC)NC(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)C1CCCC1,99.78,Homo sapiens
2638,CHEMBL1916260,CCC(CC)NC(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)C1CCCC1,99.79,Rattus norvegicus

CCC(CC)NC(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
601,CHEMBL1916082,CCC(CC)NC(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)c1ccc...,98.61,Homo sapiens
2710,CHEMBL1916082,CCC(CC)NC(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)c1ccc...,97.66,Rattus norvegicus

CCC(CC)[C@@H](CO)NS(=O)(=O)c1ccc(Cl)s1

,Drug_ID,SMILES,Y,Species
1273,CHEMBL480558,CCC(CC)[C@@H](CO)NS(=O)(=O)c1ccc(Cl)s1,92.16,Homo sapiens
2046,CHEMBL480558,CCC(CC)[C@@H](CO)NS(=O)(=O)c1ccc(Cl)s1,89.05,Mus musculus
2214,CHEMBL480558,CCC(CC)[C@@H](CO)NS(=O)(=O)c1ccc(Cl)s1,90.91,Rattus norvegicus

CCC(CC)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
1036,CHEMBL1934271,CCC(CC)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=...,98.00,Homo sapiens
2400,CHEMBL1934271,CCC(CC)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=...,91.82,Rattus norvegicus

CCCC(=O)Nc1ccc(OCC(O)CNC(C)C)c(C(C)=O)c1

,Drug_ID,SMILES,Y,Species
102,CHEMBL642,CCCC(=O)Nc1ccc(OCC(O)CNC(C)C)c(C(C)=O)c1,21.21,Canis lupus familiaris
2617,CHEMBL642,CCCC(=O)Nc1ccc(OCC(O)CNC(C)C)c(C(C)=O)c1,28.95,Rattus norvegicus

CCCCC(=O)N(Cc1ccc(-c2ccccc2-c2nnn[nH]2)cc1)[C@H](C(=O)O)C(C)C

,Drug_ID,SMILES,Y,Species
29,CHEMBL1069,CCCCC(=O)N(Cc1ccc(-c2ccccc2-c2nnn[nH]2)cc1)[C@...,98.64,Canis lupus familiaris
1324,CHEMBL1069,CCCCC(=O)N(Cc1ccc(-c2ccccc2-c2nnn[nH]2)cc1)[C@...,99.78,Homo sapiens

CCCCCCC(=O)CCCCCC/C=C/C[C@@H](O)[C@H](O)[C@@](N)(CO)C(=O)O

,Drug_ID,SMILES,Y,Species
1975,CHEMBL55076,CCCCCCC(=O)CCCCCC/C=C/C[C@@H](O)[C@H](O)[C@@](...,93.8,Mus musculus
2774,CHEMBL55076,CCCCCCC(=O)CCCCCC/C=C/C[C@@H](O)[C@H](O)[C@@](...,97.2,Rattus norvegicus

CCCCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc1ccccc1

,Drug_ID,SMILES,Y,Species
315,CHEMBL1800659,CCCCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc...,83.04,Cavia porcellus
1948,CHEMBL1800659,CCCCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc...,94.68,Homo sapiens
2447,CHEMBL1800659,CCCCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc...,92.95,Rattus norvegicus

CCCCNC(=O)NS(=O)(=O)c1ccc(C)cc1

        Drug_ID                           SMILES      Y            Species
458   CHEMBL782  CCCCNC(=O)NS(=O)(=O)c1ccc(C)cc1  98.09       Homo sapiens
2709  CHEMBL782  CCCCNC(=O)NS(=O)(=O)c1ccc(C)cc1  97.71  Rattus norvegicus

CCCCNC(=O)c1ccc(Oc2ccc(CC(=O)O)cc2OC)c(NS(=O)(=O)c2ccc(Cl)cc2Cl)c1

,Drug_ID,SMILES,Y,Species
67,CHEMBL589973,CCCCNC(=O)c1ccc(Oc2ccc(CC(=O)O)cc2OC)c(NS(=O)(...,98.29,Canis lupus familiaris
1292,CHEMBL589973,CCCCNC(=O)c1ccc(Oc2ccc(CC(=O)O)cc2OC)c(NS(=O)(...,99.80,Homo sapiens
2476,CHEMBL589973,CCCCNC(=O)c1ccc(Oc2ccc(CC(=O)O)cc2OC)c(NS(=O)(...,99.81,Rattus norvegicus

CCCCNc1cc(C(=O)O)cc(S(N)(=O)=O)c1Oc1ccccc1

,Drug_ID,SMILES,Y,Species
721,CHEMBL1072,CCCCNc1cc(C(=O)O)cc(S(N)(=O)=O)c1Oc1ccccc1,98.44,Homo sapiens
2456,CHEMBL1072,CCCCNc1cc(C(=O)O)cc(S(N)(=O)=O)c1Oc1ccccc1,96.34,Rattus norvegicus

CCCCNc1nc(SCCC)nc2c1nnn2[C@@H]1C[C@H](CO)[C@@H](O)[C@H]1O

,Drug_ID,SMILES,Y,Species
2,CHEMBL401158,CCCCNc1nc(SCCC)nc2c1nnn2[C@@H]1C[C@H](CO)[C@@H...,95.33,Canis lupus familiaris
481,CHEMBL401158,CCCCNc1nc(SCCC)nc2c1nnn2[C@@H]1C[C@H](CO)[C@@H...,97.60,Homo sapiens

CCCC[C@H](NC[C@@H]1Cc2cccc(c2)CCCCc2cc(cc(N(CCC)S(C)(=O)=O)c2)C(=O)N1)C(=O)NCC(C)C

,Drug_ID,SMILES,Y,Species
1136,CHEMBL385374,CCCC[C@H](NC[C@@H]1Cc2cccc(c2)CCCCc2cc(cc(N(CC...,99.6,Homo sapiens
2100,CHEMBL385374,CCCC[C@H](NC[C@@H]1Cc2cccc(c2)CCCCc2cc(cc(N(CC...,99.8,Mus musculus

CCCCc1nc(Cl)c(C(=O)O)n1Cc1ccc(-c2ccccc2-c2nn[nH]n2)cc1

,Drug_ID,SMILES,Y,Species
1631,CHEMBL907,CCCCc1nc(Cl)c(C(=O)O)n1Cc1ccc(-c2ccccc2-c2nn[n...,99.51,Homo sapiens
2544,CHEMBL907,CCCCc1nc(Cl)c(C(=O)O)n1Cc1ccc(-c2ccccc2-c2nn[n...,99.78,Rattus norvegicus

CCCCc1nc2c(N)nc3ccccc3c2n1CC(C)C

           Drug_ID                            SMILES      Y            Species
1816  CHEMBL192307  CCCCc1nc2c(N)nc3ccccc3c2n1CC(C)C  93.80       Homo sapiens
2357  CHEMBL192307  CCCCc1nc2c(N)nc3ccccc3c2n1CC(C)C  96.93  Rattus norvegicus

CCCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc1ccccc1

,Drug_ID,SMILES,Y,Species
254,CHEMBL1800657,CCCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc1...,89.05,Cavia porcellus
1217,CHEMBL1800657,CCCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc1...,93.94,Homo sapiens

CCCN(c1cccc(C#N)c1)P(=O)(c1ccccc1)c1ccccc1

,Drug_ID,SMILES,Y,Species
802,CHEMBL2312920,CCCN(c1cccc(C#N)c1)P(=O)(c1ccccc1)c1ccccc1,99.44,Homo sapiens
2011,CHEMBL2312920,CCCN(c1cccc(C#N)c1)P(=O)(c1ccccc1)c1ccccc1,95.33,Mus musculus
2671,CHEMBL2312920,CCCN(c1cccc(C#N)c1)P(=O)(c1ccccc1)c1ccccc1,93.67,Rattus norvegicus

CCCN(c1cccc(S(C)(=O)=O)c1)P(=O)(c1ccccc1)c1ccccc1

,Drug_ID,SMILES,Y,Species
263,CHEMBL2312921,CCCN(c1cccc(S(C)(=O)=O)c1)P(=O)(c1ccccc1)c1ccccc1,71.05,Cavia porcellus
1392,CHEMBL2312921,CCCN(c1cccc(S(C)(=O)=O)c1)P(=O)(c1ccccc1)c1ccccc1,96.79,Homo sapiens
2690,CHEMBL2312921,CCCN(c1cccc(S(C)(=O)=O)c1)P(=O)(c1ccccc1)c1ccccc1,81.36,Rattus norvegicus

CCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1

,Drug_ID,SMILES,Y,Species
41,CHEMBL2312933,CCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,82.39,Canis lupus familiaris
261,CHEMBL2312933,CCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,69.12,Cavia porcellus
1595,CHEMBL2312933,CCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,97.95,Homo sapiens
1990,CHEMBL2312933,CCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,87.62,Mus musculus
2306,CHEMBL2312933,CCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,84.90,Rattus norvegicus

CCCN(c1ccon1)P(=O)(c1ccccc1)c1ccccc1

,Drug_ID,SMILES,Y,Species
300,CHEMBL2312918,CCCN(c1ccon1)P(=O)(c1ccccc1)c1ccccc1,81.71,Cavia porcellus
650,CHEMBL2312918,CCCN(c1ccon1)P(=O)(c1ccccc1)c1ccccc1,96.26,Homo sapiens
2035,CHEMBL2312918,CCCN(c1ccon1)P(=O)(c1ccccc1)c1ccccc1,87.11,Mus musculus
2255,CHEMBL2312918,CCCN(c1ccon1)P(=O)(c1ccccc1)c1ccccc1,84.90,Rattus norvegicus

CCCN(c1cncnc1)P(=O)(c1ccccc1)c1ccccc1

,Drug_ID,SMILES,Y,Species
245,CHEMBL2313230,CCCN(c1cncnc1)P(=O)(c1ccccc1)c1ccccc1,47.12,Cavia porcellus
1688,CHEMBL2313230,CCCN(c1cncnc1)P(=O)(c1ccccc1)c1ccccc1,88.11,Homo sapiens

CCCNC(=O)NS(=O)(=O)c1ccc(Cl)cc1

       Drug_ID                           SMILES      Y                 Species
18   CHEMBL498  CCCNC(=O)NS(=O)(=O)c1ccc(Cl)cc1  85.77  Canis lupus familiaris
744  CHEMBL498  CCCNC(=O)NS(=O)(=O)c1ccc(Cl)cc1  96.00            Homo sapiens

CCCNC(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1

,Drug_ID,SMILES,Y,Species
8,CHEMBL2312928,CCCNC(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,80.29,Canis lupus familiaris
281,CHEMBL2312928,CCCNC(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,81.01,Cavia porcellus
2595,CHEMBL2312928,CCCNC(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,82.72,Rattus norvegicus

CCCNCC(O)COc1ccccc1C(=O)CCc1ccccc1

        Drug_ID                              SMILES      Y            Species
1271  CHEMBL631  CCCNCC(O)COc1ccccc1C(=O)CCc1ccccc1  92.95       Homo sapiens
2403  CHEMBL631  CCCNCC(O)COc1ccccc1C(=O)CCc1ccccc1  95.91  Rattus norvegicus

CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1

         Drug_ID                          SMILES      Y            Species
1304  CHEMBL1483  CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1  95.43       Homo sapiens
2536  CHEMBL1483  CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1  94.19  Rattus norvegicus

CCCSc1nc(N)c2ncn([C@@H]3O[C@H](CO)[C@@H](O)[C@H]3O)c2n1

,Drug_ID,SMILES,Y,Species
81,CHEMBL577902,CCCSc1nc(N)c2ncn([C@@H]3O[C@H](CO)[C@@H](O)[C@...,40.89,Canis lupus familiaris
1410,CHEMBL577902,CCCSc1nc(N)c2ncn([C@@H]3O[C@H](CO)[C@@H](O)[C@...,51.73,Homo sapiens

CCCSc1nc(N[C@@H]2C[C@H]2c2ccccc2)c2nnn([C@@H]3C[C@H](CO)[C@@H](O)[C@H]3O)c2n1

,Drug_ID,SMILES,Y,Species
170,CHEMBL250687,CCCSc1nc(N[C@@H]2C[C@H]2c2ccccc2)c2nnn([C@@H]3...,99.19,Canis lupus familiaris
1773,CHEMBL250687,CCCSc1nc(N[C@@H]2C[C@H]2c2ccccc2)c2nnn([C@@H]3...,99.23,Homo sapiens

CCC[C@@H](CNC(=O)c1nc(Cl)c(N)nc1N)[N+](C)(C)CCCc1ccc(OC)cc1

,Drug_ID,SMILES,Y,Species
1565,CHEMBL2021706,CCC[C@@H](CNC(=O)c1nc(Cl)c(N)nc1N)[N+](C)(C)CC...,48.85,Homo sapiens
2475,CHEMBL2021706,CCC[C@@H](CNC(=O)c1nc(Cl)c(N)nc1N)[N+](C)(C)CC...,54.59,Rattus norvegicus

CCC[C@@H](c1ccc(C(=O)O)c(Oc2cccc(Cl)c2)c1)N1CCC[C@H](n2cc(C)c(=O)[nH]c2=O)C1

,Drug_ID,SMILES,Y,Species
1139,CHEMBL2179274,CCC[C@@H](c1ccc(C(=O)O)c(Oc2cccc(Cl)c2)c1)N1CC...,99.30,Homo sapiens
2602,CHEMBL2179274,CCC[C@@H](c1ccc(C(=O)O)c(Oc2cccc(Cl)c2)c1)N1CC...,98.21,Rattus norvegicus

CCC[C@H](CO)Nc1nc(S[C@@H](C)c2cccc(C#N)c2)nc2[nH]c(=O)sc12

,Drug_ID,SMILES,Y,Species
1623,CHEMBL2349318,CCC[C@H](CO)Nc1nc(S[C@@H](C)c2cccc(C#N)c2)nc2[...,99.93,Homo sapiens
2154,CHEMBL2349318,CCC[C@H](CO)Nc1nc(S[C@@H](C)c2cccc(C#N)c2)nc2[...,99.92,Rattus norvegicus

CCC[C@H](c1ccc(C(=O)O)c(Oc2cccc(Cl)c2)c1)N1CCC[C@H](n2cc(C)c(=O)[nH]c2=O)C1

,Drug_ID,SMILES,Y,Species
375,CHEMBL2179273,CCC[C@H](c1ccc(C(=O)O)c(Oc2cccc(Cl)c2)c1)N1CCC...,98.81,Homo sapiens
2477,CHEMBL2179273,CCC[C@H](c1ccc(C(=O)O)c(Oc2cccc(Cl)c2)c1)N1CCC...,98.40,Rattus norvegicus

CCCc1cc(=O)[nH]c(=S)[nH]1

         Drug_ID                     SMILES      Y            Species
499   CHEMBL1518  CCCc1cc(=O)[nH]c(=S)[nH]1  40.89       Homo sapiens
2379  CHEMBL1518  CCCc1cc(=O)[nH]c(=S)[nH]1  37.60  Rattus norvegicus

CCCc1nc2c(C)cc(-c3nc4ccccc4n3C)cc2n1Cc1ccc(-c2ccccc2C(=O)O)cc1

,Drug_ID,SMILES,Y,Species
0,CHEMBL1017,CCCc1nc2c(C)cc(-c3nc4ccccc4n3C)cc2n1Cc1ccc(-c2...,98.25,Canis lupus familiaris
1944,CHEMBL1017,CCCc1nc2c(C)cc(-c3nc4ccccc4n3C)cc2n1Cc1ccc(-c2...,99.23,Homo sapiens
2366,CHEMBL1017,CCCc1nc2c(C)cc(-c3nc4ccccc4n3C)cc2n1Cc1ccc(-c2...,99.62,Rattus norvegicus

CCCc1nn(C)c2c(=O)[nH]c(-c3cc(S(=O)(=O)N4CCN(C)CC4)ccc3OCC)nc12

,Drug_ID,SMILES,Y,Species
219,CHEMBL192,CCCc1nn(C)c2c(=O)[nH]c(-c3cc(S(=O)(=O)N4CCN(C)...,82.39,Canis lupus familiaris
835,CHEMBL192,CCCc1nn(C)c2c(=O)[nH]c(-c3cc(S(=O)(=O)N4CCN(C)...,95.53,Homo sapiens
2260,CHEMBL192,CCCc1nn(C)c2c(=O)[nH]c(-c3cc(S(=O)(=O)N4CCN(C)...,90.12,Rattus norvegicus

CCCn1c(=O)[nH]c(=O)c2[nH]cnc21

,Drug_ID,SMILES,Y,Species
171,CHEMBL279898,CCCn1c(=O)[nH]c(=O)c2[nH]cnc21,60.77,Canis lupus familiaris
1541,CHEMBL279898,CCCn1c(=O)[nH]c(=O)c2[nH]cnc21,67.12,Homo sapiens
2590,CHEMBL279898,CCCn1c(=O)[nH]c(=O)c2[nH]cnc21,78.79,Rattus norvegicus

CCCn1c(=O)[nH]c2nc(-c3ccc(S(=O)(=O)N4CCN(Cc5ccc(Cl)cc5)CC4)cc3)[nH]c2c1=O

,Drug_ID,SMILES,Y,Species
2010,CHEMBL482436,CCCn1c(=O)[nH]c2nc(-c3ccc(S(=O)(=O)N4CCN(Cc5cc...,99.93,Mus musculus
2551,CHEMBL482436,CCCn1c(=O)[nH]c2nc(-c3ccc(S(=O)(=O)N4CCN(Cc5cc...,99.94,Rattus norvegicus

CCN(C(=O)c1ccc(-c2ccc(Cl)cc2)o1)c1ccc(N2CCNCC2)cc1

,Drug_ID,SMILES,Y,Species
746,CHEMBL2017459,CCN(C(=O)c1ccc(-c2ccc(Cl)cc2)o1)c1ccc(N2CCNCC2...,95.82,Homo sapiens
2047,CHEMBL2017459,CCN(C(=O)c1ccc(-c2ccc(Cl)cc2)o1)c1ccc(N2CCNCC2...,96.09,Mus musculus
2373,CHEMBL2017459,CCN(C(=O)c1ccc(-c2ccc(Cl)cc2)o1)c1ccc(N2CCNCC2...,95.72,Rattus norvegicus

CCN(C(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)c1ccc(-c2cnco2)cc1)C1CCCCC1

,Drug_ID,SMILES,Y,Species
121,CHEMBL1916271,CCN(C(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)c1ccc(-c2...,99.75,Canis lupus familiaris
1426,CHEMBL1916271,CCN(C(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)c1ccc(-c2...,98.70,Homo sapiens
2467,CHEMBL1916271,CCN(C(=O)c1cnn(-c2ccccc2)c1NS(=O)(=O)c1ccc(-c2...,99.43,Rattus norvegicus

CCN(CC)CCN1C(=O)[C@@](O)(c2ccccc2Cl)c2c1cc(C(N)=O)cc2C(F)(F)F

,Drug_ID,SMILES,Y,Species
168,CHEMBL360227,CCN(CC)CCN1C(=O)[C@@](O)(c2ccccc2Cl)c2c1cc(C(N...,81.01,Canis lupus familiaris
1170,CHEMBL360227,CCN(CC)CCN1C(=O)[C@@](O)(c2ccccc2Cl)c2c1cc(C(N...,71.05,Homo sapiens
2294,CHEMBL360227,CCN(CC)CCN1C(=O)[C@@](O)(c2ccccc2Cl)c2c1cc(C(N...,78.79,Rattus norvegicus

CCN(CC)CCNC(=O)c1ccc(NS(C)(=O)=O)cc1

,Drug_ID,SMILES,Y,Species
19,CHEMBL95804,CCN(CC)CCNC(=O)c1ccc(NS(C)(=O)=O)cc1,10.09,Canis lupus familiaris
1533,CHEMBL95804,CCN(CC)CCNC(=O)c1ccc(NS(C)(=O)=O)cc1,15.10,Homo sapiens
2436,CHEMBL95804,CCN(CC)CCNC(=O)c1ccc(NS(C)(=O)=O)cc1,10.09,Rattus norvegicus

CCN(CC)S(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)cc1

,Drug_ID,SMILES,Y,Species
435,CHEMBL1778623,CCN(CC)S(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=...,98.78,Homo sapiens
2333,CHEMBL1778623,CCN(CC)S(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=...,98.21,Rattus norvegicus

CCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc1ccccc1

,Drug_ID,SMILES,Y,Species
249,CHEMBL1800656,CCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc1c...,89.70,Cavia porcellus
1889,CHEMBL1800656,CCN(CCNCCc1ccc(O)c2[nH]c(=O)sc12)C(=O)CCOCCc1c...,94.56,Homo sapiens

CCN(CCO)C(=O)c1cc2cccnc2n1-c1cccc(C(F)(F)F)c1

,Drug_ID,SMILES,Y,Species
899,CHEMBL2164567,CCN(CCO)C(=O)c1cc2cccnc2n1-c1cccc(C(F)(F)F)c1,90.72,Homo sapiens
2576,CHEMBL2164567,CCN(CCO)C(=O)c1cc2cccnc2n1-c1cccc(C(F)(F)F)c1,75.12,Rattus norvegicus

CCN(CCO)C(=O)c1cc2cccnn2c1-c1cccc(C(F)(F)F)c1

,Drug_ID,SMILES,Y,Species
1824,CHEMBL2164565,CCN(CCO)C(=O)c1cc2cccnn2c1-c1cccc(C(F)(F)F)c1,95.72,Homo sapiens
2707,CHEMBL2164565,CCN(CCO)C(=O)c1cc2cccnn2c1-c1cccc(C(F)(F)F)c1,91.28,Rattus norvegicus

CCN(CCO)C(=O)c1oc2cccnc2c1-c1cccc(C(F)(F)F)c1

,Drug_ID,SMILES,Y,Species
1124,CHEMBL2164566,CCN(CCO)C(=O)c1oc2cccnc2c1-c1cccc(C(F)(F)F)c1,91.28,Homo sapiens
2248,CHEMBL2164566,CCN(CCO)C(=O)c1oc2cccnc2c1-c1cccc(C(F)(F)F)c1,86.05,Rattus norvegicus

CCN(Cc1cc(C(F)(F)F)ccc1-c1cc(CC(=O)O)ccc1OC)C(=O)NCc1ccccc1

,Drug_ID,SMILES,Y,Species
103,CHEMBL2181753,CCN(Cc1cc(C(F)(F)F)ccc1-c1cc(CC(=O)O)ccc1OC)C(...,99.61,Canis lupus familiaris
284,CHEMBL2181753,CCN(Cc1cc(C(F)(F)F)ccc1-c1cc(CC(=O)O)ccc1OC)C(...,97.44,Cavia porcellus
554,CHEMBL2181753,CCN(Cc1cc(C(F)(F)F)ccc1-c1cc(CC(=O)O)ccc1OC)C(...,98.29,Homo sapiens
2528,CHEMBL2181753,CCN(Cc1cc(C(F)(F)F)ccc1-c1cc(CC(=O)O)ccc1OC)C(...,98.09,Rattus norvegicus

CCN1CCC[C@H]1CNC(=O)c1c(O)c(Cl)cc(Cl)c1OC

,Drug_ID,SMILES,Y,Species
599,CHEMBL8809,CCN1CCC[C@H]1CNC(=O)c1c(O)c(Cl)cc(Cl)c1OC,89.05,Homo sapiens
2329,CHEMBL8809,CCN1CCC[C@H]1CNC(=O)c1c(O)c(Cl)cc(Cl)c1OC,44.27,Rattus norvegicus

CCN1CCC[C@H]1CNC(=O)c1cc(Br)cc(OC)c1OC

,Drug_ID,SMILES,Y,Species
1371,CHEMBL289330,CCN1CCC[C@H]1CNC(=O)c1cc(Br)cc(OC)c1OC,45.98,Homo sapiens
2369,CHEMBL289330,CCN1CCC[C@H]1CNC(=O)c1cc(Br)cc(OC)c1OC,29.90,Rattus norvegicus

CCN1CCN(C(=O)N[C@@H](C(=O)N[C@@H]2C(=O)N3C(C(=O)O)=C(CSc4nnnn4C)CS[C@H]23)c2ccc(O)cc2)C(=O)C1=O

,Drug_ID,SMILES,Y,Species
42,CHEMBL507674,CCN1CCN(C(=O)N[C@@H](C(=O)N[C@@H]2C(=O)N3C(C(=...,32.37,Canis lupus familiaris
900,CHEMBL507674,CCN1CCN(C(=O)N[C@@H](C(=O)N[C@@H]2C(=O)N3C(C(=...,90.12,Homo sapiens
2661,CHEMBL507674,CCN1CCN(C(=O)N[C@@H](C(=O)N[C@@H]2C(=O)N3C(C(=...,69.12,Rattus norvegicus

CCNC(=O)C[C@@H]1N=C(c2ccc(Cl)cc2)c2cc(OC)ccc2-n2c(C)nnc21

,Drug_ID,SMILES,Y,Species
159,CHEMBL1232461,CCNC(=O)C[C@@H]1N=C(c2ccc(Cl)cc2)c2cc(OC)ccc2-...,67.63,Canis lupus familiaris
374,CHEMBL1232461,CCNC(=O)C[C@@H]1N=C(c2ccc(Cl)cc2)c2cc(OC)ccc2-...,75.97,Homo sapiens
2192,CHEMBL1232461,CCNC(=O)C[C@@H]1N=C(c2ccc(Cl)cc2)c2cc(OC)ccc2-...,68.63,Rattus norvegicus

CCNC(=O)Nc1nc2cc(-c3cccnc3)cc(-c3ncccc3F)c2[nH]1

,Drug_ID,SMILES,Y,Species
11,CHEMBL222333,CCNC(=O)Nc1nc2cc(-c3cccnc3)cc(-c3ncccc3F)c2[nH]1,96.00,Canis lupus familiaris
1297,CHEMBL222333,CCNC(=O)Nc1nc2cc(-c3cccnc3)cc(-c3ncccc3F)c2[nH]1,98.64,Homo sapiens
2798,CHEMBL222333,CCNC(=O)Nc1nc2cc(-c3cccnc3)cc(-c3ncccc3F)c2[nH]1,97.20,Rattus norvegicus

CCNC(=O)[C@H]1C[C@@](F)(c2ccc(CN3CCCC3)c(F)c2)C1

,Drug_ID,SMILES,Y,Species
89,CHEMBL2151197,CCNC(=O)[C@H]1C[C@@](F)(c2ccc(CN3CCCC3)c(F)c2)C1,19.35,Canis lupus familiaris
2424,CHEMBL2151197,CCNC(=O)[C@H]1C[C@@](F)(c2ccc(CN3CCCC3)c(F)c2)C1,22.79,Rattus norvegicus

CCNC(=O)[C@H]1O[C@@H](n2cnc3c(N)nc(NCCc4ccc(CCC(=O)O)cc4)nc32)[C@H](O)[C@@H]1O

,Drug_ID,SMILES,Y,Species
1789,CHEMBL331372,CCNC(=O)[C@H]1O[C@@H](n2cnc3c(N)nc(NCCc4ccc(CC...,57.99,Homo sapiens
2052,CHEMBL331372,CCNC(=O)[C@H]1O[C@@H](n2cnc3c(N)nc(NCCc4ccc(CC...,64.01,Mus musculus
2135,CHEMBL331372,CCNC(=O)[C@H]1O[C@@H](n2cnc3c(N)nc(NCCc4ccc(CC...,89.91,Rattus norvegicus

CCNC(=O)[C@H]1O[C@@H](n2cnc3c(NCC(c4ccccc4)c4ccccc4)nc(C(=O)NCCNC(=O)NC4CCN(c5ccccn5)CC4)nc32)[C@H](O)[C@@H]1O

,Drug_ID,SMILES,Y,Species
965,CHEMBL1096896,CCNC(=O)[C@H]1O[C@@H](n2cnc3c(NCC(c4ccccc4)c4c...,99.10,Homo sapiens
2782,CHEMBL1096896,CCNC(=O)[C@H]1O[C@@H](n2cnc3c(NCC(c4ccccc4)c4c...,98.58,Rattus norvegicus

CCNc1cc(C(=O)N[C@@H](Cc2ccccc2)[C@H](O)CNCc2cccc(C(F)(F)F)c2)c(F)c(N2CCCCS2(=O)=O)c1

,Drug_ID,SMILES,Y,Species
449,CHEMBL253641,CCNc1cc(C(=O)N[C@@H](Cc2ccccc2)[C@H](O)CNCc2cc...,98.81,Homo sapiens
2033,CHEMBL253641,CCNc1cc(C(=O)N[C@@H](Cc2ccccc2)[C@H](O)CNCc2cc...,98.40,Mus musculus

CCO/N=C/c1ccc(OCCC2CCN(c3ccc(C)nn3)CC2)cc1

,Drug_ID,SMILES,Y,Species
590,CHEMBL108922,CCO/N=C/c1ccc(OCCC2CCN(c3ccc(C)nn3)CC2)cc1,99.72,Homo sapiens
2134,CHEMBL108922,CCO/N=C/c1ccc(OCCC2CCN(c3ccc(C)nn3)CC2)cc1,99.66,Rattus norvegicus

CCOC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1cccc([N+](=O)[O-])c1

,Drug_ID,SMILES,Y,Species
144,CHEMBL475534,CCOC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1cccc([N+](=...,98.92,Canis lupus familiaris
969,CHEMBL475534,CCOC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1cccc([N+](=...,99.10,Homo sapiens
2275,CHEMBL475534,CCOC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1cccc([N+](=...,99.23,Rattus norvegicus

CCOC(=O)C1=C(C)NC(C)=C(C(C)=O)[C@H]1c1cccc2c(=O)cc(C)oc12

,Drug_ID,SMILES,Y,Species
883,CHEMBL2181926,CCOC(=O)C1=C(C)NC(C)=C(C(C)=O)[C@H]1c1cccc2c(=...,85.19,Homo sapiens
2020,CHEMBL2181926,CCOC(=O)C1=C(C)NC(C)=C(C(C)=O)[C@H]1c1cccc2c(=...,99.84,Mus musculus
2581,CHEMBL2181926,CCOC(=O)C1=C(C)NC(C)=C(C(C)=O)[C@H]1c1cccc2c(=...,99.92,Rattus norvegicus

CCOC(=O)Nc1ccc(NCc2ccc(F)cc2)cc1N

          Drug_ID                             SMILES      Y            Species
922   CHEMBL41355  CCOC(=O)Nc1ccc(NCc2ccc(F)cc2)cc1N  86.05       Homo sapiens
2395  CHEMBL41355  CCOC(=O)Nc1ccc(NCc2ccc(F)cc2)cc1N  79.92  Rattus norvegicus

CCOC(=O)Nc1ccc(NCc2ccc(F)cc2)nc1N

,Drug_ID,SMILES,Y,Species
1514,CHEMBL255044,CCOC(=O)Nc1ccc(NCc2ccc(F)cc2)nc1N,84.00,Homo sapiens
2681,CHEMBL255044,CCOC(=O)Nc1ccc(NCc2ccc(F)cc2)nc1N,78.01,Rattus norvegicus

CCOc1cc(CN2CCC(NC(=O)c3cncc(C)c3)CC2)cc(OCC)c1-c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
597,CHEMBL1210207,CCOc1cc(CN2CCC(NC(=O)c3cncc(C)c3)CC2)cc(OCC)c1...,98.51,Homo sapiens
1998,CHEMBL1210207,CCOc1cc(CN2CCC(NC(=O)c3cncc(C)c3)CC2)cc(OCC)c1...,98.61,Mus musculus
2740,CHEMBL1210207,CCOc1cc(CN2CCC(NC(=O)c3cncc(C)c3)CC2)cc(OCC)c1...,98.81,Rattus norvegicus

CCOc1cc(CN2CCC(Nc3nc4cc(S(N)(=O)=O)ccc4o3)CC2)cc(OCC)c1N

,Drug_ID,SMILES,Y,Species
1215,CHEMBL236788,CCOc1cc(CN2CCC(Nc3nc4cc(S(N)(=O)=O)ccc4o3)CC2)...,70.10,Homo sapiens
1988,CHEMBL236788,CCOc1cc(CN2CCC(Nc3nc4cc(S(N)(=O)=O)ccc4o3)CC2)...,90.72,Mus musculus
2632,CHEMBL236788,CCOc1cc(CN2CCC(Nc3nc4cc(S(N)(=O)=O)ccc4o3)CC2)...,89.05,Rattus norvegicus

CCOc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2)n[nH]1

,Drug_ID,SMILES,Y,Species
75,CHEMBL2151325,CCOc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2...,75.97,Canis lupus familiaris
1572,CHEMBL2151325,CCOc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2...,86.85,Homo sapiens
2667,CHEMBL2151325,CCOc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2...,83.04,Rattus norvegicus

CCOc1cc2c(c(F)c1OCC)C(=N)N(CC(=O)c1cc(N3CCOCC3)c(OC)c(C(C)(C)C)c1)C2

,Drug_ID,SMILES,Y,Species
1301,CHEMBL2103856,CCOc1cc2c(c(F)c1OCC)C(=N)N(CC(=O)c1cc(N3CCOCC3...,99.79,Homo sapiens
2038,CHEMBL2103856,CCOc1cc2c(c(F)c1OCC)C(=N)N(CC(=O)c1cc(N3CCOCC3...,99.75,Mus musculus

CCOc1cc2ncc(C(N)=O)c(Nc3cc(C)ccc3F)c2cc1N1CCN(C)CC1

,Drug_ID,SMILES,Y,Species
94,CHEMBL481212,CCOc1cc2ncc(C(N)=O)c(Nc3cc(C)ccc3F)c2cc1N1CCN(...,63.47,Canis lupus familiaris
1092,CHEMBL481212,CCOc1cc2ncc(C(N)=O)c(Nc3cc(C)ccc3F)c2cc1N1CCN(...,93.94,Homo sapiens
2290,CHEMBL481212,CCOc1cc2ncc(C(N)=O)c(Nc3cc(C)ccc3F)c2cc1N1CCN(...,89.27,Rattus norvegicus

CCOc1cc2ncc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(C)CC1

,Drug_ID,SMILES,Y,Species
9,CHEMBL521096,CCOc1cc2ncc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(...,81.71,Canis lupus familiaris
1571,CHEMBL521096,CCOc1cc2ncc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(...,94.32,Homo sapiens
2270,CHEMBL521096,CCOc1cc2ncc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(...,84.90,Rattus norvegicus

CCOc1cc2ncc(C(N)=O)c(Nc3cccc(Cl)c3F)c2cc1N1CCN(C)CC1

,Drug_ID,SMILES,Y,Species
163,CHEMBL520278,CCOc1cc2ncc(C(N)=O)c(Nc3cccc(Cl)c3F)c2cc1N1CCN...,79.55,Canis lupus familiaris
1051,CHEMBL520278,CCOc1cc2ncc(C(N)=O)c(Nc3cccc(Cl)c3F)c2cc1N1CCN...,92.95,Homo sapiens
2646,CHEMBL520278,CCOc1cc2ncc(C(N)=O)c(Nc3cccc(Cl)c3F)c2cc1N1CCN...,86.59,Rattus norvegicus

CCOc1cc2nnc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(C)CC1

,Drug_ID,SMILES,Y,Species
115,CHEMBL1683031,CCOc1cc2nnc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(...,93.80,Canis lupus familiaris
1648,CHEMBL1683031,CCOc1cc2nnc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(...,98.40,Homo sapiens
2504,CHEMBL1683031,CCOc1cc2nnc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(...,93.67,Rattus norvegicus

CCOc1ccc(-n2c([C@@H](C)N(Cc3cccnc3)C(=O)Cc3ccc(C(F)(F)F)cc3)nc3ccccc3c2=O)cc1

,Drug_ID,SMILES,Y,Species
398,CHEMBL436826,CCOc1ccc(-n2c([C@@H](C)N(Cc3cccnc3)C(=O)Cc3ccc...,99.53,Homo sapiens
2580,CHEMBL436826,CCOc1ccc(-n2c([C@@H](C)N(Cc3cccnc3)C(=O)Cc3ccc...,98.54,Rattus norvegicus

CCOc1ccc(-n2c([C@@H](C)N(Cc3cccnc3)C(=O)Cc3ccc(OC(F)(F)F)cc3)nc3ncccc3c2=O)cc1

,Drug_ID,SMILES,Y,Species
1863,CHEMBL397983,CCOc1ccc(-n2c([C@@H](C)N(Cc3cccnc3)C(=O)Cc3ccc...,95.23,Homo sapiens
2377,CHEMBL397983,CCOc1ccc(-n2c([C@@H](C)N(Cc3cccnc3)C(=O)Cc3ccc...,97.07,Rattus norvegicus

CCOc1ccc([C@@H](C)Nc2nc(N3CCN(C(C)=O)CC3)nc3c2CN(C(C)C)C3=O)cc1

,Drug_ID,SMILES,Y,Species
129,CHEMBL2011120,CCOc1ccc([C@@H](C)Nc2nc(N3CCN(C(C)=O)CC3)nc3c2...,56.86,Canis lupus familiaris
1412,CHEMBL2011120,CCOc1ccc([C@@H](C)Nc2nc(N3CCN(C(C)=O)CC3)nc3c2...,70.10,Homo sapiens
2013,CHEMBL2011120,CCOc1ccc([C@@H](C)Nc2nc(N3CCN(C(C)=O)CC3)nc3c2...,69.61,Mus musculus
2682,CHEMBL2011120,CCOc1ccc([C@@H](C)Nc2nc(N3CCN(C(C)=O)CC3)nc3c2...,78.41,Rattus norvegicus

CCOc1ccc([C@@H](C)Nc2nc(N3CCN(C(C)=O)CC3)nc3c2CN(C(C)C)C3=O)cc1F

,Drug_ID,SMILES,Y,Species
381,CHEMBL2011123,CCOc1ccc([C@@H](C)Nc2nc(N3CCN(C(C)=O)CC3)nc3c2...,66.61,Homo sapiens
2459,CHEMBL2011123,CCOc1ccc([C@@H](C)Nc2nc(N3CCN(C(C)=O)CC3)nc3c2...,74.25,Rattus norvegicus

CCOc1ncc(C)c2c1[C@H](c1ccc(C#N)cc1OC)C(C(N)=O)=C(C)N2

,Drug_ID,SMILES,Y,Species
425,CHEMBL2181927,CCOc1ncc(C)c2c1[C@H](c1ccc(C#N)cc1OC)C(C(N)=O)...,92.48,Homo sapiens
1974,CHEMBL2181927,CCOc1ncc(C)c2c1[C@H](c1ccc(C#N)cc1OC)C(C(N)=O)...,99.93,Mus musculus
2188,CHEMBL2181927,CCOc1ncc(C)c2c1[C@H](c1ccc(C#N)cc1OC)C(C(N)=O)...,99.93,Rattus norvegicus

CCOc1noc2cc(OCCC3CCN(c4ccc(C)nn4)CC3)ccc12

,Drug_ID,SMILES,Y,Species
27,CHEMBL2062774,CCOc1noc2cc(OCCC3CCN(c4ccc(C)nn4)CC3)ccc12,99.69,Canis lupus familiaris
1098,CHEMBL2062774,CCOc1noc2cc(OCCC3CCN(c4ccc(C)nn4)CC3)ccc12,99.86,Homo sapiens
2639,CHEMBL2062774,CCOc1noc2cc(OCCC3CCN(c4ccc(C)nn4)CC3)ccc12,99.85,Rattus norvegicus

CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c(C)c1

,Drug_ID,SMILES,Y,Species
204,CHEMBL1778639,CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c...,97.00,Canis lupus familiaris
276,CHEMBL1778639,CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c...,90.72,Cavia porcellus
1715,CHEMBL1778639,CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c...,95.72,Homo sapiens
2096,CHEMBL1778639,CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c...,79.17,Mus musculus
2732,CHEMBL1778639,CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c...,92.95,Rattus norvegicus

CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c(Cl)c1

,Drug_ID,SMILES,Y,Species
229,CHEMBL1778638,CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c...,97.76,Canis lupus familiaris
1709,CHEMBL1778638,CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c...,97.66,Homo sapiens
2464,CHEMBL1778638,CCS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c...,96.87,Rattus norvegicus

CCS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(Cl)c1

,Drug_ID,SMILES,Y,Species
145,CHEMBL1778646,CCS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(Cl)c1,99.18,Canis lupus familiaris
567,CHEMBL1778646,CCS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(Cl)c1,97.32,Homo sapiens

CCS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(F)c1

,Drug_ID,SMILES,Y,Species
151,CHEMBL1778644,CCS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(F)c1,99.16,Canis lupus familiaris
393,CHEMBL1778644,CCS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(F)c1,95.12,Homo sapiens
2753,CHEMBL1778644,CCS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(F)c1,94.32,Rattus norvegicus

CC[C@@H](Nc1c(Nc2cccc(C(=O)N(C)C)c2O)c(=O)c1=O)c1ccc(C)o1

,Drug_ID,SMILES,Y,Species
54,CHEMBL216981,CC[C@@H](Nc1c(Nc2cccc(C(=O)N(C)C)c2O)c(=O)c1=O...,91.10,Canis lupus familiaris
344,CHEMBL216981,CC[C@@H](Nc1c(Nc2cccc(C(=O)N(C)C)c2O)c(=O)c1=O...,98.21,Homo sapiens
2724,CHEMBL216981,CC[C@@H](Nc1c(Nc2cccc(C(=O)N(C)C)c2O)c(=O)c1=O...,98.94,Rattus norvegicus

CC[C@H](C)C(=O)O[C@H]1C[C@H](O)C=C2C=C[C@H](C)[C@H](CC[C@@H](O)C[C@@H](O)CC(=O)O)[C@H]21

,Drug_ID,SMILES,Y,Species
17,CHEMBL1144,CC[C@H](C)C(=O)O[C@H]1C[C@H](O)C=C2C=C[C@H](C)...,39.23,Canis lupus familiaris
2625,CHEMBL1144,CC[C@H](C)C(=O)O[C@H]1C[C@H](O)C=C2C=C[C@H](C)...,65.06,Rattus norvegicus

CC[C@H](CO)Nc1nc(SCc2ccccc2)nc2[nH]c(=O)sc12

,Drug_ID,SMILES,Y,Species
15,CHEMBL2349334,CC[C@H](CO)Nc1nc(SCc2ccccc2)nc2[nH]c(=O)sc12,99.47,Canis lupus familiaris
1069,CHEMBL2349334,CC[C@H](CO)Nc1nc(SCc2ccccc2)nc2[nH]c(=O)sc12,99.84,Homo sapiens

CC[C@H](N)C(=O)N[C@H](C#N)Cc1ccc(-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
988,CHEMBL212521,CC[C@H](N)C(=O)N[C@H](C#N)Cc1ccc(-c2ccccc2)cc1,91.99,Homo sapiens
2609,CHEMBL212521,CC[C@H](N)C(=O)N[C@H](C#N)Cc1ccc(-c2ccccc2)cc1,92.32,Rattus norvegicus

CCc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1ccccc1

,Drug_ID,SMILES,Y,Species
130,CHEMBL148674,CCc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1ccccc1,87.11,Canis lupus familiaris
1927,CHEMBL148674,CCc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1ccccc1,87.62,Homo sapiens
2018,CHEMBL148674,CCc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1ccccc1,78.01,Mus musculus
2331,CHEMBL148674,CCc1c(C(=O)C(N)=O)c2c(OCC(=O)O)cccc2n1Cc1ccccc1,92.32,Rattus norvegicus

CCc1c2c(nc3ccc(O)cc13)-c1cc3c(c(=O)n1C2)COC(=O)[C@]3(O)CC

,Drug_ID,SMILES,Y,Species
1065,CHEMBL837,CCc1c2c(nc3ccc(O)cc13)-c1cc3c(c(=O)n1C2)COC(=O...,92.32,Homo sapiens
2320,CHEMBL837,CCc1c2c(nc3ccc(O)cc13)-c1cc3c(c(=O)n1C2)COC(=O...,90.52,Rattus norvegicus

CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@H]3CCO)nc12

,Drug_ID,SMILES,Y,Species
1397,CHEMBL2103840,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@H]3C...,90.12,Homo sapiens
2336,CHEMBL2103840,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@H]3C...,82.39,Rattus norvegicus

CCc1nc(N)nc(N)c1-c1ccc(Cl)cc1

       Drug_ID                         SMILES      Y            Species
480   CHEMBL36  CCc1nc(N)nc(N)c1-c1ccc(Cl)cc1  92.64       Homo sapiens
2375  CHEMBL36  CCc1nc(N)nc(N)c1-c1ccc(Cl)cc1  93.10  Rattus norvegicus

CCc1nn(C2CCCC2)c2c1CCn1c(-c3cccs3)nnc1-2

,Drug_ID,SMILES,Y,Species
1452,CHEMBL217899,CCc1nn(C2CCCC2)c2c1CCn1c(-c3cccs3)nnc1-2,96.26,Homo sapiens
2744,CHEMBL217899,CCc1nn(C2CCCC2)c2c1CCn1c(-c3cccs3)nnc1-2,95.23,Rattus norvegicus

CCn1cc([C@]2(c3cccc(NC(=O)c4ccc(Cl)cn4)c3)N=C(N)c3c(F)cccc32)cc(C)c1=O

,Drug_ID,SMILES,Y,Species
373,CHEMBL2177305,CCn1cc([C@]2(c3cccc(NC(=O)c4ccc(Cl)cn4)c3)N=C(...,98.29,Homo sapiens
2098,CHEMBL2177305,CCn1cc([C@]2(c3cccc(NC(=O)c4ccc(Cl)cn4)c3)N=C(...,97.49,Mus musculus

CCn1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
1446,CHEMBL1934268,CCn1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=O)(=O...,98.37,Homo sapiens
2745,CHEMBL1934268,CCn1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=O)(=O...,95.23,Rattus norvegicus

CN(C(=O)Cc1ccc(-n2cnnn2)cc1)C1CCN(Cc2ccc(C(F)(F)F)cc2)CC1

,Drug_ID,SMILES,Y,Species
898,CHEMBL2010836,CN(C(=O)Cc1ccc(-n2cnnn2)cc1)C1CCN(Cc2ccc(C(F)(...,91.28,Homo sapiens
2675,CHEMBL2010836,CN(C(=O)Cc1ccc(-n2cnnn2)cc1)C1CCN(Cc2ccc(C(F)(...,93.94,Rattus norvegicus

CN(C(=O)Cc1ccc(S(C)(=O)=O)cc1)C1CCN(Cc2ccc(C(F)(F)F)cc2)CC1

,Drug_ID,SMILES,Y,Species
978,CHEMBL2010831,CN(C(=O)Cc1ccc(S(C)(=O)=O)cc1)C1CCN(Cc2ccc(C(F...,81.01,Homo sapiens
2168,CHEMBL2010831,CN(C(=O)Cc1ccc(S(C)(=O)=O)cc1)C1CCN(Cc2ccc(C(F...,84.00,Rattus norvegicus

CN(C)C(=O)C(CCN1CCC(O)(c2ccc(Cl)cc2)CC1)(c1ccccc1)c1ccccc1

,Drug_ID,SMILES,Y,Species
1901,CHEMBL841,CN(C)C(=O)C(CCN1CCC(O)(c2ccc(Cl)cc2)CC1)(c1ccc...,92.64,Homo sapiens
1986,CHEMBL841,CN(C)C(=O)C(CCN1CCC(O)(c2ccc(Cl)cc2)CC1)(c1ccc...,96.42,Mus musculus
2640,CHEMBL841,CN(C)C(=O)C(CCN1CCC(O)(c2ccc(Cl)cc2)CC1)(c1ccc...,94.56,Rattus norvegicus

CN(C)C(=O)[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cc2cc(Cl)ccc2[nH]1

,Drug_ID,SMILES,Y,Species
1469,CHEMBL319136,CN(C)C(=O)[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cc2c...,97.81,Homo sapiens
2526,CHEMBL319136,CN(C)C(=O)[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cc2c...,97.32,Rattus norvegicus

CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)OC(C)(C)C)CC3)c3ccccc3n2)CC1

,Drug_ID,SMILES,Y,Species
173,CHEMBL1818296,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,99.34,Canis lupus familiaris
1778,CHEMBL1818296,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,96.65,Homo sapiens
2093,CHEMBL1818296,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,99.21,Mus musculus
2129,CHEMBL1818296,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,96.00,Rattus norvegicus

CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)OC4CCOCC4)CC3)c3ccccc3n2)CC1

,Drug_ID,SMILES,Y,Species
1102,CHEMBL1818302,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,82.05,Homo sapiens
2127,CHEMBL1818302,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,73.81,Rattus norvegicus

CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)OCC(C)(C)C)CC3)c3ccccc3n2)CC1

,Drug_ID,SMILES,Y,Species
1791,CHEMBL1818303,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,98.61,Homo sapiens
2109,CHEMBL1818303,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,99.61,Mus musculus
2612,CHEMBL1818303,CN(C)CCC1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,98.67,Rattus norvegicus

CN(C)CCC=C1c2ccccc2C=Cc2ccccc21

        Drug_ID                           SMILES      Y            Species
1718  CHEMBL669  CN(C)CCC=C1c2ccccc2C=Cc2ccccc21  92.16       Homo sapiens
2630  CHEMBL669  CN(C)CCC=C1c2ccccc2C=Cc2ccccc21  88.35  Rattus norvegicus

CN(C)CCC=C1c2ccccc2COc2ccccc21

            Drug_ID                          SMILES      Y            Species
1189  CHEMBL1628227  CN(C)CCC=C1c2ccccc2COc2ccccc21  76.39       Homo sapiens
2824  CHEMBL1628227  CN(C)CCC=C1c2ccccc2COc2ccccc21  79.55  Rattus norvegicus

CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21

,Drug_ID,SMILES,Y,Species
119,CHEMBL549,CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,59.66,Canis lupus familiaris
258,CHEMBL549,CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,37.06,Cavia porcellus
1904,CHEMBL549,CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,59.66,Homo sapiens
2061,CHEMBL549,CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,48.85,Mus musculus
2384,CHEMBL549,CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,56.30,Rattus norvegicus

CN(C)CCCN1c2ccccc2CCc2ccccc21

       Drug_ID                         SMILES      Y                 Species
40    CHEMBL11  CN(C)CCCN1c2ccccc2CCc2ccccc21  95.63  Canis lupus familiaris
824   CHEMBL11  CN(C)CCCN1c2ccccc2CCc2ccccc21  87.87            Homo sapiens
2115  CHEMBL11  CN(C)CCCN1c2ccccc2CCc2ccccc21  82.72       Rattus norvegicus

CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc21

       Drug_ID                            SMILES      Y            Species
1878  CHEMBL71  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc21  98.64       Homo sapiens
2334  CHEMBL71  CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc21  98.29  Rattus norvegicus

CN(C)CCN1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)OC(C)(C)C)CC3)c3ccccc3n2)CC1

,Drug_ID,SMILES,Y,Species
224,CHEMBL1818294,CN(C)CCN1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,97.07,Canis lupus familiaris
508,CHEMBL1818294,CN(C)CCN1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,93.94,Homo sapiens
2266,CHEMBL1818294,CN(C)CCN1CCN(c2cc(C(=O)NC[C@H]3CC[C@H](CNC(=O)...,94.32,Rattus norvegicus

CN(C)CCOc1cc(NS(=O)(=O)c2c(Cl)cc(C(F)(F)F)cc2Cl)ccc1Cl

,Drug_ID,SMILES,Y,Species
733,CHEMBL1164033,CN(C)CCOc1cc(NS(=O)(=O)c2c(Cl)cc(C(F)(F)F)cc2C...,99.71,Homo sapiens
2482,CHEMBL1164033,CN(C)CCOc1cc(NS(=O)(=O)c2c(Cl)cc(C(F)(F)F)cc2C...,99.76,Rattus norvegicus

CN(C)N(C)C(=O)[C@@]1(Cc2ccccc2)CCCN(C(=O)[C@@H](Cc2c[nH]c3ccccc23)NC(=O)C(C)(C)N)C1

,Drug_ID,SMILES,Y,Species
207,CHEMBL2110579,CN(C)N(C)C(=O)[C@@]1(Cc2ccccc2)CCCN(C(=O)[C@@H...,93.67,Canis lupus familiaris
303,CHEMBL2110579,CN(C)N(C)C(=O)[C@@]1(Cc2ccccc2)CCCN(C(=O)[C@@H...,78.01,Cavia porcellus
2253,CHEMBL2110579,CN(C)N(C)C(=O)[C@@]1(Cc2ccccc2)CCCN(C(=O)[C@@H...,84.00,Rattus norvegicus

CN(C)S(=O)(=O)NC(=O)CCCc1c(-c2ccc(F)cc2)[nH]c2ccc(C#N)cc12

,Drug_ID,SMILES,Y,Species
90,CHEMBL403313,CN(C)S(=O)(=O)NC(=O)CCCc1c(-c2ccc(F)cc2)[nH]c2...,98.04,Canis lupus familiaris
948,CHEMBL403313,CN(C)S(=O)(=O)NC(=O)CCCc1c(-c2ccc(F)cc2)[nH]c2...,99.59,Homo sapiens
2280,CHEMBL403313,CN(C)S(=O)(=O)NC(=O)CCCc1c(-c2ccc(F)cc2)[nH]c2...,99.58,Rattus norvegicus

CN(C)c1nc(Cc2ccc(NC(=O)c3ccc(C(F)(F)F)cc3)cc2)nc(N(C)C)c1CC(=O)O

,Drug_ID,SMILES,Y,Species
274,CHEMBL551813,CN(C)c1nc(Cc2ccc(NC(=O)c3ccc(C(F)(F)F)cc3)cc2)...,95.63,Cavia porcellus
945,CHEMBL551813,CN(C)c1nc(Cc2ccc(NC(=O)c3ccc(C(F)(F)F)cc3)cc2)...,99.61,Homo sapiens
2637,CHEMBL551813,CN(C)c1nc(Cc2ccc(NC(=O)c3ccc(C(F)(F)F)cc3)cc2)...,99.75,Rattus norvegicus

CN(CC(=O)NC1CC1)C(=O)c1ccc2c(c1)c1c(n2C)CCC(C2CCOCC2)C1

,Drug_ID,SMILES,Y,Species
1252,CHEMBL2029721,CN(CC(=O)NC1CC1)C(=O)c1ccc2c(c1)c1c(n2C)CCC(C2...,96.72,Homo sapiens
2778,CHEMBL2029721,CN(CC(=O)NC1CC1)C(=O)c1ccc2c(c1)c1c(n2C)CCC(C2...,97.81,Rattus norvegicus

CN(CCCOCCOCCc1ccccc1)CCc1ccc(O)c2nc(O)sc12

,Drug_ID,SMILES,Y,Species
774,CHEMBL110999,CN(CCCOCCOCCc1ccccc1)CCc1ccc(O)c2nc(O)sc12,90.12,Homo sapiens
2335,CHEMBL110999,CN(CCCOCCOCCc1ccccc1)CCc1ccc(O)c2nc(O)sc12,75.97,Rattus norvegicus

CN(CCNCCc1ccc(O)c2nc(O)sc12)C(=O)CCOCCc1ccccc1

,Drug_ID,SMILES,Y,Species
252,CHEMBL323776,CN(CCNCCc1ccc(O)c2nc(O)sc12)C(=O)CCOCCc1ccccc1,72.45,Cavia porcellus
769,CHEMBL323776,CN(CCNCCc1ccc(O)c2nc(O)sc12)C(=O)CCOCCc1ccccc1,89.27,Homo sapiens
2217,CHEMBL323776,CN(CCNCCc1ccc(O)c2nc(O)sc12)C(=O)CCOCCc1ccccc1,79.17,Rattus norvegicus

CN(CCOc1ccc(NS(C)(=O)=O)cc1)CCc1ccc(NS(C)(=O)=O)cc1

,Drug_ID,SMILES,Y,Species
184,CHEMBL473,CN(CCOc1ccc(NS(C)(=O)=O)cc1)CCc1ccc(NS(C)(=O)=...,69.61,Canis lupus familiaris
250,CHEMBL473,CN(CCOc1ccc(NS(C)(=O)=O)cc1)CCc1ccc(NS(C)(=O)=...,51.15,Cavia porcellus
536,CHEMBL473,CN(CCOc1ccc(NS(C)(=O)=O)cc1)CCc1ccc(NS(C)(=O)=...,66.10,Homo sapiens

CN(Cc1cccc2ccccc12)c1cc(N2CCOCC2)nc(=O)[nH]1

,Drug_ID,SMILES,Y,Species
486,CHEMBL2165177,CN(Cc1cccc2ccccc12)c1cc(N2CCOCC2)nc(=O)[nH]1,94.32,Homo sapiens
2600,CHEMBL2165177,CN(Cc1cccc2ccccc12)c1cc(N2CCOCC2)nc(=O)[nH]1,99.36,Rattus norvegicus

CN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)C(C)(O)C(F)(F)F)cc1

,Drug_ID,SMILES,Y,Species
1615,CHEMBL140684,CN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)C(C)(O)C(F)(F...,97.71,Homo sapiens
2516,CHEMBL140684,CN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)C(C)(O)C(F)(F...,97.60,Rattus norvegicus

CN1C(=N)N[C@](C)(c2cc(-c3cccc(C#N)c3)cs2)CC1=O

,Drug_ID,SMILES,Y,Species
989,CHEMBL2151138,CN1C(=N)N[C@](C)(c2cc(-c3cccc(C#N)c3)cs2)CC1=O,91.64,Homo sapiens
1978,CHEMBL2151138,CN1C(=N)N[C@](C)(c2cc(-c3cccc(C#N)c3)cs2)CC1=O,75.12,Mus musculus

CN1C(=O)CN=C(c2ccccc2)c2cc(Cl)ccc21

       Drug_ID                               SMILES      Y            Species
670   CHEMBL12  CN1C(=O)CN=C(c2ccccc2)c2cc(Cl)ccc21  98.61       Homo sapiens
2133  CHEMBL12  CN1C(=O)CN=C(c2ccccc2)c2cc(Cl)ccc21  87.62  Rattus norvegicus

CN1CC(n2nccc2-c2cc(Cl)ccc2Oc2cc(F)c(S(=O)(=O)Nc3ncns3)cc2F)C1

,Drug_ID,SMILES,Y,Species
674,CHEMBL2325622,CN1CC(n2nccc2-c2cc(Cl)ccc2Oc2cc(F)c(S(=O)(=O)N...,98.40,Homo sapiens
2014,CHEMBL2325622,CN1CC(n2nccc2-c2cc(Cl)ccc2Oc2cc(F)c(S(=O)(=O)N...,95.82,Mus musculus
2354,CHEMBL2325622,CN1CC(n2nccc2-c2cc(Cl)ccc2Oc2cc(F)c(S(=O)(=O)N...,96.50,Rattus norvegicus

CN1CCC[C@@H]1Cc1c[nH]c2ccc(Nc3ncccc3[N+](=O)[O-])cc12

,Drug_ID,SMILES,Y,Species
828,CHEMBL83597,CN1CCC[C@@H]1Cc1c[nH]c2ccc(Nc3ncccc3[N+](=O)[O...,86.32,Homo sapiens
2622,CHEMBL83597,CN1CCC[C@@H]1Cc1c[nH]c2ccc(Nc3ncccc3[N+](=O)[O...,61.31,Rattus norvegicus

CN1CCN(C2=Nc3cc(Cl)ccc3Nc3ccccc32)CC1

,Drug_ID,SMILES,Y,Species
96,CHEMBL42,CN1CCN(C2=Nc3cc(Cl)ccc3Nc3ccccc32)CC1,92.64,Canis lupus familiaris
291,CHEMBL42,CN1CCN(C2=Nc3cc(Cl)ccc3Nc3ccccc32)CC1,91.28,Cavia porcellus
476,CHEMBL42,CN1CCN(C2=Nc3cc(Cl)ccc3Nc3ccccc32)CC1,94.79,Homo sapiens
2490,CHEMBL42,CN1CCN(C2=Nc3cc(Cl)ccc3Nc3ccccc32)CC1,93.53,Rattus norvegicus

CN1CCN(CCCN2c3ccccc3Sc3ccc(C(F)(F)F)cc32)CC1

,Drug_ID,SMILES,Y,Species
679,CHEMBL422,CN1CCN(CCCN2c3ccccc3Sc3ccc(C(F)(F)F)cc32)CC1,99.19,Homo sapiens
2399,CHEMBL422,CN1CCN(CCCN2c3ccccc3Sc3ccc(C(F)(F)F)cc32)CC1,99.30,Rattus norvegicus

CN1CCN(S(=O)(=O)c2ccc(-c3cnc(N)c(C(=O)Nc4cnccc4CN4CCCC4)n3)cc2)CC1

,Drug_ID,SMILES,Y,Species
1683,CHEMBL2177173,CN1CCN(S(=O)(=O)c2ccc(-c3cnc(N)c(C(=O)Nc4cnccc...,92.16,Homo sapiens
2210,CHEMBL2177173,CN1CCN(S(=O)(=O)c2ccc(-c3cnc(N)c(C(=O)Nc4cnccc...,90.12,Rattus norvegicus

CN1CC[C@]23c4c5ccc(O)c4O[C@H]2[C@@H](O)C=C[C@H]3[C@H]1C5

,Drug_ID,SMILES,Y,Species
503,CHEMBL70,CN1CC[C@]23c4c5ccc(O)c4O[C@H]2[C@@H](O)C=C[C@H...,20.83,Homo sapiens
2509,CHEMBL70,CN1CC[C@]23c4c5ccc(O)c4O[C@H]2[C@@H](O)C=C[C@H...,17.28,Rattus norvegicus

CN1CCc2cc(Cl)c(O)cc2[C@@H](c2ccccc2)C1

,Drug_ID,SMILES,Y,Species
1689,CHEMBL62,CN1CCc2cc(Cl)c(O)cc2[C@@H](c2ccccc2)C1,91.99,Homo sapiens
2169,CHEMBL62,CN1CCc2cc(Cl)c(O)cc2[C@@H](c2ccccc2)C1,83.04,Rattus norvegicus

CNC(=O)CCCN(C)C(=O)c1ccc2c(c1)c1c(n2C)CC[C@@H](C2CCOCC2)C1

,Drug_ID,SMILES,Y,Species
80,CHEMBL2029729,CNC(=O)CCCN(C)C(=O)c1ccc2c(c1)c1c(n2C)CC[C@@H]...,74.25,Canis lupus familiaris
294,CHEMBL2029729,CNC(=O)CCCN(C)C(=O)c1ccc2c(c1)c1c(n2C)CC[C@@H]...,67.12,Cavia porcellus
1448,CHEMBL2029729,CNC(=O)CCCN(C)C(=O)c1ccc2c(c1)c1c(n2C)CC[C@@H]...,96.34,Homo sapiens
2746,CHEMBL2029729,CNC(=O)CCCN(C)C(=O)c1ccc2c(c1)c1c(n2C)CC[C@@H]...,98.54,Rattus norvegicus

CNC(=O)c1ccc(C)c(-n2c(C)cc(OCc3ccc(F)cc3F)c(Br)c2=O)c1

,Drug_ID,SMILES,Y,Species
436,CHEMBL1088751,CNC(=O)c1ccc(C)c(-n2c(C)cc(OCc3ccc(F)cc3F)c(Br...,93.53,Homo sapiens
2529,CHEMBL1088751,CNC(=O)c1ccc(C)c(-n2c(C)cc(OCc3ccc(F)cc3F)c(Br...,98.17,Rattus norvegicus

CNC1(c2ccccc2Cl)CCCCC1=O

        Drug_ID                    SMILES      Y            Species
1507  CHEMBL742  CNC1(c2ccccc2Cl)CCCCC1=O  42.01       Homo sapiens
2647  CHEMBL742  CNC1(c2ccccc2Cl)CCCCC1=O  44.84  Rattus norvegicus

CNCCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1

       Drug_ID                              SMILES      Y            Species
781   CHEMBL41  CNCCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1  95.72       Homo sapiens
2396  CHEMBL41  CNCCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1  94.79  Rattus norvegicus

CNCCCC12CCC(c3ccccc31)c1ccccc12

          Drug_ID                           SMILES      Y            Species
1116  CHEMBL21731  CNCCCC12CCC(c3ccccc31)c1ccccc12  87.37       Homo sapiens
2607  CHEMBL21731  CNCCCC12CCC(c3ccccc31)c1ccccc12  92.16  Rattus norvegicus

CNCCCN1c2ccccc2CCc2ccccc21

       Drug_ID                      SMILES      Y                 Species
106   CHEMBL72  CNCCCN1c2ccccc2CCc2ccccc21  95.33  Canis lupus familiaris
1309  CHEMBL72  CNCCCN1c2ccccc2CCc2ccccc21  85.19            Homo sapiens
2199  CHEMBL72  CNCCCN1c2ccccc2CCc2ccccc21  81.01       Rattus norvegicus

CN[C@H]1CC[C@@H](c2ccc(Cl)c(Cl)c2)c2ccccc21

,Drug_ID,SMILES,Y,Species
1587,CHEMBL809,CN[C@H]1CC[C@@H](c2ccc(Cl)c(Cl)c2)c2ccccc21,98.54,Homo sapiens
2749,CHEMBL809,CN[C@H]1CC[C@@H](c2ccc(Cl)c(Cl)c2)c2ccccc21,98.00,Rattus norvegicus

CNc1cc2[nH]c(=O)n(-c3ccc(NC(=O)NS(=O)(=O)c4ccc(Cl)s4)cc3)c(=O)c2cc1F

,Drug_ID,SMILES,Y,Species
195,CHEMBL2103828,CNc1cc2[nH]c(=O)n(-c3ccc(NC(=O)NS(=O)(=O)c4ccc...,99.31,Canis lupus familiaris
801,CHEMBL2103828,CNc1cc2[nH]c(=O)n(-c3ccc(NC(=O)NS(=O)(=O)c4ccc...,99.58,Homo sapiens

CNc1ccc(-c2nc3ccc(O)cc3s2)cc1

          Drug_ID                         SMILES      Y            Species
1168  CHEMBL93124  CNc1ccc(-c2nc3ccc(O)cc3s2)cc1  98.89       Homo sapiens
2206  CHEMBL93124  CNc1ccc(-c2nc3ccc(O)cc3s2)cc1  98.17  Rattus norvegicus

COC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1ccccc1[N+](=O)[O-]

,Drug_ID,SMILES,Y,Species
116,CHEMBL193,COC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1ccccc1[N+](=...,92.64,Canis lupus familiaris
1938,CHEMBL193,COC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1ccccc1[N+](=...,96.17,Homo sapiens
2469,CHEMBL193,COC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1ccccc1[N+](=...,99.77,Rattus norvegicus

COC(=O)C1=C(C)NC(C)=C(C(=O)OCCN(C)Cc2ccccc2)C1c1cccc([N+](=O)[O-])c1

,Drug_ID,SMILES,Y,Species
33,CHEMBL1484,COC(=O)C1=C(C)NC(C)=C(C(=O)OCCN(C)Cc2ccccc2)C1...,99.60,Canis lupus familiaris
2714,CHEMBL1484,COC(=O)C1=C(C)NC(C)=C(C(=O)OCCN(C)Cc2ccccc2)C1...,99.61,Rattus norvegicus

COC(=O)N[C@@H](C)C#Cc1cnc(Oc2ccc(OC(C)C)cc2)s1

,Drug_ID,SMILES,Y,Species
403,CHEMBL378997,COC(=O)N[C@@H](C)C#Cc1cnc(Oc2ccc(OC(C)C)cc2)s1,99.66,Homo sapiens
2107,CHEMBL378997,COC(=O)N[C@@H](C)C#Cc1cnc(Oc2ccc(OC(C)C)cc2)s1,99.01,Mus musculus
2402,CHEMBL378997,COC(=O)N[C@@H](C)C#Cc1cnc(Oc2ccc(OC(C)C)cc2)s1,99.49,Rattus norvegicus

COCC#Cc1cccc(C2(c3ccc(OC(F)F)cc3)N=C(N)N3CC(F)(F)CN=C32)c1

,Drug_ID,SMILES,Y,Species
430,CHEMBL1957480,COCC#Cc1cccc(C2(c3ccc(OC(F)F)cc3)N=C(N)N3CC(F)...,98.89,Homo sapiens
2051,CHEMBL1957480,COCC#Cc1cccc(C2(c3ccc(OC(F)F)cc3)N=C(N)N3CC(F)...,98.70,Mus musculus

COCC(C)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
1227,CHEMBL1934416,COCC(C)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=...,91.64,Homo sapiens
2245,CHEMBL1934416,COCC(C)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=...,86.05,Rattus norvegicus

COCC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)/C(=N\OC)c3csc(N)n3)[C@H]2SC1

,Drug_ID,SMILES,Y,Species
1395,CHEMBL1672,COCC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)/C(=N\OC)c3...,53.45,Homo sapiens
2416,CHEMBL1672,COCC1=C(C(=O)O)N2C(=O)[C@@H](NC(=O)/C(=N\OC)c3...,54.59,Rattus norvegicus

COCCC#Cc1cccc(C2(c3ccc(OC(F)F)cc3)N=C(N)N3CC(F)(F)CN=C32)c1

,Drug_ID,SMILES,Y,Species
1359,CHEMBL1957481,COCCC#Cc1cccc(C2(c3ccc(OC(F)F)cc3)N=C(N)N3CC(F...,97.71,Homo sapiens
2003,CHEMBL1957481,COCCC#Cc1cccc(C2(c3ccc(OC(F)F)cc3)N=C(N)N3CC(F...,97.38,Mus musculus

COCCC(=O)N[C@H](C)c1ccc(Nc2ncc3cc(-c4ccncc4)ccc3n2)cc1

,Drug_ID,SMILES,Y,Species
74,CHEMBL2335893,COCCC(=O)N[C@H](C)c1ccc(Nc2ncc3cc(-c4ccncc4)cc...,95.12,Canis lupus familiaris
340,CHEMBL2335893,COCCC(=O)N[C@H](C)c1ccc(Nc2ncc3cc(-c4ccncc4)cc...,98.17,Homo sapiens
2240,CHEMBL2335893,COCCC(=O)N[C@H](C)c1ccc(Nc2ncc3cc(-c4ccncc4)cc...,95.53,Rattus norvegicus

COCCC(C)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(=O)(=O)c1ccc(C)cc1

,Drug_ID,SMILES,Y,Species
1134,CHEMBL1934417,COCCC(C)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(...,89.91,Homo sapiens
2269,CHEMBL1934417,COCCC(C)n1nc(C)c(C(=O)N[C@@H](C)C(C)(C)C)c1NS(...,72.45,Rattus norvegicus

COCCCCC(=NOCCN)c1ccc(C(F)(F)F)cc1

,Drug_ID,SMILES,Y,Species
1352,CHEMBL1621884,COCCCCC(=NOCCN)c1ccc(C(F)(F)F)cc1,73.36,Homo sapiens
2283,CHEMBL1621884,COCCCCC(=NOCCN)c1ccc(C(F)(F)F)cc1,77.62,Rattus norvegicus

COCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1

,Drug_ID,SMILES,Y,Species
311,CHEMBL2313227,COCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,42.01,Cavia porcellus
592,CHEMBL2313227,COCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,91.28,Homo sapiens
2696,CHEMBL2313227,COCCN(c1cccnc1)P(=O)(c1ccccc1)c1ccccc1,62.40,Rattus norvegicus

COCCNCC(=O)NC12CC3CC(CC(C3)C1)C2

,Drug_ID,SMILES,Y,Species
457,CHEMBL1354035,COCCNCC(=O)NC12CC3CC(CC(C3)C1)C2,50.00,Homo sapiens
2443,CHEMBL1354035,COCCNCC(=O)NC12CC3CC(CC(C3)C1)C2,51.73,Rattus norvegicus

COCCOC(=O)C1=C(C)NC(C)=C(C(=O)OC(C)C)C1c1cccc([N+](=O)[O-])c1

,Drug_ID,SMILES,Y,Species
112,CHEMBL1428,COCCOC(=O)C1=C(C)NC(C)=C(C(=O)OC(C)C)C1c1cccc(...,98.84,Canis lupus familiaris
873,CHEMBL1428,COCCOC(=O)C1=C(C)NC(C)=C(C(=O)OC(C)C)C1c1cccc(...,98.17,Homo sapiens
2501,CHEMBL1428,COCCOC(=O)C1=C(C)NC(C)=C(C(=O)OC(C)C)C1c1cccc(...,98.25,Rattus norvegicus

COCCOc1nc(N)c2[nH]c(=O)n(Cc3ccccc3)c2n1

,Drug_ID,SMILES,Y,Species
1666,CHEMBL210884,COCCOc1nc(N)c2[nH]c(=O)n(Cc3ccccc3)c2n1,89.49,Homo sapiens
2244,CHEMBL210884,COCCOc1nc(N)c2[nH]c(=O)n(Cc3ccccc3)c2n1,62.40,Rattus norvegicus

COC[C@@H](O)Cn1c(=O)cnn(-c2ccc(Cl)c(C(=O)NCC3(O)CCCCCC3)c2)c1=O

,Drug_ID,SMILES,Y,Species
535,CHEMBL1779512,COC[C@@H](O)Cn1c(=O)cnn(-c2ccc(Cl)c(C(=O)NCC3(...,41.45,Homo sapiens
2181,CHEMBL1779512,COC[C@@H](O)Cn1c(=O)cnn(-c2ccc(Cl)c(C(=O)NCC3(...,39.23,Rattus norvegicus

COC[C@H](O)Cn1c(=O)cnn(-c2ccc(Cl)c(C(=O)NCC3(O)CCCCCC3)c2)c1=O

,Drug_ID,SMILES,Y,Species
82,CHEMBL1823817,COC[C@H](O)Cn1c(=O)cnn(-c2ccc(Cl)c(C(=O)NCC3(O...,44.84,Canis lupus familiaris
1378,CHEMBL1823817,COC[C@H](O)Cn1c(=O)cnn(-c2ccc(Cl)c(C(=O)NCC3(O...,58.55,Homo sapiens
2670,CHEMBL1823817,COC[C@H](O)Cn1c(=O)cnn(-c2ccc(Cl)c(C(=O)NCC3(O...,52.30,Rattus norvegicus

COCc1c(C(C)C)nc(C(C)C)c(/C=C/[C@@H](O)C[C@@H](O)CC(=O)O)c1-c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
1870,CHEMBL1477,COCc1c(C(C)C)nc(C(C)C)c(/C=C/[C@@H](O)C[C@@H](...,99.01,Homo sapiens
2754,CHEMBL1477,COCc1c(C(C)C)nc(C(C)C)c(/C=C/[C@@H](O)C[C@@H](...,94.90,Rattus norvegicus

CON(C)C(=O)c1c(Cn2c(C)nc(Cl)c2Cl)sc2c1c(=O)n(C)c(=O)n2CC(C)C

,Drug_ID,SMILES,Y,Species
99,CHEMBL387125,CON(C)C(=O)c1c(Cn2c(C)nc(Cl)c2Cl)sc2c1c(=O)n(C...,67.12,Canis lupus familiaris
1912,CHEMBL387125,CON(C)C(=O)c1c(Cn2c(C)nc(Cl)c2Cl)sc2c1c(=O)n(C...,64.01,Homo sapiens

CO[C@H]1CC[C@]2(CC1)Cc1ccc(-c3cncc(Br)c3)cc1C21N=C(C)C(N)=N1

,Drug_ID,SMILES,Y,Species
1676,CHEMBL2152918,CO[C@H]1CC[C@]2(CC1)Cc1ccc(-c3cncc(Br)c3)cc1C2...,86.05,Homo sapiens
2056,CHEMBL2152918,CO[C@H]1CC[C@]2(CC1)Cc1ccc(-c3cncc(Br)c3)cc1C2...,97.91,Mus musculus
2295,CHEMBL2152918,CO[C@H]1CC[C@]2(CC1)Cc1ccc(-c3cncc(Br)c3)cc1C2...,93.39,Rattus norvegicus

CO[C@H]1CC[C@]2(CC1)Cc1ccc(OCC(C)C)cc1C21N=C(C)C(N)=N1

,Drug_ID,SMILES,Y,Species
1420,CHEMBL2152917,CO[C@H]1CC[C@]2(CC1)Cc1ccc(OCC(C)C)cc1C21N=C(C...,79.92,Homo sapiens
2036,CHEMBL2152917,CO[C@H]1CC[C@]2(CC1)Cc1ccc(OCC(C)C)cc1C21N=C(C...,65.06,Mus musculus

CO[C@H]1CN(CCn2c(=O)ccc3ccc(C#N)cc32)CC[C@H]1NCc1cc2c(cn1)OCCO2

,Drug_ID,SMILES,Y,Species
13,CHEMBL2165054,CO[C@H]1CN(CCn2c(=O)ccc3ccc(C#N)cc32)CC[C@H]1N...,43.14,Canis lupus familiaris
467,CHEMBL2165054,CO[C@H]1CN(CCn2c(=O)ccc3ccc(C#N)cc32)CC[C@H]1N...,51.73,Homo sapiens
2650,CHEMBL2165054,CO[C@H]1CN(CCn2c(=O)ccc3ccc(C#N)cc32)CC[C@H]1N...,26.19,Rattus norvegicus

COc1c(C)cc(C2(c3cccc(-c4cncnc4)c3)N=C(C)C(N)=N2)cc1C

,Drug_ID,SMILES,Y,Species
1770,CHEMBL2180028,COc1c(C)cc(C2(c3cccc(-c4cncnc4)c3)N=C(C)C(N)=N...,95.63,Homo sapiens
2069,CHEMBL2180028,COc1c(C)cc(C2(c3cccc(-c4cncnc4)c3)N=C(C)C(N)=N...,84.00,Mus musculus

COc1c(C)cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)cccc32)nc1C

,Drug_ID,SMILES,Y,Species
1097,CHEMBL2177917,COc1c(C)cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)...,96.57,Homo sapiens
2008,CHEMBL2177917,COc1c(C)cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)...,90.32,Mus musculus

COc1c(N2C[C@@H]3CCCN[C@@H]3C2)c(F)cc2c(=O)c(C(=O)O)cn(C3CC3)c12

,Drug_ID,SMILES,Y,Species
299,CHEMBL32,COc1c(N2C[C@@H]3CCCN[C@@H]3C2)c(F)cc2c(=O)c(C(...,23.19,Cavia porcellus
501,CHEMBL32,COc1c(N2C[C@@H]3CCCN[C@@H]3C2)c(F)cc2c(=O)c(C(...,30.88,Homo sapiens
2775,CHEMBL32,COc1c(N2C[C@@H]3CCCN[C@@H]3C2)c(F)cc2c(=O)c(C(...,34.42,Rattus norvegicus

COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OCCN1CCCC1

,Drug_ID,SMILES,Y,Species
1418,CHEMBL214957,COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OCC...,98.61,Homo sapiens
2140,CHEMBL214957,COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OCC...,99.01,Rattus norvegicus

COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OC[C@H](O)C1CC1

,Drug_ID,SMILES,Y,Species
137,CHEMBL2147474,COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OC[...,99.86,Canis lupus familiaris
896,CHEMBL2147474,COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OC[...,99.79,Homo sapiens
2065,CHEMBL2147474,COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OC[...,99.82,Mus musculus
2361,CHEMBL2147474,COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OC[...,98.81,Rattus norvegicus

COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OC[C@H](OP(=O)(O)O)C1CC1

,Drug_ID,SMILES,Y,Species
200,CHEMBL2147475,COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OC[...,99.16,Canis lupus familiaris
1748,CHEMBL2147475,COc1cc(-n2cnc3cc(-c4ccc(Cl)cc4)sc3c2=O)ccc1OC[...,99.39,Homo sapiens

COc1cc(C(C)C)c(Oc2cnc(N)nc2N)cc1I

,Drug_ID,SMILES,Y,Species
729,CHEMBL526307,COc1cc(C(C)C)c(Oc2cnc(N)nc2N)cc1I,95.33,Homo sapiens
2358,CHEMBL526307,COc1cc(C(C)C)c(Oc2cnc(N)nc2N)cc1I,96.17,Rattus norvegicus

COc1cc(C(C)C)c(Oc2cnc(NC(CO)CO)nc2N)cc1I

,Drug_ID,SMILES,Y,Species
2064,CHEMBL494161,COc1cc(C(C)C)c(Oc2cnc(NC(CO)CO)nc2N)cc1I,94.19,Mus musculus
2663,CHEMBL494161,COc1cc(C(C)C)c(Oc2cnc(NC(CO)CO)nc2N)cc1I,97.20,Rattus norvegicus

COc1cc(C)c(S(=O)(=O)N(C)CCOCC(=O)N2CCC(C3CCN(C)CC3)CC2)c(C)c1

,Drug_ID,SMILES,Y,Species
547,CHEMBL2087433,COc1cc(C)c(S(=O)(=O)N(C)CCOCC(=O)N2CCC(C3CCN(C...,51.73,Homo sapiens
2763,CHEMBL2087433,COc1cc(C)c(S(=O)(=O)N(C)CCOCC(=O)N2CCC(C3CCN(C...,48.85,Rattus norvegicus

COc1cc(C)c(S(=O)(=O)N(C)CCOCC(=O)N2CCN(C3CCN(C)CC3)CC2)c(C)c1

,Drug_ID,SMILES,Y,Species
795,CHEMBL2087421,COc1cc(C)c(S(=O)(=O)N(C)CCOCC(=O)N2CCN(C3CCN(C...,42.01,Homo sapiens
2618,CHEMBL2087421,COc1cc(C)c(S(=O)(=O)N(C)CCOCC(=O)N2CCN(C3CCN(C...,37.06,Rattus norvegicus

COc1cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)cccc32)ccn1

,Drug_ID,SMILES,Y,Species
1706,CHEMBL2177911,COc1cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)cccc...,95.33,Homo sapiens
2041,CHEMBL2177911,COc1cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)cccc...,91.64,Mus musculus

COc1cc(NC(=O)Nc2cccc(CNC(=O)O[C@H]3CCOC3)c2)ccc1-c1cnco1

,Drug_ID,SMILES,Y,Species
908,CHEMBL304087,COc1cc(NC(=O)Nc2cccc(CNC(=O)O[C@H]3CCOC3)c2)cc...,98.70,Homo sapiens
2153,CHEMBL304087,COc1cc(NC(=O)Nc2cccc(CNC(=O)O[C@H]3CCOC3)c2)cc...,99.12,Rattus norvegicus

COc1cc(Nc2nc3c(c(COC4CCCC4)n2)COCC3)ccc1-n1cnc(C)c1

,Drug_ID,SMILES,Y,Species
1638,CHEMBL2151176,COc1cc(Nc2nc3c(c(COC4CCCC4)n2)COCC3)ccc1-n1cnc...,99.01,Homo sapiens
2044,CHEMBL2151176,COc1cc(Nc2nc3c(c(COC4CCCC4)n2)COCC3)ccc1-n1cnc...,98.51,Mus musculus
2780,CHEMBL2151176,COc1cc(Nc2nc3c(c(COC4CCCC4)n2)COCC3)ccc1-n1cnc...,97.95,Rattus norvegicus

COc1cc(Nc2nc3c(c(Cc4ccccc4)n2)CN(CCO)CC3)ccc1-n1cnc(C)c1

,Drug_ID,SMILES,Y,Species
563,CHEMBL2151177,COc1cc(Nc2nc3c(c(Cc4ccccc4)n2)CN(CCO)CC3)ccc1-...,98.09,Homo sapiens
2050,CHEMBL2151177,COc1cc(Nc2nc3c(c(Cc4ccccc4)n2)CN(CCO)CC3)ccc1-...,98.00,Mus musculus

COc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2)n[nH]1

,Drug_ID,SMILES,Y,Species
59,CHEMBL2151326,COc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2)...,65.06,Canis lupus familiaris
750,CHEMBL2151326,COc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2)...,78.41,Homo sapiens
2411,CHEMBL2151326,COc1cc(Nc2nc3c(cc2F)ncn3[C@@H](CO)c2ccc(F)cn2)...,63.47,Rattus norvegicus

COc1cc([C@@H]2c3cc4c(cc3C(O[C@@H]3O[C@@H]5CO[C@@H](C)O[C@H]5[C@H](O)[C@H]3O)C3COC(=O)[C@@H]32)OCO4)cc(OC)c1O

,Drug_ID,SMILES,Y,Species
141,CHEMBL320876,COc1cc([C@@H]2c3cc4c(cc3C(O[C@@H]3O[C@@H]5CO[C...,52.30,Canis lupus familiaris
1589,CHEMBL320876,COc1cc([C@@H]2c3cc4c(cc3C(O[C@@H]3O[C@@H]5CO[C...,98.17,Homo sapiens
2288,CHEMBL320876,COc1cc([C@@H]2c3cc4c(cc3C(O[C@@H]3O[C@@H]5CO[C...,78.79,Rattus norvegicus

COc1cc2c(cc1-c1c(C)noc1C)ncc1[nH]c(=O)n([C@H](C)c3ccccn3)c12

,Drug_ID,SMILES,Y,Species
149,CHEMBL2017291,COc1cc2c(cc1-c1c(C)noc1C)ncc1[nH]c(=O)n([C@H](...,89.49,Canis lupus familiaris
1707,CHEMBL2017291,COc1cc2c(cc1-c1c(C)noc1C)ncc1[nH]c(=O)n([C@H](...,97.66,Homo sapiens
2764,CHEMBL2017291,COc1cc2c(cc1-c1c(C)noc1C)ncc1[nH]c(=O)n([C@H](...,96.26,Rattus norvegicus

COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2

,Drug_ID,SMILES,Y,Species
78,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,38.69,Canis lupus familiaris
1103,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,89.49,Homo sapiens
2578,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,66.10,Rattus norvegicus

COc1cc2nc(N3CCN(C(=O)c4ccco4)CC3)nc(N)c2cc1OC

,Drug_ID,SMILES,Y,Species
627,CHEMBL2,COc1cc2nc(N3CCN(C(=O)c4ccco4)CC3)nc(N)c2cc1OC,96.00,Homo sapiens
2570,CHEMBL2,COc1cc2nc(N3CCN(C(=O)c4ccco4)CC3)nc(N)c2cc1OC,78.41,Rattus norvegicus

COc1cc2nnc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(C)CC1

,Drug_ID,SMILES,Y,Species
231,CHEMBL1683036,COc1cc2nnc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(C...,87.87,Canis lupus familiaris
1445,CHEMBL1683036,COc1cc2nnc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(C...,93.67,Homo sapiens
2397,CHEMBL1683036,COc1cc2nnc(C(N)=O)c(Nc3ccc(C)cc3F)c2cc1N1CCN(C...,93.10,Rattus norvegicus

COc1cc2nnc(C(N)=O)c(Nc3ccc(F)cc3F)c2cc1N1CCN(C)CC1

,Drug_ID,SMILES,Y,Species
1015,CHEMBL1683035,COc1cc2nnc(C(N)=O)c(Nc3ccc(F)cc3F)c2cc1N1CCN(C...,90.52,Homo sapiens
2672,CHEMBL1683035,COc1cc2nnc(C(N)=O)c(Nc3ccc(F)cc3F)c2cc1N1CCN(C...,84.30,Rattus norvegicus

COc1ccc(-c2c(C(=O)N3CCC[C@H]3CO)cc3cccnn23)cc1

,Drug_ID,SMILES,Y,Species
1020,CHEMBL2164564,COc1ccc(-c2c(C(=O)N3CCC[C@H]3CO)cc3cccnn23)cc1,89.05,Homo sapiens
2589,CHEMBL2164564,COc1ccc(-c2c(C(=O)N3CCC[C@H]3CO)cc3cccnn23)cc1,73.81,Rattus norvegicus

COc1ccc(-c2nc(-c3ccccn3)no2)cc1

            Drug_ID                           SMILES      Y            Species
1321  CHEMBL1486109  COc1ccc(-c2nc(-c3ccccn3)no2)cc1  97.60       Homo sapiens
2564  CHEMBL1486109  COc1ccc(-c2nc(-c3ccccn3)no2)cc1  94.56  Rattus norvegicus

COc1ccc(C2(c3ccc(F)c(-c4cccnc4F)c3)N=C(N)N(C)C2=O)cc1C

,Drug_ID,SMILES,Y,Species
2042,CHEMBL584926,COc1ccc(C2(c3ccc(F)c(-c4cccnc4F)c3)N=C(N)N(C)C...,99.19,Mus musculus
2356,CHEMBL584926,COc1ccc(C2(c3ccc(F)c(-c4cccnc4F)c3)N=C(N)N(C)C...,99.01,Rattus norvegicus

COc1ccc(C2(c3cccc(-c4cncnc4)c3)N=C(C)C(N)=N2)cc1C

,Drug_ID,SMILES,Y,Species
928,CHEMBL2180027,COc1ccc(C2(c3cccc(-c4cncnc4)c3)N=C(C)C(N)=N2)cc1C,93.80,Homo sapiens
2121,CHEMBL2180027,COc1ccc(C2(c3cccc(-c4cncnc4)c3)N=C(C)C(N)=N2)cc1C,72.91,Rattus norvegicus

COc1ccc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)cccc32)cc1

,Drug_ID,SMILES,Y,Species
1260,CHEMBL2177916,COc1ccc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)ccc...,97.32,Homo sapiens
1989,CHEMBL2177916,COc1ccc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)ccc...,95.33,Mus musculus

COc1ccc(C2CNC(=O)C2)cc1OC1CCCC1

       Drug_ID                           SMILES      Y            Species
1196  CHEMBL63  COc1ccc(C2CNC(=O)C2)cc1OC1CCCC1  82.72       Homo sapiens
2521  CHEMBL63  COc1ccc(C2CNC(=O)C2)cc1OC1CCCC1  67.12  Rattus norvegicus

COc1ccc(CC(=O)NCc2ccccc2-c2ccccc2C(=O)NCCc2cccnc2)cc1

,Drug_ID,SMILES,Y,Species
111,CHEMBL1671897,COc1ccc(CC(=O)NCc2ccccc2-c2ccccc2C(=O)NCCc2ccc...,92.95,Canis lupus familiaris
287,CHEMBL1671897,COc1ccc(CC(=O)NCc2ccccc2-c2ccccc2C(=O)NCCc2ccc...,83.04,Cavia porcellus
1351,CHEMBL1671897,COc1ccc(CC(=O)NCc2ccccc2-c2ccccc2C(=O)NCCc2ccc...,99.34,Homo sapiens
2039,CHEMBL1671897,COc1ccc(CC(=O)NCc2ccccc2-c2ccccc2C(=O)NCCc2ccc...,91.28,Mus musculus
2497,CHEMBL1671897,COc1ccc(CC(=O)NCc2ccccc2-c2ccccc2C(=O)NCCc2ccc...,91.64,Rattus norvegicus

COc1ccc(CC(C)(C)NC[C@H](O)c2cc(O)cc3c2OCC(=O)N3)cc1

,Drug_ID,SMILES,Y,Species
1270,CHEMBL605846,COc1ccc(CC(C)(C)NC[C@H](O)c2cc(O)cc3c2OCC(=O)N...,59.11,Homo sapiens
2571,CHEMBL605846,COc1ccc(CC(C)(C)NC[C@H](O)c2cc(O)cc3c2OCC(=O)N...,55.73,Rattus norvegicus

COc1ccc(CCC[N+](C)(CCCc2ccc(OC)cc2)CCNC(=O)c2nc(Cl)c(N)nc2N)cc1

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,Drug_ID,SMILES,Y,Species
1618,CHEMBL1962896,COc1ccc(CCC[N+](C)(CCCc2ccc(OC)cc2)CCNC(=O)c2n...,83.68,Homo sapiens
2636,CHEMBL1962896,COc1ccc(CCC[N+](C)(CCCc2ccc(OC)cc2)CCNC(=O)c2n...,84.30,Rattus norvegicus

COc1ccc(CCN(C)CCCC(C#N)(c2ccc(OC)c(OC)c2)C(C)C)cc1OC

,Drug_ID,SMILES,Y,Species
877,CHEMBL6966,COc1ccc(CCN(C)CCCC(C#N)(c2ccc(OC)c(OC)c2)C(C)C...,89.27,Homo sapiens
2072,CHEMBL6966,COc1ccc(CCN(C)CCCC(C#N)(c2ccc(OC)c(OC)c2)C(C)C...,89.91,Mus musculus
2126,CHEMBL6966,COc1ccc(CCN(C)CCCC(C#N)(c2ccc(OC)c(OC)c2)C(C)C...,86.05,Rattus norvegicus

COc1ccc(CCN2C(=O)N(NS(C)(=O)=O)C[C@@H]2c2ccc(OC)cc2)cc1

,Drug_ID,SMILES,Y,Species
126,CHEMBL569184,COc1ccc(CCN2C(=O)N(NS(C)(=O)=O)C[C@@H]2c2ccc(O...,91.46,Canis lupus familiaris
691,CHEMBL569184,COc1ccc(CCN2C(=O)N(NS(C)(=O)=O)C[C@@H]2c2ccc(O...,95.23,Homo sapiens
2737,CHEMBL569184,COc1ccc(CCN2C(=O)N(NS(C)(=O)=O)C[C@@H]2c2ccc(O...,98.09,Rattus norvegicus

COc1ccc(CCN2C(=O)N(NS(C)(=O)=O)C[C@H]2c2ccc(OC)cc2)cc1

,Drug_ID,SMILES,Y,Species
65,CHEMBL569185,COc1ccc(CCN2C(=O)N(NS(C)(=O)=O)C[C@H]2c2ccc(OC...,91.10,Canis lupus familiaris
1946,CHEMBL569185,COc1ccc(CCN2C(=O)N(NS(C)(=O)=O)C[C@H]2c2ccc(OC...,93.67,Homo sapiens
2748,CHEMBL569185,COc1ccc(CCN2C(=O)N(NS(C)(=O)=O)C[C@H]2c2ccc(OC...,94.32,Rattus norvegicus

COc1ccc(CCO[C@@H]2CCCC[C@H]2N2CC[C@@H](O)C2)cc1OC

,Drug_ID,SMILES,Y,Species
20,CHEMBL2111112,COc1ccc(CCO[C@@H]2CCCC[C@H]2N2CC[C@@H](O)C2)cc1OC,22.79,Canis lupus familiaris
271,CHEMBL2111112,COc1ccc(CCO[C@@H]2CCCC[C@H]2N2CC[C@@H](O)C2)cc1OC,69.12,Cavia porcellus
460,CHEMBL2111112,COc1ccc(CCO[C@@H]2CCCC[C@H]2N2CC[C@@H](O)C2)cc1OC,37.06,Homo sapiens
2652,CHEMBL2111112,COc1ccc(CCO[C@@H]2CCCC[C@H]2N2CC[C@@H](O)C2)cc1OC,22.38,Rattus norvegicus

COc1ccc(CNC(=O)Nc2ncc([N+](=O)[O-])s2)cc1

,Drug_ID,SMILES,Y,Species
868,CHEMBL259850,COc1ccc(CNC(=O)Nc2ncc([N+](=O)[O-])s2)cc1,99.68,Homo sapiens
2683,CHEMBL259850,COc1ccc(CNC(=O)Nc2ncc([N+](=O)[O-])s2)cc1,98.92,Rattus norvegicus

COc1ccc(C[C@@H](C)NC[C@H](O)c2ccc(O)c(NC=O)c2)cc1

,Drug_ID,SMILES,Y,Species
199,CHEMBL1363,COc1ccc(C[C@@H](C)NC[C@H](O)c2ccc(O)c(NC=O)c2)cc1,17.95,Canis lupus familiaris
500,CHEMBL1363,COc1ccc(C[C@@H](C)NC[C@H](O)c2ccc(O)c(NC=O)c2)cc1,31.87,Homo sapiens
2697,CHEMBL1363,COc1ccc(C[C@@H](C)NC[C@H](O)c2ccc(O)c(NC=O)c2)cc1,60.77,Rattus norvegicus

COc1ccc(Cl)cc1C(=O)NCCc1ccc(S(=O)(=O)NC(=O)NC2CCCCC2)cc1

,Drug_ID,SMILES,Y,Species
1009,CHEMBL472,COc1ccc(Cl)cc1C(=O)NCCc1ccc(S(=O)(=O)NC(=O)NC2...,99.88,Homo sapiens
2077,CHEMBL472,COc1ccc(Cl)cc1C(=O)NCCc1ccc(S(=O)(=O)NC(=O)NC2...,99.73,Mus musculus
2132,CHEMBL472,COc1ccc(Cl)cc1C(=O)NCCc1ccc(S(=O)(=O)NC(=O)NC2...,99.88,Rattus norvegicus

COc1ccc(Cl)cc1C1(F)C(=O)Nc2cc(C(F)(F)F)ccc21

,Drug_ID,SMILES,Y,Species
1510,CHEMBL7662,COc1ccc(Cl)cc1C1(F)C(=O)Nc2cc(C(F)(F)F)ccc21,99.83,Homo sapiens
2086,CHEMBL7662,COc1ccc(Cl)cc1C1(F)C(=O)Nc2cc(C(F)(F)F)ccc21,99.81,Mus musculus
2193,CHEMBL7662,COc1ccc(Cl)cc1C1(F)C(=O)Nc2cc(C(F)(F)F)ccc21,99.85,Rattus norvegicus

COc1ccc(NC(=O)c2ccc(C[S+](C)[O-])c3ccccc23)c(C(=O)NCC2CCOCC2)n1

,Drug_ID,SMILES,Y,Species
912,CHEMBL2316382,COc1ccc(NC(=O)c2ccc(C[S+](C)[O-])c3ccccc23)c(C...,94.56,Homo sapiens
2660,CHEMBL2316382,COc1ccc(NC(=O)c2ccc(C[S+](C)[O-])c3ccccc23)c(C...,95.63,Rattus norvegicus

COc1ccc(OC(F)(F)F)cc1CN[C@H]1CCCN[C@H]1c1ccccc1

,Drug_ID,SMILES,Y,Species
275,CHEMBL319118,COc1ccc(OC(F)(F)F)cc1CN[C@H]1CCCN[C@H]1c1ccccc1,92.16,Cavia porcellus
2814,CHEMBL319118,COc1ccc(OC(F)(F)F)cc1CN[C@H]1CCCN[C@H]1c1ccccc1,90.72,Rattus norvegicus

COc1ccc(S(=O)(=O)N2CC(C)N(S(=O)(=O)c3ccc(OC)cc3)CC2C)cc1

,Drug_ID,SMILES,Y,Species
392,CHEMBL1461208,COc1ccc(S(=O)(=O)N2CC(C)N(S(=O)(=O)c3ccc(OC)cc...,99.65,Homo sapiens
2091,CHEMBL1461208,COc1ccc(S(=O)(=O)N2CC(C)N(S(=O)(=O)c3ccc(OC)cc...,98.21,Mus musculus
2654,CHEMBL1461208,COc1ccc(S(=O)(=O)N2CC(C)N(S(=O)(=O)c3ccc(OC)cc...,98.61,Rattus norvegicus

COc1ccc([C@@H]2Sc3ccccc3N(CCN(C)C)C(=O)[C@@H]2OC(C)=O)cc1

,Drug_ID,SMILES,Y,Species
60,CHEMBL23,COc1ccc([C@@H]2Sc3ccccc3N(CCN(C)C)C(=O)[C@@H]2...,65.06,Canis lupus familiaris
1767,CHEMBL23,COc1ccc([C@@H]2Sc3ccccc3N(CCN(C)C)C(=O)[C@@H]2...,75.97,Homo sapiens

COc1ccc([C@]2(C#N)CC[C@@H](C(=O)O)CC2)cc1OC1CCCC1

,Drug_ID,SMILES,Y,Species
470,CHEMBL511115,COc1ccc([C@]2(C#N)CC[C@@H](C(=O)O)CC2)cc1OC1CCCC1,98.84,Homo sapiens
2440,CHEMBL511115,COc1ccc([C@]2(C#N)CC[C@@H](C(=O)O)CC2)cc1OC1CCCC1,93.94,Rattus norvegicus

COc1ccc2c(C)cc(N[C@H]3CC[C@H](NCc4cn(C)c5ccc(C#N)cc45)C3)nc2c1

,Drug_ID,SMILES,Y,Species
113,CHEMBL398748,COc1ccc2c(C)cc(N[C@H]3CC[C@H](NCc4cn(C)c5ccc(C...,97.91,Canis lupus familiaris
1905,CHEMBL398748,COc1ccc2c(C)cc(N[C@H]3CC[C@H](NCc4cn(C)c5ccc(C...,98.61,Homo sapiens
2520,CHEMBL398748,COc1ccc2c(C)cc(N[C@H]3CC[C@H](NCc4cn(C)c5ccc(C...,98.54,Rattus norvegicus

COc1ccc2c(C)cc(N[C@H]3CC[C@H](NCc4cn(C)c5cccnc45)C3)nc2c1

,Drug_ID,SMILES,Y,Species
282,CHEMBL251701,COc1ccc2c(C)cc(N[C@H]3CC[C@H](NCc4cn(C)c5cccnc...,91.46,Cavia porcellus
1470,CHEMBL251701,COc1ccc2c(C)cc(N[C@H]3CC[C@H](NCc4cn(C)c5cccnc...,97.38,Homo sapiens
1991,CHEMBL251701,COc1ccc2c(C)cc(N[C@H]3CC[C@H](NCc4cn(C)c5cccnc...,93.53,Mus musculus

COc1ccc2c(c1)C(=O)C(=O)N2CC1COc2ccccc2O1

,Drug_ID,SMILES,Y,Species
1343,CHEMBL1496905,COc1ccc2c(c1)C(=O)C(=O)N2CC1COc2ccccc2O1,99.34,Homo sapiens
2278,CHEMBL1496905,COc1ccc2c(c1)C(=O)C(=O)N2CC1COc2ccccc2O1,99.41,Rattus norvegicus

COc1ccc2c(c1)c(CC(=O)O)c(C)n2-c1ccnc2cc(Cl)ccc12

,Drug_ID,SMILES,Y,Species
7,CHEMBL213029,COc1ccc2c(c1)c(CC(=O)O)c(C)n2-c1ccnc2cc(Cl)ccc12,98.17,Canis lupus familiaris
1060,CHEMBL213029,COc1ccc2c(c1)c(CC(=O)O)c(C)n2-c1ccnc2cc(Cl)ccc12,99.01,Homo sapiens

COc1ccc2cc(S(=O)(=O)N[C@H](CC(=O)N[C@H](Cc3ccc(CN4[C@@H](C)CCC[C@H]4C)cc3)C(=O)N(C)C(C)C)c3ccc4c(c3)OCO4)ccc2c1

,Drug_ID,SMILES,Y,Species
1499,CHEMBL2021721,COc1ccc2cc(S(=O)(=O)N[C@H](CC(=O)N[C@H](Cc3ccc...,96.00,Homo sapiens
1996,CHEMBL2021721,COc1ccc2cc(S(=O)(=O)N[C@H](CC(=O)N[C@H](Cc3ccc...,96.00,Mus musculus
2238,CHEMBL2021721,COc1ccc2cc(S(=O)(=O)N[C@H](CC(=O)N[C@H](Cc3ccc...,95.53,Rattus norvegicus

COc1ccc2ncc(F)c(CCN3CCC(NCc4cc5c(cn4)OCCO5)CC3)c2n1

,Drug_ID,SMILES,Y,Species
120,CHEMBL1916532,COc1ccc2ncc(F)c(CCN3CCC(NCc4cc5c(cn4)OCCO5)CC3...,90.32,Canis lupus familiaris
1776,CHEMBL1916532,COc1ccc2ncc(F)c(CCN3CCC(NCc4cc5c(cn4)OCCO5)CC3...,82.72,Homo sapiens
2067,CHEMBL1916532,COc1ccc2ncc(F)c(CCN3CCC(NCc4cc5c(cn4)OCCO5)CC3...,64.01,Mus musculus

COc1cccc(CNCc2cccc(CCNC[C@H](O)c3ccc(O)c4[nH]c(=O)sc34)c2)c1

,Drug_ID,SMILES,Y,Species
273,CHEMBL1945044,COc1cccc(CNCc2cccc(CCNC[C@H](O)c3ccc(O)c4[nH]c...,78.41,Cavia porcellus
829,CHEMBL1945044,COc1cccc(CNCc2cccc(CCNC[C@H](O)c3ccc(O)c4[nH]c...,86.32,Homo sapiens
2218,CHEMBL1945044,COc1cccc(CNCc2cccc(CCNC[C@H](O)c3ccc(O)c4[nH]c...,84.60,Rattus norvegicus

COc1cccc(Nc2c(C(N)=O)cnc3c(C)cc(S(=O)(=O)c4cccc(C(=O)N(C)C)c4)cc23)c1

,Drug_ID,SMILES,Y,Species
594,CHEMBL570015,COc1cccc(Nc2c(C(N)=O)cnc3c(C)cc(S(=O)(=O)c4ccc...,98.51,Homo sapiens
2162,CHEMBL570015,COc1cccc(Nc2c(C(N)=O)cnc3c(C)cc(S(=O)(=O)c4ccc...,97.60,Rattus norvegicus

COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(CNC(=O)C(C)(C)O)c1

,Drug_ID,SMILES,Y,Species
326,CHEMBL2018969,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,96.50,Cavia porcellus
1679,CHEMBL2018969,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,98.67,Homo sapiens
2555,CHEMBL2018969,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,99.18,Rattus norvegicus

COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(CNC(=O)[C@@H]2COCCN2)c1

,Drug_ID,SMILES,Y,Species
1441,CHEMBL2326624,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,98.40,Homo sapiens
2785,CHEMBL2326624,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,98.44,Rattus norvegicus

COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(CNC(=O)[C@H]2COCCN2)c1

,Drug_ID,SMILES,Y,Species
1540,CHEMBL2326623,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,98.44,Homo sapiens
2143,CHEMBL2326623,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,99.48,Rattus norvegicus

COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(CNC(C)=O)c1

,Drug_ID,SMILES,Y,Species
1251,CHEMBL2018964,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,99.34,Homo sapiens
2816,CHEMBL2018964,COc1cccc2c1c(NS(=O)(=O)c1ccc(Cl)s1)nn2Cc1cccc(...,99.72,Rattus norvegicus

COc1ccccc1-c1csc(-n2ncc(C#N)c2N)n1

,Drug_ID,SMILES,Y,Species
715,CHEMBL1322893,COc1ccccc1-c1csc(-n2ncc(C#N)c2N)n1,40.89,Homo sapiens
2575,CHEMBL1322893,COc1ccccc1-c1csc(-n2ncc(C#N)c2N)n1,47.12,Rattus norvegicus

COc1ccccc1CCNCc1ccc(CCNC[C@H](O)c2ccc(O)c3[nH]c(=O)sc23)cc1

,Drug_ID,SMILES,Y,Species
320,CHEMBL1944694,COc1ccccc1CCNCc1ccc(CCNC[C@H](O)c2ccc(O)c3[nH]...,95.53,Cavia porcellus
660,CHEMBL1944694,COc1ccccc1CCNCc1ccc(CCNC[C@H](O)c2ccc(O)c3[nH]...,95.53,Homo sapiens
2171,CHEMBL1944694,COc1ccccc1CCNCc1ccc(CCNC[C@H](O)c2ccc(O)c3[nH]...,93.94,Rattus norvegicus

COc1ccccc1CCNCc1cccc(CCNC[C@H](O)c2ccc(O)c3[nH]c(=O)sc23)c1

,Drug_ID,SMILES,Y,Species
295,CHEMBL1944693,COc1ccccc1CCNCc1cccc(CCNC[C@H](O)c2ccc(O)c3[nH...,72.45,Cavia porcellus
1713,CHEMBL1944693,COc1ccccc1CCNCc1cccc(CCNC[C@H](O)c2ccc(O)c3[nH...,94.06,Homo sapiens
2605,CHEMBL1944693,COc1ccccc1CCNCc1cccc(CCNC[C@H](O)c2ccc(O)c3[nH...,91.64,Rattus norvegicus

COc1ccccc1CN(C(C)=O)c1cnccc1Oc1ccccc1

,Drug_ID,SMILES,Y,Species
473,CHEMBL2068817,COc1ccccc1CN(C(C)=O)c1cnccc1Oc1ccccc1,93.10,Homo sapiens
2539,CHEMBL2068817,COc1ccccc1CN(C(C)=O)c1cnccc1Oc1ccccc1,89.91,Rattus norvegicus

COc1ccccc1O[C@@H](c1ccccc1)[C@@H]1CNCCO1

,Drug_ID,SMILES,Y,Species
690,CHEMBL223166,COc1ccccc1O[C@@H](c1ccccc1)[C@@H]1CNCCO1,69.12,Homo sapiens
2755,CHEMBL223166,COc1ccccc1O[C@@H](c1ccccc1)[C@@H]1CNCCO1,23.19,Rattus norvegicus

COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO

,Drug_ID,SMILES,Y,Species
1838,CHEMBL957,COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc...,98.70,Homo sapiens
2720,CHEMBL957,COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc...,98.78,Rattus norvegicus

COc1cnc(-c2c(C)ccc(F)c2CCNC(=O)c2ccc(COCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
179,CHEMBL2147307,COc1cnc(-c2c(C)ccc(F)c2CCNC(=O)c2ccc(COCC(F)(F...,94.90,Canis lupus familiaris
465,CHEMBL2147307,COc1cnc(-c2c(C)ccc(F)c2CCNC(=O)c2ccc(COCC(F)(F...,97.60,Homo sapiens
1992,CHEMBL2147307,COc1cnc(-c2c(C)ccc(F)c2CCNC(=O)c2ccc(COCC(F)(F...,89.91,Mus musculus
2810,CHEMBL2147307,COc1cnc(-c2c(C)ccc(F)c2CCNC(=O)c2ccc(COCC(F)(F...,90.12,Rattus norvegicus

COc1cnc(-c2cccc(F)c2C(F)(F)CNC(=O)c2ccc(COCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
936,CHEMBL2147317,COc1cnc(-c2cccc(F)c2C(F)(F)CNC(=O)c2ccc(COCC(F...,96.72,Homo sapiens
2550,CHEMBL2147317,COc1cnc(-c2cccc(F)c2C(F)(F)CNC(=O)c2ccc(COCC(F...,95.43,Rattus norvegicus

COc1cnc(-c2ccccc2C(F)(F)CNC(=O)c2ccc(COCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
306,CHEMBL2147316,COc1cnc(-c2ccccc2C(F)(F)CNC(=O)c2ccc(COCC(F)(F...,94.56,Cavia porcellus
1174,CHEMBL2147316,COc1cnc(-c2ccccc2C(F)(F)CNC(=O)c2ccc(COCC(F)(F...,99.31,Homo sapiens
2751,CHEMBL2147316,COc1cnc(-c2ccccc2C(F)(F)CNC(=O)c2ccc(COCC(F)(F...,94.68,Rattus norvegicus

COc1nc(Br)cnc1NS(=O)(=O)c1ccc(Cl)s1

,Drug_ID,SMILES,Y,Species
147,CHEMBL2011441,COc1nc(Br)cnc1NS(=O)(=O)c1ccc(Cl)s1,98.76,Canis lupus familiaris
756,CHEMBL2011441,COc1nc(Br)cnc1NS(=O)(=O)c1ccc(Cl)s1,99.87,Homo sapiens
1954,CHEMBL2011441,COc1nc(Br)cnc1NS(=O)(=O)c1ccc(Cl)s1,98.09,Mus musculus
2795,CHEMBL2011441,COc1nc(Br)cnc1NS(=O)(=O)c1ccc(Cl)s1,99.80,Rattus norvegicus

COc1ncc(-c2c(C)ccc(F)c2CCNC(=O)c2ccc(OCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
1294,CHEMBL2147306,COc1ncc(-c2c(C)ccc(F)c2CCNC(=O)c2ccc(OCC(F)(F)...,99.80,Homo sapiens
2374,CHEMBL2147306,COc1ncc(-c2c(C)ccc(F)c2CCNC(=O)c2ccc(OCC(F)(F)...,95.63,Rattus norvegicus

COc1ncc(-c2cccc(C#N)c2CCNC(=O)c2ccc(OCCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
1939,CHEMBL2147226,COc1ncc(-c2cccc(C#N)c2CCNC(=O)c2ccc(OCCC(F)(F)...,88.11,Homo sapiens
2721,CHEMBL2147226,COc1ncc(-c2cccc(C#N)c2CCNC(=O)c2ccc(OCCC(F)(F)...,86.05,Rattus norvegicus

COc1ncc(-c2cccc(C)c2CCNC(=O)c2ccc(OCCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
361,CHEMBL2147221,COc1ncc(-c2cccc(C)c2CCNC(=O)c2ccc(OCCC(F)(F)F)...,99.50,Homo sapiens
2233,CHEMBL2147221,COc1ncc(-c2cccc(C)c2CCNC(=O)c2ccc(OCCC(F)(F)F)...,94.44,Rattus norvegicus

COc1ncc(-c2cccc(F)c2CCNC(=O)c2ccc(OCCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
1935,CHEMBL2147222,COc1ncc(-c2cccc(F)c2CCNC(=O)c2ccc(OCCC(F)(F)F)...,99.50,Homo sapiens
2502,CHEMBL2147222,COc1ncc(-c2cccc(F)c2CCNC(=O)c2ccc(OCCC(F)(F)F)...,93.24,Rattus norvegicus

COc1ncc(-c2cccc3c2C[C@H](NC(=O)c2ccc(COCC(F)(F)F)nc2)CO3)cn1

,Drug_ID,SMILES,Y,Species
225,CHEMBL2069423,COc1ncc(-c2cccc3c2C[C@H](NC(=O)c2ccc(COCC(F)(F...,92.95,Canis lupus familiaris
742,CHEMBL2069423,COc1ncc(-c2cccc3c2C[C@H](NC(=O)c2ccc(COCC(F)(F...,96.34,Homo sapiens

COc1ncc(-c2ccccc2C(F)(F)CNC(=O)c2ccc(COCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
967,CHEMBL2147303,COc1ncc(-c2ccccc2C(F)(F)CNC(=O)c2ccc(COCC(F)(F...,99.01,Homo sapiens
2158,CHEMBL2147303,COc1ncc(-c2ccccc2C(F)(F)CNC(=O)c2ccc(COCC(F)(F...,87.11,Rattus norvegicus

CS(=O)(=O)N1CCC(NC(=O)NC23CC4CC(CC(C4)C2)C3)CC1

,Drug_ID,SMILES,Y,Species
1157,CHEMBL1668935,CS(=O)(=O)N1CCC(NC(=O)NC23CC4CC(CC(C4)C2)C3)CC1,71.05,Homo sapiens
2025,CHEMBL1668935,CS(=O)(=O)N1CCC(NC(=O)NC23CC4CC(CC(C4)C2)C3)CC1,83.04,Mus musculus
2588,CHEMBL1668935,CS(=O)(=O)N1CCC(NC(=O)NC23CC4CC(CC(C4)C2)C3)CC1,73.81,Rattus norvegicus

CS(=O)(=O)Nc1ccc2[nH]c(Cc3ccc(Oc4ccccc4)cc3)nc2c1

,Drug_ID,SMILES,Y,Species
1697,CHEMBL65693,CS(=O)(=O)Nc1ccc2[nH]c(Cc3ccc(Oc4ccccc4)cc3)nc2c1,99.45,Homo sapiens
1958,CHEMBL65693,CS(=O)(=O)Nc1ccc2[nH]c(Cc3ccc(Oc4ccccc4)cc3)nc2c1,99.41,Mus musculus
2470,CHEMBL65693,CS(=O)(=O)Nc1ccc2[nH]c(Cc3ccc(Oc4ccccc4)cc3)nc2c1,99.39,Rattus norvegicus

CS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c(Cl)c1

,Drug_ID,SMILES,Y,Species
747,CHEMBL1778637,CS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c(...,95.82,Homo sapiens
2449,CHEMBL1778637,CS(=O)(=O)c1ccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c(...,95.01,Rattus norvegicus

CS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(Cl)c1

,Drug_ID,SMILES,Y,Species
860,CHEMBL1778642,CS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(Cl)c1,97.49,Homo sapiens
2818,CHEMBL1778642,CS(=O)(=O)c1ccc(-c2cc(Cl)ccc2OCC(=O)O)c(Cl)c1,96.50,Rattus norvegicus

CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2

,Drug_ID,SMILES,Y,Species
1158,CHEMBL479,CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2,99.63,Homo sapiens
2495,CHEMBL479,CSc1ccc2c(c1)N(CCC1CCCCN1C)c1ccccc1S2,99.30,Rattus norvegicus

C[C@@H](CC(=O)OC(C)(C)C)NC(=O)C1=NOC(C(O)(C(F)(F)F)C(F)(F)F)C1

,Drug_ID,SMILES,Y,Species
1521,CHEMBL208825,C[C@@H](CC(=O)OC(C)(C)C)NC(=O)C1=NOC(C(O)(C(F)...,84.00,Homo sapiens
1966,CHEMBL208825,C[C@@H](CC(=O)OC(C)(C)C)NC(=O)C1=NOC(C(O)(C(F)...,79.92,Mus musculus
2428,CHEMBL208825,C[C@@H](CC(=O)OC(C)(C)C)NC(=O)C1=NOC(C(O)(C(F)...,84.00,Rattus norvegicus

C[C@@H](CC(=O)OC(C)(C)C)NC(=O)C1=NO[C@@H](C(O)(C(F)(F)F)C(F)(F)F)C1

,Drug_ID,SMILES,Y,Species
1143,CHEMBL211177,C[C@@H](CC(=O)OC(C)(C)C)NC(=O)C1=NO[C@@H](C(O)...,82.05,Homo sapiens
2391,CHEMBL211177,C[C@@H](CC(=O)OC(C)(C)C)NC(=O)C1=NO[C@@H](C(O)...,81.01,Rattus norvegicus

C[C@@H](NC(=O)Cc1ccc(C2CC2)cc1)c1ccc(OCC(F)(F)F)cn1

,Drug_ID,SMILES,Y,Species
301,CHEMBL1684954,C[C@@H](NC(=O)Cc1ccc(C2CC2)cc1)c1ccc(OCC(F)(F)...,99.94,Cavia porcellus
1566,CHEMBL1684954,C[C@@H](NC(=O)Cc1ccc(C2CC2)cc1)c1ccc(OCC(F)(F)...,99.59,Homo sapiens
2281,CHEMBL1684954,C[C@@H](NC(=O)Cc1ccc(C2CC2)cc1)c1ccc(OCC(F)(F)...,99.56,Rattus norvegicus

C[C@@H](NC(=O)[C@H]1CCCCN1)c1ccc(Nc2ncc3cc(-c4ccncc4)ccc3n2)cc1

,Drug_ID,SMILES,Y,Species
72,CHEMBL2335897,C[C@@H](NC(=O)[C@H]1CCCCN1)c1ccc(Nc2ncc3cc(-c4...,88.59,Canis lupus familiaris
365,CHEMBL2335897,C[C@@H](NC(=O)[C@H]1CCCCN1)c1ccc(Nc2ncc3cc(-c4...,95.12,Homo sapiens

C[C@@H](NC1=CC(=O)CCC1)c1ccc(Nc2ncc3cc(-c4ccncc4)ccc3n2)cc1

,Drug_ID,SMILES,Y,Species
191,CHEMBL2335903,C[C@@H](NC1=CC(=O)CCC1)c1ccc(Nc2ncc3cc(-c4ccnc...,96.79,Canis lupus familiaris
1188,CHEMBL2335903,C[C@@H](NC1=CC(=O)CCC1)c1ccc(Nc2ncc3cc(-c4ccnc...,98.64,Homo sapiens

C[C@@H](O)[C@H](NC(=O)c1ccc(C#Cc2ccc(CN3CCOCC3)cc2)cc1)C(=O)NO

,Drug_ID,SMILES,Y,Species
489,CHEMBL260091,C[C@@H](O)[C@H](NC(=O)c1ccc(C#Cc2ccc(CN3CCOCC3...,96.42,Homo sapiens
2305,CHEMBL260091,C[C@@H](O)[C@H](NC(=O)c1ccc(C#Cc2ccc(CN3CCOCC3...,93.67,Rattus norvegicus

C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl

,Drug_ID,SMILES,Y,Species
239,CHEMBL601719,C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)...,94.79,Canis lupus familiaris
1257,CHEMBL601719,C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)...,92.16,Homo sapiens
2314,CHEMBL601719,C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)...,95.53,Rattus norvegicus

C[C@@H]1CN(c2ccc3c(n2)NC(=O)CO3)[C@H](c2ccccc2)CO1

,Drug_ID,SMILES,Y,Species
1815,CHEMBL2181928,C[C@@H]1CN(c2ccc3c(n2)NC(=O)CO3)[C@H](c2ccccc2...,93.67,Homo sapiens
2808,CHEMBL2181928,C[C@@H]1CN(c2ccc3c(n2)NC(=O)CO3)[C@H](c2ccccc2...,90.72,Rattus norvegicus

C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(Cl)[C@@H](O)C[C@]2(C)[C@@]1(OC(=O)c1ccco1)C(=O)CCl

,Drug_ID,SMILES,Y,Species
128,CHEMBL1161,C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C...,99.70,Canis lupus familiaris
1068,CHEMBL1161,C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C...,99.77,Homo sapiens
2608,CHEMBL1161,C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C...,99.90,Rattus norvegicus

C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)CO

,Drug_ID,SMILES,Y,Species
349,CHEMBL384467,C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C...,71.53,Homo sapiens
2629,CHEMBL384467,C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C...,87.37,Rattus norvegicus

C[C@@](C(=O)OC1CC[N+](C)(C)CC1)(c1ccccc1)C1CCCC1

,Drug_ID,SMILES,Y,Species
272,CHEMBL1963462,C[C@@](C(=O)OC1CC[N+](C)(C)CC1)(c1ccccc1)C1CCCC1,39.23,Cavia porcellus
531,CHEMBL1963462,C[C@@](C(=O)OC1CC[N+](C)(C)CC1)(c1ccccc1)C1CCCC1,57.99,Homo sapiens
2758,CHEMBL1963462,C[C@@](C(=O)OC1CC[N+](C)(C)CC1)(c1ccccc1)C1CCCC1,61.31,Rattus norvegicus

C[C@@](C(=O)O[C@H]1C[N+]2(CC(=O)Nc3cccc(F)c3)CCC1CC2)(c1ccccc1)N1CCCCC1

,Drug_ID,SMILES,Y,Species
333,CHEMBL1921944,C[C@@](C(=O)O[C@H]1C[N+]2(CC(=O)Nc3cccc(F)c3)C...,99.26,Cavia porcellus
422,CHEMBL1921944,C[C@@](C(=O)O[C@H]1C[N+]2(CC(=O)Nc3cccc(F)c3)C...,99.60,Homo sapiens

C[C@@](C(=O)O[C@H]1C[N+]2(CC(=O)Nc3ccccc3)CCC1CC2)(c1ccccc1)N1CCCCC1

,Drug_ID,SMILES,Y,Species
310,CHEMBL1921942,C[C@@](C(=O)O[C@H]1C[N+]2(CC(=O)Nc3ccccc3)CCC1...,95.01,Cavia porcellus
1907,CHEMBL1921942,C[C@@](C(=O)O[C@H]1C[N+]2(CC(=O)Nc3ccccc3)CCC1...,98.58,Homo sapiens
2549,CHEMBL1921942,C[C@@](C(=O)O[C@H]1C[N+]2(CC(=O)Nc3ccccc3)CCC1...,98.61,Rattus norvegicus

C[C@@](C(=O)O[C@H]1C[N+]2(CCCc3ccc4ncsc4c3)CCC1CC2)(c1ccccc1)N1CCCCC1

,Drug_ID,SMILES,Y,Species
290,CHEMBL1921926,C[C@@](C(=O)O[C@H]1C[N+]2(CCCc3ccc4ncsc4c3)CCC...,75.55,Cavia porcellus
726,CHEMBL1921926,C[C@@](C(=O)O[C@H]1C[N+]2(CCCc3ccc4ncsc4c3)CCC...,95.72,Homo sapiens

C[C@@](C(=O)O[C@H]1C[N+]2(CCc3ccccc3)CCC1CC2)(c1ccccc1)N1CCCCC1

,Drug_ID,SMILES,Y,Species
253,CHEMBL1924047,C[C@@](C(=O)O[C@H]1C[N+]2(CCc3ccccc3)CCC1CC2)(...,87.11,Cavia porcellus
1548,CHEMBL1924047,C[C@@](C(=O)O[C@H]1C[N+]2(CCc3ccccc3)CCC1CC2)(...,97.60,Homo sapiens
2286,CHEMBL1924047,C[C@@](C(=O)O[C@H]1C[N+]2(CCc3ccccc3)CCC1CC2)(...,78.01,Rattus norvegicus

C[C@@](C(=O)O[C@H]1C[N+]2(CCc3ccccc3F)CCC1CC2)(c1ccccc1)N1CCCCC1

,Drug_ID,SMILES,Y,Species
324,CHEMBL1924049,C[C@@](C(=O)O[C@H]1C[N+]2(CCc3ccccc3F)CCC1CC2)...,80.65,Cavia porcellus
1177,CHEMBL1924049,C[C@@](C(=O)O[C@H]1C[N+]2(CCc3ccccc3F)CCC1CC2)...,99.19,Homo sapiens

C[C@@](C(=O)O[C@H]1C[N+]2(Cc3nc(-c4ccccc4)no3)CCC1CC2)(c1ccccc1)N1CCCCC1

,Drug_ID,SMILES,Y,Species
327,CHEMBL1922056,C[C@@](C(=O)O[C@H]1C[N+]2(Cc3nc(-c4ccccc4)no3)...,95.01,Cavia porcellus
484,CHEMBL1922056,C[C@@](C(=O)O[C@H]1C[N+]2(Cc3nc(-c4ccccc4)no3)...,97.66,Homo sapiens

C[C@@](O)(C(=O)Nc1ccc(S(C)(=O)=O)cc1Cl)C(F)(F)F

,Drug_ID,SMILES,Y,Species
1362,CHEMBL73048,C[C@@](O)(C(=O)Nc1ccc(S(C)(=O)=O)cc1Cl)C(F)(F)F,60.77,Homo sapiens
2722,CHEMBL73048,C[C@@](O)(C(=O)Nc1ccc(S(C)(=O)=O)cc1Cl)C(F)(F)F,84.00,Rattus norvegicus

C[C@@]1(c2cc(-c3cncnc3)c(F)cc2F)CCSC(N)=N1

,Drug_ID,SMILES,Y,Species
84,CHEMBL2333941,C[C@@]1(c2cc(-c3cncnc3)c(F)cc2F)CCSC(N)=N1,37.06,Canis lupus familiaris
1665,CHEMBL2333941,C[C@@]1(c2cc(-c3cncnc3)c(F)cc2F)CCSC(N)=N1,54.02,Homo sapiens
1983,CHEMBL2333941,C[C@@]1(c2cc(-c3cncnc3)c(F)cc2F)CCSC(N)=N1,32.88,Mus musculus

C[C@H](CN(C(=O)c1ccc(C#N)cc1)c1ccccn1)N1CCN(c2cccc3c2OCCO3)CC1

,Drug_ID,SMILES,Y,Species
308,CHEMBL372205,C[C@H](CN(C(=O)c1ccc(C#N)cc1)c1ccccn1)N1CCN(c2...,86.05,Cavia porcellus
1356,CHEMBL372205,C[C@H](CN(C(=O)c1ccc(C#N)cc1)c1ccccn1)N1CCN(c2...,99.10,Homo sapiens
2040,CHEMBL372205,C[C@H](CN(C(=O)c1ccc(C#N)cc1)c1ccccn1)N1CCN(c2...,86.05,Mus musculus
2342,CHEMBL372205,C[C@H](CN(C(=O)c1ccc(C#N)cc1)c1ccccn1)N1CCN(c2...,82.05,Rattus norvegicus

C[C@H](CO)Nc1nc(SCc2cccc(F)c2F)nc2[nH]c(=O)cnc12

,Drug_ID,SMILES,Y,Species
194,CHEMBL256668,C[C@H](CO)Nc1nc(SCc2cccc(F)c2F)nc2[nH]c(=O)cnc12,97.20,Canis lupus familiaris
1231,CHEMBL256668,C[C@H](CO)Nc1nc(SCc2cccc(F)c2F)nc2[nH]c(=O)cnc12,98.86,Homo sapiens

C[C@H](CO)Nc1nc(SCc2cccc(F)c2F)nc2nc(N)sc12

,Drug_ID,SMILES,Y,Species
37,CHEMBL397237,C[C@H](CO)Nc1nc(SCc2cccc(F)c2F)nc2nc(N)sc12,96.34,Canis lupus familiaris
1034,CHEMBL397237,C[C@H](CO)Nc1nc(SCc2cccc(F)c2F)nc2nc(N)sc12,98.04,Homo sapiens

C[C@H](CO)Nc1nc(SCc2ccccc2)nc2[nH]c(=O)sc12

,Drug_ID,SMILES,Y,Species
69,CHEMBL402986,C[C@H](CO)Nc1nc(SCc2ccccc2)nc2[nH]c(=O)sc12,97.81,Canis lupus familiaris
866,CHEMBL402986,C[C@H](CO)Nc1nc(SCc2ccccc2)nc2[nH]c(=O)sc12,99.71,Homo sapiens

C[C@H](CO)Nc1nc(SCc2ccccc2F)nc2[nH]c(=O)sc12

,Drug_ID,SMILES,Y,Species
221,CHEMBL271012,C[C@H](CO)Nc1nc(SCc2ccccc2F)nc2[nH]c(=O)sc12,98.29,Canis lupus familiaris
757,CHEMBL271012,C[C@H](CO)Nc1nc(SCc2ccccc2F)nc2[nH]c(=O)sc12,99.86,Homo sapiens

C[C@H](CO)Nc1nc(SCc2ccco2)nc2[nH]c(=O)sc12

,Drug_ID,SMILES,Y,Species
85,CHEMBL272705,C[C@H](CO)Nc1nc(SCc2ccco2)nc2[nH]c(=O)sc12,97.26,Canis lupus familiaris
583,CHEMBL272705,C[C@H](CO)Nc1nc(SCc2ccco2)nc2[nH]c(=O)sc12,98.40,Homo sapiens

C[C@H](Cc1cccc(CC(=O)NC23CC4CC(CC(C4)C2)C3)c1)NC[C@H](O)c1ccc(O)c(CO)c1

,Drug_ID,SMILES,Y,Species
267,CHEMBL402501,C[C@H](Cc1cccc(CC(=O)NC23CC4CC(CC(C4)C2)C3)c1)...,79.17,Cavia porcellus
841,CHEMBL402501,C[C@H](Cc1cccc(CC(=O)NC23CC4CC(CC(C4)C2)C3)c1)...,89.91,Homo sapiens
2815,CHEMBL402501,C[C@H](Cc1cccc(CC(=O)NC23CC4CC(CC(C4)C2)C3)c1)...,86.59,Rattus norvegicus

C[C@H](NC(=O)Cc1cc(F)cc(F)c1)C(=O)NC1C(=O)N(C)c2ccccc2-c2ccccc21

,Drug_ID,SMILES,Y,Species
581,CHEMBL421236,C[C@H](NC(=O)Cc1cc(F)cc(F)c1)C(=O)NC1C(=O)N(C)...,99.01,Homo sapiens
2007,CHEMBL421236,C[C@H](NC(=O)Cc1cc(F)cc(F)c1)C(=O)NC1C(=O)N(C)...,98.29,Mus musculus

C[C@H](NC(=O)[C@@H](Cc1c[nH]c2ccccc12)NC(=O)[C@@H](N)Cc1c[nH]cn1)C(=O)N[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@H](Cc1ccccc1)C(=O)N[C@@H](CCCCN)C(N)=O

,Drug_ID,SMILES,Y,Species
47,CHEMBL105462,C[C@H](NC(=O)[C@@H](Cc1c[nH]c2ccccc12)NC(=O)[C...,81.71,Canis lupus familiaris
2273,CHEMBL105462,C[C@H](NC(=O)[C@@H](Cc1c[nH]c2ccccc12)NC(=O)[C...,73.81,Rattus norvegicus

C[C@H](Nc1nc(Nc2cc(C3CC3)[nH]n2)cnc1C#N)c1ccc(F)cn1

,Drug_ID,SMILES,Y,Species
1919,CHEMBL578194,C[C@H](Nc1nc(Nc2cc(C3CC3)[nH]n2)cnc1C#N)c1ccc(...,95.12,Homo sapiens
2553,CHEMBL578194,C[C@H](Nc1nc(Nc2cc(C3CC3)[nH]n2)cnc1C#N)c1ccc(...,93.80,Rattus norvegicus

C[C@H](Nc1ncc(Cl)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc(F)cn1

,Drug_ID,SMILES,Y,Species
203,CHEMBL457608,C[C@H](Nc1ncc(Cl)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc...,89.05,Canis lupus familiaris
806,CHEMBL457608,C[C@H](Nc1ncc(Cl)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc...,96.42,Homo sapiens
2103,CHEMBL457608,C[C@H](Nc1ncc(Cl)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc...,96.42,Mus musculus
2434,CHEMBL457608,C[C@H](Nc1ncc(Cl)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc...,99.10,Rattus norvegicus

C[C@H](Nc1ncc(F)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc(F)cn1

,Drug_ID,SMILES,Y,Species
197,CHEMBL457393,C[C@H](Nc1ncc(F)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc(...,81.71,Canis lupus familiaris
1225,CHEMBL457393,C[C@H](Nc1ncc(F)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc(...,91.99,Homo sapiens
2078,CHEMBL457393,C[C@H](Nc1ncc(F)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc(...,95.82,Mus musculus
2227,CHEMBL457393,C[C@H](Nc1ncc(F)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc(...,96.50,Rattus norvegicus

C[C@H]([C@H](O)c1ccc(O)cc1)N1CCC(O)(c2ccccc2)CC1

,Drug_ID,SMILES,Y,Species
1339,CHEMBL321758,C[C@H]([C@H](O)c1ccc(O)cc1)N1CCC(O)(c2ccccc2)CC1,31.87,Homo sapiens
2371,CHEMBL321758,C[C@H]([C@H](O)c1ccc(O)cc1)N1CCC(O)(c2ccccc2)CC1,39.23,Rattus norvegicus

C[C@H](c1ccc(F)cc1CCCC(=O)O)N(c1cc(F)ccc1F)S(=O)(=O)c1ccc(Cl)cc1

,Drug_ID,SMILES,Y,Species
1628,CHEMBL247471,C[C@H](c1ccc(F)cc1CCCC(=O)O)N(c1cc(F)ccc1F)S(=...,99.9,Homo sapiens
2000,CHEMBL247471,C[C@H](c1ccc(F)cc1CCCC(=O)O)N(c1cc(F)ccc1F)S(=...,99.5,Mus musculus

C[C@H](c1nc2ncccc2c(=O)n1-c1ccc(Cl)cc1)N(CC1CCS(=O)(=O)CC1)C(=O)Cc1ccc(C(F)(F)F)c(F)c1

,Drug_ID,SMILES,Y,Species
109,CHEMBL1939560,C[C@H](c1nc2ncccc2c(=O)n1-c1ccc(Cl)cc1)N(CC1CC...,94.56,Canis lupus familiaris
736,CHEMBL1939560,C[C@H](c1nc2ncccc2c(=O)n1-c1ccc(Cl)cc1)N(CC1CC...,89.05,Homo sapiens
1956,CHEMBL1939560,C[C@H](c1nc2ncccc2c(=O)n1-c1ccc(Cl)cc1)N(CC1CC...,95.23,Mus musculus
2296,CHEMBL1939560,C[C@H](c1nc2ncccc2c(=O)n1-c1ccc(Cl)cc1)N(CC1CC...,89.91,Rattus norvegicus

C[C@H]1CN(C(=O)N[C@H](Cc2ccc(F)cc2)C(=O)N2CCC(C(=O)NC(C)(C)C)(C3CCCCC3)CC2)C[C@@H](C)N1

,Drug_ID,SMILES,Y,Species
848,CHEMBL1761870,C[C@H]1CN(C(=O)N[C@H](Cc2ccc(F)cc2)C(=O)N2CCC(...,92.32,Homo sapiens
1987,CHEMBL1761870,C[C@H]1CN(C(=O)N[C@H](Cc2ccc(F)cc2)C(=O)N2CCC(...,92.48,Mus musculus
2584,CHEMBL1761870,C[C@H]1CN(C(=O)N[C@H](Cc2ccc(F)cc2)C(=O)N2CCC(...,91.28,Rattus norvegicus

C[C@H]1CN(C(=O)[C@@H]2CN(C(C)(C)C)C[C@H]2c2ccc(F)cc2F)C[C@@H](C)[C@]1(O)c1ccccc1

,Drug_ID,SMILES,Y,Species
1605,CHEMBL1090488,C[C@H]1CN(C(=O)[C@@H]2CN(C(C)(C)C)C[C@H]2c2ccc...,76.81,Homo sapiens
2063,CHEMBL1090488,C[C@H]1CN(C(=O)[C@@H]2CN(C(C)(C)C)C[C@H]2c2ccc...,73.81,Mus musculus
2362,CHEMBL1090488,C[C@H]1CN(C(=O)[C@@H]2CN(C(C)(C)C)C[C@H]2c2ccc...,81.01,Rattus norvegicus

C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1ccc(Cl)cc1

,Drug_ID,SMILES,Y,Species
24,CHEMBL1689128,C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1cc...,97.38,Canis lupus familiaris
573,CHEMBL1689128,C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1cc...,98.13,Homo sapiens
2392,CHEMBL1689128,C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1cc...,96.17,Rattus norvegicus

C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
1892,CHEMBL1689127,C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1cc...,97.13,Homo sapiens
2166,CHEMBL1689127,C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1cc...,90.72,Rattus norvegicus

C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1ccccc1

,Drug_ID,SMILES,Y,Species
236,CHEMBL1689126,C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1cc...,92.16,Canis lupus familiaris
1323,CHEMBL1689126,C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1cc...,97.38,Homo sapiens
2174,CHEMBL1689126,C[C@H]1CN(Cc2cc(Cl)ccc2OCC(=O)O)CCN1C(=O)Cc1cc...,89.05,Rattus norvegicus

C[C@H]1CN(Cc2nnc(-c3cc(-c4cccc5[nH]ccc45)cc4[nH]ncc34)o2)C[C@@H](C)O1

,Drug_ID,SMILES,Y,Species
1633,CHEMBL2216839,C[C@H]1CN(Cc2nnc(-c3cc(-c4cccc5[nH]ccc45)cc4[n...,98.09,Homo sapiens
2731,CHEMBL2216839,C[C@H]1CN(Cc2nnc(-c3cc(-c4cccc5[nH]ccc45)cc4[n...,96.87,Rattus norvegicus

C[C@H]1CN(c2cc(N(CCO)Cc3cccc4ccccc34)[nH]c(=O)n2)CCO1

,Drug_ID,SMILES,Y,Species
12,CHEMBL2165189,C[C@H]1CN(c2cc(N(CCO)Cc3cccc4ccccc34)[nH]c(=O)...,70.10,Canis lupus familiaris
1042,CHEMBL2165189,C[C@H]1CN(c2cc(N(CCO)Cc3cccc4ccccc34)[nH]c(=O)...,84.00,Homo sapiens
2635,CHEMBL2165189,C[C@H]1CN(c2cc(N(CCO)Cc3cccc4ccccc34)[nH]c(=O)...,90.52,Rattus norvegicus

C[C@]12CC[C@H]3[C@@H](C=CC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@@]21CCC(=O)O1

,Drug_ID,SMILES,Y,Species
399,CHEMBL1463345,C[C@]12CC[C@H]3[C@@H](C=CC4=CC(=O)CC[C@@]43C)[...,94.06,Homo sapiens
2487,CHEMBL1463345,C[C@]12CC[C@H]3[C@@H](C=CC4=CC(=O)CC[C@@]43C)[...,96.17,Rattus norvegicus

C[C@]12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC[C@@]2(O)CCc1ccc(F)cc1C(N)=O

,Drug_ID,SMILES,Y,Species
645,CHEMBL2147569,C[C@]12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC[C@@]2(O)CC...,96.79,Homo sapiens
2339,CHEMBL2147569,C[C@]12Cc3cnn(-c4ccc(F)cc4)c3C=C1CC[C@@]2(O)CC...,99.54,Rattus norvegicus

C[N+](C)(Cc1ccc(NC(=O)c2ccc(Cl)c(Cl)c2)cc1)C1CCOCC1

,Drug_ID,SMILES,Y,Species
693,CHEMBL397647,C[N+](C)(Cc1ccc(NC(=O)c2ccc(Cl)c(Cl)c2)cc1)C1C...,82.05,Homo sapiens
2546,CHEMBL397647,C[N+](C)(Cc1ccc(NC(=O)c2ccc(Cl)c(Cl)c2)cc1)C1C...,61.31,Rattus norvegicus

C[N+]1(C)CCC(OC(=O)C(O)(c2ccccc2)C2CCCC2)C1

,Drug_ID,SMILES,Y,Species
268,CHEMBL1201335,C[N+]1(C)CCC(OC(=O)C(O)(c2ccccc2)C2CCCC2)C1,20.83,Cavia porcellus
985,CHEMBL1201335,C[N+]1(C)CCC(OC(=O)C(O)(c2ccccc2)C2CCCC2)C1,28.95,Homo sapiens
2418,CHEMBL1201335,C[N+]1(C)CCC(OC(=O)C(O)(c2ccccc2)C2CCCC2)C1,31.87,Rattus norvegicus

C[N+]1(C)[C@H]2C[C@H](OC(=O)C(O)(c3cccs3)c3cccs3)C[C@@H]1[C@H]1O[C@@H]21

,Drug_ID,SMILES,Y,Species
138,CHEMBL1900528,C[N+]1(C)[C@H]2C[C@H](OC(=O)C(O)(c3cccs3)c3ccc...,19.35,Canis lupus familiaris
283,CHEMBL1900528,C[N+]1(C)[C@H]2C[C@H](OC(=O)C(O)(c3cccs3)c3ccc...,38.69,Cavia porcellus
551,CHEMBL1900528,C[N+]1(C)[C@H]2C[C@H](OC(=O)C(O)(c3cccs3)c3ccc...,47.70,Homo sapiens
2645,CHEMBL1900528,C[N+]1(C)[C@H]2C[C@H](OC(=O)C(O)(c3cccs3)c3ccc...,47.70,Rattus norvegicus

C[S+]([O-])Cc1ccc(C(=O)Nc2ccc(OCCOCCO)nc2C(=O)NCC2CCC2)c2ccccc12

,Drug_ID,SMILES,Y,Species
70,CHEMBL2316386,C[S+]([O-])Cc1ccc(C(=O)Nc2ccc(OCCOCCO)nc2C(=O)...,94.19,Canis lupus familiaris
383,CHEMBL2316386,C[S+]([O-])Cc1ccc(C(=O)Nc2ccc(OCCOCCO)nc2C(=O)...,95.01,Homo sapiens
2263,CHEMBL2316386,C[S+]([O-])Cc1ccc(C(=O)Nc2ccc(OCCOCCO)nc2C(=O)...,96.57,Rattus norvegicus

C[S+]([O-])Cc1ccc(C(=O)Nc2cccnc2C(=O)NCC2CCC2)c2ccccc12

,Drug_ID,SMILES,Y,Species
1150,CHEMBL2316109,C[S+]([O-])Cc1ccc(C(=O)Nc2cccnc2C(=O)NCC2CCC2)...,98.70,Homo sapiens
2686,CHEMBL2316109,C[S+]([O-])Cc1ccc(C(=O)Nc2cccnc2C(=O)NCC2CCC2)...,98.81,Rattus norvegicus

Cc1[nH]c(C(=O)NC2CCN(c3ncc(C(=O)O)s3)CC2)c(Cl)c1Cl

,Drug_ID,SMILES,Y,Species
1384,CHEMBL1923433,Cc1[nH]c(C(=O)NC2CCN(c3ncc(C(=O)O)s3)CC2)c(Cl)...,97.07,Homo sapiens
1968,CHEMBL1923433,Cc1[nH]c(C(=O)NC2CCN(c3ncc(C(=O)O)s3)CC2)c(Cl)...,80.29,Mus musculus

Cc1c(CC(=O)O)c2cc(F)ccc2n1S(=O)(=O)c1ccc(S(C)(=O)=O)cc1

,Drug_ID,SMILES,Y,Species
237,CHEMBL196707,Cc1c(CC(=O)O)c2cc(F)ccc2n1S(=O)(=O)c1ccc(S(C)(...,94.79,Canis lupus familiaris
849,CHEMBL196707,Cc1c(CC(=O)O)c2cc(F)ccc2n1S(=O)(=O)c1ccc(S(C)(...,92.32,Homo sapiens

Cc1c(Cc2ccc3ccccc3n2)c2cc(F)ccc2n1CC(=O)O

,Drug_ID,SMILES,Y,Species
38,CHEMBL560993,Cc1c(Cc2ccc3ccccc3n2)c2cc(F)ccc2n1CC(=O)O,98.86,Canis lupus familiaris
298,CHEMBL560993,Cc1c(Cc2ccc3ccccc3n2)c2cc(F)ccc2n1CC(=O)O,98.76,Cavia porcellus
1745,CHEMBL560993,Cc1c(Cc2ccc3ccccc3n2)c2cc(F)ccc2n1CC(=O)O,99.36,Homo sapiens
2220,CHEMBL560993,Cc1c(Cc2ccc3ccccc3n2)c2cc(F)ccc2n1CC(=O)O,99.64,Rattus norvegicus

Cc1c(Cl)ccc(OC2CCN(CC3CCN([C@@H](Cc4ccc(F)cc4)C(=O)O)CC3)CC2)c1Cl

,Drug_ID,SMILES,Y,Species
395,CHEMBL2158783,Cc1c(Cl)ccc(OC2CCN(CC3CCN([C@@H](Cc4ccc(F)cc4)...,96.26,Homo sapiens
2213,CHEMBL2158783,Cc1c(Cl)ccc(OC2CCN(CC3CCN([C@@H](Cc4ccc(F)cc4)...,76.81,Rattus norvegicus

Cc1c(F)cc(C(=O)NC2CC2)cc1-c1ccc(C(=O)NCC(C)(C)C)cn1

,Drug_ID,SMILES,Y,Species
855,CHEMBL1088752,Cc1c(F)cc(C(=O)NC2CC2)cc1-c1ccc(C(=O)NCC(C)(C)...,88.11,Homo sapiens
2561,CHEMBL1088752,Cc1c(F)cc(C(=O)NC2CC2)cc1-c1ccc(C(=O)NCC(C)(C)...,91.82,Rattus norvegicus

Cc1c(OC2CCN(CC3CCN([C@@H](Cc4ccc(F)cc4)C(=O)O)CC3)CC2)ccc(C#N)c1Cl

,Drug_ID,SMILES,Y,Species
984,CHEMBL2158785,Cc1c(OC2CCN(CC3CCN([C@@H](Cc4ccc(F)cc4)C(=O)O)...,94.06,Homo sapiens
2442,CHEMBL2158785,Cc1c(OC2CCN(CC3CCN([C@@H](Cc4ccc(F)cc4)C(=O)O)...,52.30,Rattus norvegicus

Cc1c(OC2CCN(CC3CCN([C@@](C)(Cc4ccc(F)cc4)C(=O)O)CC3)CC2)ccc(Cl)c1Cl

,Drug_ID,SMILES,Y,Species
180,CHEMBL2158790,Cc1c(OC2CCN(CC3CCN([C@@](C)(Cc4ccc(F)cc4)C(=O)...,94.32,Canis lupus familiaris
933,CHEMBL2158790,Cc1c(OC2CCN(CC3CCN([C@@](C)(Cc4ccc(F)cc4)C(=O)...,96.79,Homo sapiens
2694,CHEMBL2158790,Cc1c(OC2CCN(CC3CCN([C@@](C)(Cc4ccc(F)cc4)C(=O)...,92.48,Rattus norvegicus

Cc1c(Sc2ccc(Cl)cc2)c2c(-c3cnccn3)cccc2n1CC(=O)O

,Drug_ID,SMILES,Y,Species
452,CHEMBL1917440,Cc1c(Sc2ccc(Cl)cc2)c2c(-c3cnccn3)cccc2n1CC(=O)O,98.76,Homo sapiens
2209,CHEMBL1917440,Cc1c(Sc2ccc(Cl)cc2)c2c(-c3cnccn3)cccc2n1CC(=O)O,97.60,Rattus norvegicus

Cc1c(Sc2ccc(Cl)cc2)c2c(NS(C)(=O)=O)cccc2n1CC(=O)O

,Drug_ID,SMILES,Y,Species
1061,CHEMBL1917433,Cc1c(Sc2ccc(Cl)cc2)c2c(NS(C)(=O)=O)cccc2n1CC(=O)O,98.96,Homo sapiens
2483,CHEMBL1917433,Cc1c(Sc2ccc(Cl)cc2)c2c(NS(C)(=O)=O)cccc2n1CC(=O)O,99.69,Rattus norvegicus

Cc1c(Sc2ccc(Cl)cc2)c2c(S(C)(=O)=O)cccc2n1CC(=O)O

,Drug_ID,SMILES,Y,Species
208,CHEMBL1917432,Cc1c(Sc2ccc(Cl)cc2)c2c(S(C)(=O)=O)cccc2n1CC(=O)O,97.44,Canis lupus familiaris
487,CHEMBL1917432,Cc1c(Sc2ccc(Cl)cc2)c2c(S(C)(=O)=O)cccc2n1CC(=O)O,96.50,Homo sapiens

Cc1c[nH]c(-c2cnc(NCCNc3ccc(C#N)cn3)nc2-c2ccc(Cl)cc2Cl)n1

,Drug_ID,SMILES,Y,Species
1658,CHEMBL412142,Cc1c[nH]c(-c2cnc(NCCNc3ccc(C#N)cn3)nc2-c2ccc(C...,98.13,Homo sapiens
2239,CHEMBL412142,Cc1c[nH]c(-c2cnc(NCCNc3ccc(C#N)cn3)nc2-c2ccc(C...,95.53,Rattus norvegicus

Cc1cc(-c2ccc(-c3nc4ccncc4c(O)c3C#N)cc2)ccn1

,Drug_ID,SMILES,Y,Species
947,CHEMBL1957381,Cc1cc(-c2ccc(-c3nc4ccncc4c(O)c3C#N)cc2)ccn1,99.59,Homo sapiens
1980,CHEMBL1957381,Cc1cc(-c2ccc(-c3nc4ccncc4c(O)c3C#N)cc2)ccn1,98.70,Mus musculus

Cc1cc(-c2ccc(Cl)c(C(=O)NCC3(O)CCCCCC3)c2)nn1C[C@H](O)CN

,Drug_ID,SMILES,Y,Species
367,CHEMBL1852508,Cc1cc(-c2ccc(Cl)c(C(=O)NCC3(O)CCCCCC3)c2)nn1C[...,69.61,Homo sapiens
2513,CHEMBL1852508,Cc1cc(-c2ccc(Cl)c(C(=O)NCC3(O)CCCCCC3)c2)nn1C[...,69.12,Rattus norvegicus

Cc1cc(-n2cnc3ccc(N[C@@H](C)c4ncc(F)cn4)nc32)n[nH]1

,Drug_ID,SMILES,Y,Species
1906,CHEMBL2151320,Cc1cc(-n2cnc3ccc(N[C@@H](C)c4ncc(F)cn4)nc32)n[...,61.31,Homo sapiens
2308,CHEMBL2151320,Cc1cc(-n2cnc3ccc(N[C@@H](C)c4ncc(F)cn4)nc32)n[...,51.73,Rattus norvegicus

Cc1cc(=O)n(-c2ccccc2)n1C

           Drug_ID                    SMILES      Y                 Species
164   CHEMBL277474  Cc1cc(=O)n(-c2ccccc2)n1C  14.52  Canis lupus familiaris
1537  CHEMBL277474  Cc1cc(=O)n(-c2ccccc2)n1C  19.35            Homo sapiens
2368  CHEMBL277474  Cc1cc(=O)n(-c2ccccc2)n1C  29.90       Rattus norvegicus

Cc1cc(C(C)Nc2ccccc2)c2nc(N3CCOCC3)cc(=O)n2c1

,Drug_ID,SMILES,Y,Species
172,CHEMBL1972466,Cc1cc(C(C)Nc2ccccc2)c2nc(N3CCOCC3)cc(=O)n2c1,93.94,Canis lupus familiaris
653,CHEMBL1972466,Cc1cc(C(C)Nc2ccccc2)c2nc(N3CCOCC3)cc(=O)n2c1,94.68,Homo sapiens
2303,CHEMBL1972466,Cc1cc(C(C)Nc2ccccc2)c2nc(N3CCOCC3)cc(=O)n2c1,95.33,Rattus norvegicus

Cc1cc(C)c(C)c(Cn2ccc3c(/C=N/NC(=O)c4ccc(O)c(C#N)c4)cccc32)c1C

,Drug_ID,SMILES,Y,Species
545,CHEMBL152640,Cc1cc(C)c(C)c(Cn2ccc3c(/C=N/NC(=O)c4ccc(O)c(C#...,96.00,Homo sapiens
2203,CHEMBL152640,Cc1cc(C)c(C)c(Cn2ccc3c(/C=N/NC(=O)c4ccc(O)c(C#...,99.68,Rattus norvegicus

Cc1cc(C)c(S(=O)(=O)NCc2ccncc2)c(C)c1

,Drug_ID,SMILES,Y,Species
858,CHEMBL1353474,Cc1cc(C)c(S(=O)(=O)NCc2ccncc2)c(C)c1,86.05,Homo sapiens
2087,CHEMBL1353474,Cc1cc(C)c(S(=O)(=O)NCc2ccncc2)c(C)c1,84.90,Mus musculus
2644,CHEMBL1353474,Cc1cc(C)c(S(=O)(=O)NCc2ccncc2)c(C)c1,86.05,Rattus norvegicus

Cc1cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)cccc32)cn(C)c1=O

,Drug_ID,SMILES,Y,Species
789,CHEMBL2177919,Cc1cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)cccc3...,81.01,Homo sapiens
1972,CHEMBL2177919,Cc1cc(C2(c3cccc(-c4cncnc4)c3)N=C(N)c3c(F)cccc3...,48.27,Mus musculus

Cc1cc(CCC[N+]23CCC(CC2)[C@@H](OC(=O)[C@](C)(c2ccccc2)N2CCCCC2)C3)ccn1

,Drug_ID,SMILES,Y,Species
248,CHEMBL1921919,Cc1cc(CCC[N+]23CCC(CC2)[C@@H](OC(=O)[C@](C)(c2...,47.12,Cavia porcellus
1466,CHEMBL1921919,Cc1cc(CCC[N+]23CCC(CC2)[C@@H](OC(=O)[C@](C)(c2...,23.19,Homo sapiens

Cc1cc(CN2Cc3ccccc3C2C(=O)Nc2ccc(Cl)cc2Cl)ccc1OCC(=O)O

,Drug_ID,SMILES,Y,Species
1246,CHEMBL1643194,Cc1cc(CN2Cc3ccccc3C2C(=O)Nc2ccc(Cl)cc2Cl)ccc1O...,99.87,Homo sapiens
2821,CHEMBL1643194,Cc1cc(CN2Cc3ccccc3C2C(=O)Nc2ccc(Cl)cc2Cl)ccc1O...,99.86,Rattus norvegicus

Cc1cc(F)ccc1-n1nc(C(F)(F)F)cc1-c1ccc2c(c1)NC(=O)CO2

,Drug_ID,SMILES,Y,Species
1368,CHEMBL1929039,Cc1cc(F)ccc1-n1nc(C(F)(F)F)cc1-c1ccc2c(c1)NC(=...,73.81,Homo sapiens
2767,CHEMBL1929039,Cc1cc(F)ccc1-n1nc(C(F)(F)F)cc1-c1ccc2c(c1)NC(=...,81.01,Rattus norvegicus

Cc1cc(F)ccc1OC1CCN(CC2CCN([C@@](C)(Cc3ccc(F)cc3)C(=O)O)CC2)CC1

,Drug_ID,SMILES,Y,Species
131,CHEMBL2158793,Cc1cc(F)ccc1OC1CCN(CC2CCN([C@@](C)(Cc3ccc(F)cc...,49.42,Canis lupus familiaris
1081,CHEMBL2158793,Cc1cc(F)ccc1OC1CCN(CC2CCN([C@@](C)(Cc3ccc(F)cc...,53.45,Homo sapiens
2246,CHEMBL2158793,Cc1cc(F)ccc1OC1CCN(CC2CCN([C@@](C)(Cc3ccc(F)cc...,55.16,Rattus norvegicus

Cc1cc(F)ccc1Oc1cccc2c(=O)cc(N3CCOCC3)[nH]c12

,Drug_ID,SMILES,Y,Species
213,CHEMBL2064327,Cc1cc(F)ccc1Oc1cccc2c(=O)cc(N3CCOCC3)[nH]c12,99.12,Canis lupus familiaris
1200,CHEMBL2064327,Cc1cc(F)ccc1Oc1cccc2c(=O)cc(N3CCOCC3)[nH]c12,98.81,Homo sapiens
2716,CHEMBL2064327,Cc1cc(F)ccc1Oc1cccc2c(=O)cc(N3CCOCC3)[nH]c12,91.46,Rattus norvegicus

Cc1cc(I)cc2c1NC(C(=O)O)C1CC=CC21

            Drug_ID                            SMILES     Y            Species
1563  CHEMBL1454310  Cc1cc(I)cc2c1NC(C(=O)O)C1CC=CC21  99.8       Homo sapiens
2430  CHEMBL1454310  Cc1cc(I)cc2c1NC(C(=O)O)C1CC=CC21  99.3  Rattus norvegicus

Cc1cc(N2CCC[C@@H]2C(=O)NCCc2ccc3c(c2)OCO3)nc(-n2ccnc2)n1

,Drug_ID,SMILES,Y,Species
1101,CHEMBL376632,Cc1cc(N2CCC[C@@H]2C(=O)NCCc2ccc3c(c2)OCO3)nc(-...,81.01,Homo sapiens
2080,CHEMBL376632,Cc1cc(N2CCC[C@@H]2C(=O)NCCc2ccc3c(c2)OCO3)nc(-...,84.60,Mus musculus
2422,CHEMBL376632,Cc1cc(N2CCC[C@@H]2C(=O)NCCc2ccc3c(c2)OCO3)nc(-...,78.01,Rattus norvegicus

Cc1cc(Nc2cnc(C#N)c(N[C@@H](C)c3ccc(F)cn3)n2)n[nH]1

,Drug_ID,SMILES,Y,Species
36,CHEMBL576257,Cc1cc(Nc2cnc(C#N)c(N[C@@H](C)c3ccc(F)cn3)n2)n[...,79.55,Canis lupus familiaris
901,CHEMBL576257,Cc1cc(Nc2cnc(C#N)c(N[C@@H](C)c3ccc(F)cn3)n2)n[...,85.48,Homo sapiens
2701,CHEMBL576257,Cc1cc(Nc2cnc(C#N)c(N[C@@H](C)c3ccc(F)cn3)n2)n[...,84.00,Rattus norvegicus

Cc1cc(Nc2cnc(C#N)c(N[C@@H](C)c3ncc(F)cn3)n2)n[nH]1

,Drug_ID,SMILES,Y,Species
95,CHEMBL570002,Cc1cc(Nc2cnc(C#N)c(N[C@@H](C)c3ncc(F)cn3)n2)n[...,60.22,Canis lupus familiaris
410,CHEMBL570002,Cc1cc(Nc2cnc(C#N)c(N[C@@H](C)c3ncc(F)cn3)n2)n[...,81.36,Homo sapiens
2363,CHEMBL570002,Cc1cc(Nc2cnc(C#N)c(N[C@@H](C)c3ncc(F)cn3)n2)n[...,62.40,Rattus norvegicus

Cc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cn3)c(C#N)nc2C)n[nH]1

,Drug_ID,SMILES,Y,Species
166,CHEMBL578201,Cc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cn3)c(C#N)nc2C)n...,73.81,Canis lupus familiaris
1197,CHEMBL578201,Cc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cn3)c(C#N)nc2C)n...,82.72,Homo sapiens
2693,CHEMBL578201,Cc1cc(Nc2nc(N[C@@H](C)c3ccc(F)cn3)c(C#N)nc2C)n...,81.01,Rattus norvegicus

Cc1cc(Nc2nc(N[C@@H](C)c3ncc(F)cn3)c(C#N)nc2C)n[nH]1

,Drug_ID,SMILES,Y,Species
150,CHEMBL569720,Cc1cc(Nc2nc(N[C@@H](C)c3ncc(F)cn3)c(C#N)nc2C)n...,54.59,Canis lupus familiaris
1575,CHEMBL569720,Cc1cc(Nc2nc(N[C@@H](C)c3ncc(F)cn3)c(C#N)nc2C)n...,69.61,Homo sapiens
2242,CHEMBL569720,Cc1cc(Nc2nc(N[C@@H](C)c3ncc(F)cn3)c(C#N)nc2C)n...,65.06,Rattus norvegicus

Cc1cc(Nc2nc(O[C@@H](C)c3ncc(F)cn3)ncc2Cl)n[nH]1

,Drug_ID,SMILES,Y,Species
153,CHEMBL1650726,Cc1cc(Nc2nc(O[C@@H](C)c3ncc(F)cn3)ncc2Cl)n[nH]1,51.15,Canis lupus familiaris
664,CHEMBL1650726,Cc1cc(Nc2nc(O[C@@H](C)c3ncc(F)cn3)ncc2Cl)n[nH]1,75.12,Homo sapiens
2136,CHEMBL1650726,Cc1cc(Nc2nc(O[C@@H](C)c3ncc(F)cn3)ncc2Cl)n[nH]1,66.10,Rattus norvegicus

Cc1cc(OC2CCN(CC3CCN([C@@](C)(Cc4ccc(F)cc4)C(=O)O)CC3)CC2)ccc1Cl

,Drug_ID,SMILES,Y,Species
182,CHEMBL2158792,Cc1cc(OC2CCN(CC3CCN([C@@](C)(Cc4ccc(F)cc4)C(=O...,71.53,Canis lupus familiaris
388,CHEMBL2158792,Cc1cc(OC2CCN(CC3CCN([C@@](C)(Cc4ccc(F)cc4)C(=O...,78.79,Homo sapiens
2149,CHEMBL2158792,Cc1cc(OC2CCN(CC3CCN([C@@](C)(Cc4ccc(F)cc4)C(=O...,73.36,Rattus norvegicus

Cc1cc(Oc2ncc(C(F)(F)F)cc2Cl)ccc1CC1SC(=O)NC1=O

,Drug_ID,SMILES,Y,Species
1005,CHEMBL604126,Cc1cc(Oc2ncc(C(F)(F)F)cc2Cl)ccc1CC1SC(=O)NC1=O,99.94,Homo sapiens
2190,CHEMBL604126,Cc1cc(Oc2ncc(C(F)(F)F)cc2Cl)ccc1CC1SC(=O)NC1=O,99.79,Rattus norvegicus

Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1

        Drug_ID                               SMILES      Y            Species
1104  CHEMBL715  Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1  89.27       Homo sapiens
2809  CHEMBL715  Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1  87.62  Rattus norvegicus

Cc1ccc(-c2ccc3c(ccc4sc5c(c43)NC[C@@H](C)NC5=O)n2)cn1

,Drug_ID,SMILES,Y,Species
723,CHEMBL1231206,Cc1ccc(-c2ccc3c(ccc4sc5c(c43)NC[C@@H](C)NC5=O)...,84.90,Homo sapiens
2076,CHEMBL1231206,Cc1ccc(-c2ccc3c(ccc4sc5c(c43)NC[C@@H](C)NC5=O)...,97.71,Mus musculus
2164,CHEMBL1231206,Cc1ccc(-c2ccc3c(ccc4sc5c(c43)NC[C@@H](C)NC5=O)...,98.86,Rattus norvegicus

Cc1ccc(-c2ncc[nH]2)cc1NC(=O)c1ccc(OCc2ccccn2)cc1

,Drug_ID,SMILES,Y,Species
210,CHEMBL2059865,Cc1ccc(-c2ncc[nH]2)cc1NC(=O)c1ccc(OCc2ccccn2)cc1,86.59,Canis lupus familiaris
1747,CHEMBL2059865,Cc1ccc(-c2ncc[nH]2)cc1NC(=O)c1ccc(OCc2ccccn2)cc1,94.06,Homo sapiens

Cc1ccc(C(=O)c2ccc(CC(=O)O)n2C)cc1

,Drug_ID,SMILES,Y,Species
176,CHEMBL1020,Cc1ccc(C(=O)c2ccc(CC(=O)O)n2C)cc1,95.23,Canis lupus familiaris
760,CHEMBL1020,Cc1ccc(C(=O)c2ccc(CC(=O)O)n2C)cc1,99.72,Homo sapiens
2128,CHEMBL1020,Cc1ccc(C(=O)c2ccc(CC(=O)O)n2C)cc1,97.13,Rattus norvegicus

Cc1ccc(C(NC(=O)c2ccccc2O)C(=O)Nc2c(C)cccc2C)s1

,Drug_ID,SMILES,Y,Species
1738,CHEMBL1770298,Cc1ccc(C(NC(=O)c2ccccc2O)C(=O)Nc2c(C)cccc2C)s1,99.57,Homo sapiens
2557,CHEMBL1770298,Cc1ccc(C(NC(=O)c2ccccc2O)C(=O)Nc2c(C)cccc2C)s1,99.25,Rattus norvegicus

Cc1ccc(C)c(OCCCC(C)(C)C(=O)O)c1

        Drug_ID                           SMILES      Y            Species
1467  CHEMBL457  Cc1ccc(C)c(OCCCC(C)(C)C(=O)O)c1  99.77       Homo sapiens
2747  CHEMBL457  Cc1ccc(C)c(OCCCC(C)(C)C(=O)O)c1  98.47  Rattus norvegicus

Cc1ccc(N2CC(COc3ccc(-c4noc(C)n4)cc3)C2)nn1

,Drug_ID,SMILES,Y,Species
1093,CHEMBL1835918,Cc1ccc(N2CC(COc3ccc(-c4noc(C)n4)cc3)C2)nn1,93.80,Homo sapiens
2312,CHEMBL1835918,Cc1ccc(N2CC(COc3ccc(-c4noc(C)n4)cc3)C2)nn1,95.12,Rattus norvegicus

Cc1ccc(NC(=O)Nc2nnc(-c3ccncc3)s2)cc1

,Drug_ID,SMILES,Y,Species
1241,CHEMBL1359986,Cc1ccc(NC(=O)Nc2nnc(-c3ccncc3)s2)cc1,99.39,Homo sapiens
2601,CHEMBL1359986,Cc1ccc(NC(=O)Nc2nnc(-c3ccncc3)s2)cc1,99.36,Rattus norvegicus

Cc1ccc(NC(=O)c2ccc(CN3CCN(C)CC3)cc2)cc1Nc1nccc(-c2cccnc2)n1

,Drug_ID,SMILES,Y,Species
479,CHEMBL941,Cc1ccc(NC(=O)c2ccc(CN3CCN(C)CC3)cc2)cc1Nc1nccc...,93.67,Homo sapiens
2480,CHEMBL941,Cc1ccc(NC(=O)c2ccc(CN3CCN(C)CC3)cc2)cc1Nc1nccc...,97.20,Rattus norvegicus

Cc1ccc(NC(=O)c2cccc(C(C)(C)C#N)c2)cc1Nc1ccc2ncn(C)c(=O)c2c1

,Drug_ID,SMILES,Y,Species
230,CHEMBL2144069,Cc1ccc(NC(=O)c2cccc(C(C)(C)C#N)c2)cc1Nc1ccc2nc...,99.60,Canis lupus familiaris
1772,CHEMBL2144069,Cc1ccc(NC(=O)c2cccc(C(C)(C)C#N)c2)cc1Nc1ccc2nc...,99.61,Homo sapiens
2201,CHEMBL2144069,Cc1ccc(NC(=O)c2cccc(C(C)(C)C#N)c2)cc1Nc1ccc2nc...,50.00,Rattus norvegicus

Cc1ccc(S(=O)(=O)N(C)c2ccc3sc(C)nc3c2)cc1

,Drug_ID,SMILES,Y,Species
961,CHEMBL1528356,Cc1ccc(S(=O)(=O)N(C)c2ccc3sc(C)nc3c2)cc1,99.26,Homo sapiens
2348,CHEMBL1528356,Cc1ccc(S(=O)(=O)N(C)c2ccc3sc(C)nc3c2)cc1,99.33,Rattus norvegicus

Cc1ccc(S(=O)(=O)NCCSc2nnnn2-c2ccc(C(N)=O)cc2)cc1

,Drug_ID,SMILES,Y,Species
768,CHEMBL1450473,Cc1ccc(S(=O)(=O)NCCSc2nnnn2-c2ccc(C(N)=O)cc2)cc1,89.91,Homo sapiens
2768,CHEMBL1450473,Cc1ccc(S(=O)(=O)NCCSc2nnnn2-c2ccc(C(N)=O)cc2)cc1,81.01,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N(C)C3CCCCC3)cnn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
819,CHEMBL1916085,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N(C)C3CCCCC3)cnn2-c2...,98.29,Homo sapiens
2111,CHEMBL1916085,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N(C)C3CCCCC3)cnn2-c2...,98.13,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC(C)C(C)(C)C)c(C)nn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
1866,CHEMBL1916281,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC(C)C(C)(C)C)c(C)nn...,98.73,Homo sapiens
2743,CHEMBL1916281,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC(C)C(C)(C)C)c(C)nn...,95.43,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCCCC3)c(C)nn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
1244,CHEMBL1916274,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCCCC3)c(C)nn2-c2...,99.86,Homo sapiens
2241,CHEMBL1916274,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCCCC3)c(C)nn2-c2...,97.86,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCCCC3C)c(C)nn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
1454,CHEMBL1916277,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCCCC3C)c(C)nn2-c...,99.34,Homo sapiens
2494,CHEMBL1916277,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCCCC3C)c(C)nn2-c...,97.76,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCOCC3)c(C)nn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
416,CHEMBL1916278,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCOCC3)c(C)nn2-c2...,97.38,Homo sapiens
2804,CHEMBL1916278,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NC3CCOCC3)c(C)nn2-c2...,91.10,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)NCC(C)(C)C)c(C)nn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
963,CHEMBL1916279,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NCC(C)(C)C)c(C)nn2-c...,99.18,Homo sapiens
2264,CHEMBL1916279,Cc1ccc(S(=O)(=O)Nc2c(C(=O)NCC(C)(C)C)c(C)nn2-c...,96.65,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C(F)(F)F)nn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
1147,CHEMBL1916284,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,99.57,Homo sapiens
2554,CHEMBL1916284,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,99.03,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
26,CHEMBL1916282,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,96.79,Canis lupus familiaris
255,CHEMBL1916282,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,91.82,Cavia porcellus
494,CHEMBL1916282,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,98.89,Homo sapiens
2517,CHEMBL1916282,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,95.82,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2C(C)C)cc1

,Drug_ID,SMILES,Y,Species
226,CHEMBL1934267,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,92.64,Canis lupus familiaris
244,CHEMBL1934267,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,72.91,Cavia porcellus
1280,CHEMBL1934267,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,95.43,Homo sapiens
2372,CHEMBL1934267,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,95.82,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2C2CCC2)cc1

,Drug_ID,SMILES,Y,Species
1427,CHEMBL1934413,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,98.17,Homo sapiens
2243,CHEMBL1934413,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,97.91,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2C2CCCC2)cc1

,Drug_ID,SMILES,Y,Species
1694,CHEMBL1934414,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,97.86,Homo sapiens
2827,CHEMBL1934414,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,97.32,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2C2CCCCC2)cc1

,Drug_ID,SMILES,Y,Species
1375,CHEMBL1934415,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,97.76,Homo sapiens
2327,CHEMBL1934415,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,96.34,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2C2CCOCC2)cc1

,Drug_ID,SMILES,Y,Species
73,CHEMBL1934422,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,47.12,Canis lupus familiaris
979,CHEMBL1934422,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,79.17,Homo sapiens
2315,CHEMBL1934422,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,83.37,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2C2CCS(=O)(=O)CC2)cc1

,Drug_ID,SMILES,Y,Species
1872,CHEMBL1934419,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,79.17,Homo sapiens
2394,CHEMBL1934419,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,74.25,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2C2CCSCC2)cc1

,Drug_ID,SMILES,Y,Species
634,CHEMBL1934418,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,94.68,Homo sapiens
2511,CHEMBL1934418,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,93.39,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c(C)nn2CC(F)(F)F)cc1

,Drug_ID,SMILES,Y,Species
1234,CHEMBL1934269,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,98.58,Homo sapiens
2461,CHEMBL1934269,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@@H](C)C(C)(C)C)c...,97.26,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@H](C)C(C)(C)C)c(C)nn2-c2ccccc2)cc1

,Drug_ID,SMILES,Y,Species
1140,CHEMBL1916283,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@H](C)C(C)(C)C)c(...,99.19,Homo sapiens
2326,CHEMBL1916283,Cc1ccc(S(=O)(=O)Nc2c(C(=O)N[C@H](C)C(C)(C)C)c(...,96.26,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2ccc3nc(C)oc3c2)cc1

,Drug_ID,SMILES,Y,Species
455,CHEMBL1724416,Cc1ccc(S(=O)(=O)Nc2ccc3nc(C)oc3c2)cc1,97.91,Homo sapiens
2323,CHEMBL1724416,Cc1ccc(S(=O)(=O)Nc2ccc3nc(C)oc3c2)cc1,94.90,Rattus norvegicus

Cc1ccc(S(=O)(=O)Nc2ccc3nc(C)sc3c2)cc1

,Drug_ID,SMILES,Y,Species
1488,CHEMBL1503948,Cc1ccc(S(=O)(=O)Nc2ccc3nc(C)sc3c2)cc1,99.79,Homo sapiens
2677,CHEMBL1503948,Cc1ccc(S(=O)(=O)Nc2ccc3nc(C)sc3c2)cc1,99.47,Rattus norvegicus

Cc1ccc(Sc2ccccc2CN(C)C)c(N)c1

          Drug_ID                         SMILES      Y            Species
1106  CHEMBL22183  Cc1ccc(Sc2ccccc2CN(C)C)c(N)c1  89.05       Homo sapiens
2182  CHEMBL22183  Cc1ccc(Sc2ccccc2CN(C)C)c(N)c1  90.72  Rattus norvegicus

Cc1ccc2c(OCCN3CCC(Cc4cccc(NS(C)(=O)=O)c4)CC3)cccc2n1

,Drug_ID,SMILES,Y,Species
328,CHEMBL497963,Cc1ccc2c(OCCN3CCC(Cc4cccc(NS(C)(=O)=O)c4)CC3)c...,95.63,Cavia porcellus
696,CHEMBL497963,Cc1ccc2c(OCCN3CCC(Cc4cccc(NS(C)(=O)=O)c4)CC3)c...,97.00,Homo sapiens
2790,CHEMBL497963,Cc1ccc2c(OCCN3CCC(Cc4cccc(NS(C)(=O)=O)c4)CC3)c...,94.68,Rattus norvegicus

Cc1ccc2c(c1)c(-c1cc(C)nc3ccccc13)c(C)n2CC(=O)O

,Drug_ID,SMILES,Y,Species
63,CHEMBL211677,Cc1ccc2c(c1)c(-c1cc(C)nc3ccccc13)c(C)n2CC(=O)O,98.67,Canis lupus familiaris
799,CHEMBL211677,Cc1ccc2c(c1)c(-c1cc(C)nc3ccccc13)c(C)n2CC(=O)O,99.60,Homo sapiens

Cc1ccc2c(c1)c(-c1ccnc3c(C)cccc13)c(C)n2CC(=O)O

,Drug_ID,SMILES,Y,Species
14,CHEMBL209689,Cc1ccc2c(c1)c(-c1ccnc3c(C)cccc13)c(C)n2CC(=O)O,99.48,Canis lupus familiaris
1849,CHEMBL209689,Cc1ccc2c(c1)c(-c1ccnc3c(C)cccc13)c(C)n2CC(=O)O,99.51,Homo sapiens

Cc1ccc2c(c1)c(-c1ccnc3c(Cl)cccc13)c(C)n2CC(=O)O

,Drug_ID,SMILES,Y,Species
23,CHEMBL378730,Cc1ccc2c(c1)c(-c1ccnc3c(Cl)cccc13)c(C)n2CC(=O)O,99.59,Canis lupus familiaris
1696,CHEMBL378730,Cc1ccc2c(c1)c(-c1ccnc3c(Cl)cccc13)c(C)n2CC(=O)O,99.44,Homo sapiens
2068,CHEMBL378730,Cc1ccc2c(c1)c(-c1ccnc3c(Cl)cccc13)c(C)n2CC(=O)O,97.71,Mus musculus
2556,CHEMBL378730,Cc1ccc2c(c1)c(-c1ccnc3c(Cl)cccc13)c(C)n2CC(=O)O,99.23,Rattus norvegicus

Cc1ccc2c(c1)c(-c1ccnc3cc(Cl)ccc13)c(C)n2CC(=O)O

,Drug_ID,SMILES,Y,Species
51,CHEMBL212777,Cc1ccc2c(c1)c(-c1ccnc3cc(Cl)ccc13)c(C)n2CC(=O)O,99.65,Canis lupus familiaris
629,CHEMBL212777,Cc1ccc2c(c1)c(-c1ccnc3cc(Cl)ccc13)c(C)n2CC(=O)O,99.82,Homo sapiens

Cc1ccc2c(c1)c(S(=O)(=O)c1ccc(Cl)cc1)c(C)n2CC(=O)O

,Drug_ID,SMILES,Y,Species
44,CHEMBL1917446,Cc1ccc2c(c1)c(S(=O)(=O)c1ccc(Cl)cc1)c(C)n2CC(=O)O,98.33,Canis lupus familiaris
366,CHEMBL1917446,Cc1ccc2c(c1)c(S(=O)(=O)c1ccc(Cl)cc1)c(C)n2CC(=O)O,99.48,Homo sapiens

Cc1cccc([C@H](C)c2c[nH]c(=S)[nH]2)c1C

,Drug_ID,SMILES,Y,Species
1576,CHEMBL2107366,Cc1cccc([C@H](C)c2c[nH]c(=S)[nH]2)c1C,83.04,Homo sapiens
2592,CHEMBL2107366,Cc1cccc([C@H](C)c2c[nH]c(=S)[nH]2)c1C,81.01,Rattus norvegicus

Cc1ccccc1-n1c(Cn2cnc3c(N)ncnc32)nc2cccc(C)c2c1=O

,Drug_ID,SMILES,Y,Species
668,CHEMBL1213082,Cc1ccccc1-n1c(Cn2cnc3c(N)ncnc32)nc2cccc(C)c2c1=O,98.64,Homo sapiens
2058,CHEMBL1213082,Cc1ccccc1-n1c(Cn2cnc3c(N)ncnc32)nc2cccc(C)c2c1=O,91.99,Mus musculus
2282,CHEMBL1213082,Cc1ccccc1-n1c(Cn2cnc3c(N)ncnc32)nc2cccc(C)c2c1=O,75.97,Rattus norvegicus

Cc1ccccc1-n1c(Cn2nc(-c3ccc(O)c(F)c3)c3c(N)ncnc32)nc2cccc(C)c2c1=O

,Drug_ID,SMILES,Y,Species
1758,CHEMBL1213085,Cc1ccccc1-n1c(Cn2nc(-c3ccc(O)c(F)c3)c3c(N)ncnc...,98.00,Homo sapiens
2300,CHEMBL1213085,Cc1ccccc1-n1c(Cn2nc(-c3ccc(O)c(F)c3)c3c(N)ncnc...,96.87,Rattus norvegicus

Cc1ccccc1CN1CCC(N2CCC(n3c(=O)[nH]c4ccccc43)CC2)CC1

,Drug_ID,SMILES,Y,Species
1515,CHEMBL522460,Cc1ccccc1CN1CCC(N2CCC(n3c(=O)[nH]c4ccccc43)CC2...,64.54,Homo sapiens
2293,CHEMBL522460,Cc1ccccc1CN1CCC(N2CCC(n3c(=O)[nH]c4ccccc43)CC2...,70.10,Rattus norvegicus

Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(Cl)c(Cl)c3)CC2)CC1

,Drug_ID,SMILES,Y,Species
188,CHEMBL2158772,Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(Cl...,99.60,Canis lupus familiaris
277,CHEMBL2158772,Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(Cl...,82.39,Cavia porcellus
1228,CHEMBL2158772,Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(Cl...,91.64,Homo sapiens
2633,CHEMBL2158772,Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(Cl...,88.82,Rattus norvegicus

Cc1ccsc1C(=CCCN1CCC[C@@H](C(=O)O)C1)c1sccc1C

,Drug_ID,SMILES,Y,Species
1786,CHEMBL1027,Cc1ccsc1C(=CCCN1CCC[C@@H](C(=O)O)C1)c1sccc1C,94.90,Homo sapiens
2717,CHEMBL1027,Cc1ccsc1C(=CCCN1CCC[C@@H](C(=O)O)C1)c1sccc1C,91.64,Rattus norvegicus

Cc1cn([C@H]2CCCN([C@@H](C)c3ccc(C(=O)O)c(Oc4cccc(Cl)c4)c3)C2)c(=O)[nH]c1=O

,Drug_ID,SMILES,Y,Species
134,CHEMBL2179270,Cc1cn([C@H]2CCCN([C@@H](C)c3ccc(C(=O)O)c(Oc4cc...,94.68,Canis lupus familiaris
1613,CHEMBL2179270,Cc1cn([C@H]2CCCN([C@@H](C)c3ccc(C(=O)O)c(Oc4cc...,97.71,Homo sapiens
2525,CHEMBL2179270,Cc1cn([C@H]2CCCN([C@@H](C)c3ccc(C(=O)O)c(Oc4cc...,97.32,Rattus norvegicus

Cc1cn([C@H]2CCCN([C@@H](CC(C)C)c3ccc(C(=O)O)c(Oc4cccc(Cl)c4)c3)C2)c(=O)[nH]c1=O

,Drug_ID,SMILES,Y,Species
907,CHEMBL2179276,Cc1cn([C@H]2CCCN([C@@H](CC(C)C)c3ccc(C(=O)O)c(...,98.89,Homo sapiens
2256,CHEMBL2179276,Cc1cn([C@H]2CCCN([C@@H](CC(C)C)c3ccc(C(=O)O)c(...,98.40,Rattus norvegicus

Cc1cn([C@H]2CCCN([C@H](C)c3ccc(C(=O)O)c(Oc4cccc(Cl)c4)c3)C2)c(=O)[nH]c1=O

,Drug_ID,SMILES,Y,Species
232,CHEMBL2179269,Cc1cn([C@H]2CCCN([C@H](C)c3ccc(C(=O)O)c(Oc4ccc...,89.91,Canis lupus familiaris
671,CHEMBL2179269,Cc1cn([C@H]2CCCN([C@H](C)c3ccc(C(=O)O)c(Oc4ccc...,98.44,Homo sapiens
2766,CHEMBL2179269,Cc1cn([C@H]2CCCN([C@H](C)c3ccc(C(=O)O)c(Oc4ccc...,97.07,Rattus norvegicus

Cc1cn([C@H]2CCCN([C@H](CC(C)(C)C)c3ccc(C(=O)O)c(Oc4cccc(Br)c4)c3)C2)c(=O)[nH]c1=O

,Drug_ID,SMILES,Y,Species
169,CHEMBL2179277,Cc1cn([C@H]2CCCN([C@H](CC(C)(C)C)c3ccc(C(=O)O)...,97.32,Canis lupus familiaris
1832,CHEMBL2179277,Cc1cn([C@H]2CCCN([C@H](CC(C)(C)C)c3ccc(C(=O)O)...,97.13,Homo sapiens
2786,CHEMBL2179277,Cc1cn([C@H]2CCCN([C@H](CC(C)(C)C)c3ccc(C(=O)O)...,98.51,Rattus norvegicus

Cc1cn([C@H]2CCCN([C@H](CC(C)C)c3ccc(C(=O)O)c(Oc4cccc(Cl)c4)c3)C2)c(=O)[nH]c1=O

,Drug_ID,SMILES,Y,Species
93,CHEMBL2179275,Cc1cn([C@H]2CCCN([C@H](CC(C)C)c3ccc(C(=O)O)c(O...,96.34,Canis lupus familiaris
1828,CHEMBL2179275,Cc1cn([C@H]2CCCN([C@H](CC(C)C)c3ccc(C(=O)O)c(O...,97.26,Homo sapiens
2530,CHEMBL2179275,Cc1cn([C@H]2CCCN([C@H](CC(C)C)c3ccc(C(=O)O)c(O...,98.25,Rattus norvegicus

Cc1cnc(-c2c(F)ccc(F)c2CCNC(=O)c2ccc(COCC(F)(F)F)nc2)cn1

,Drug_ID,SMILES,Y,Species
1376,CHEMBL2147309,Cc1cnc(-c2c(F)ccc(F)c2CCNC(=O)c2ccc(COCC(F)(F)...,91.99,Homo sapiens
2114,CHEMBL2147309,Cc1cnc(-c2c(F)ccc(F)c2CCNC(=O)c2ccc(COCC(F)(F)...,71.99,Rattus norvegicus

Cc1cnc(C(=O)NCCc2ccc(S(=O)(=O)NC(=O)NC3CCCCC3)cc2)cn1

,Drug_ID,SMILES,Y,Species
1353,CHEMBL1073,Cc1cnc(C(=O)NCCc2ccc(S(=O)(=O)NC(=O)NC3CCCCC3)...,99.12,Homo sapiens
2156,CHEMBL1073,Cc1cnc(C(=O)NCCc2ccc(S(=O)(=O)NC(=O)NC3CCCCC3)...,97.76,Rattus norvegicus

Cc1cnc(C(=O)c2ncnc3[nH]ccc23)c(NS(=O)(=O)c2ccc(Cl)c(C(F)(F)F)c2)c1

,Drug_ID,SMILES,Y,Species
1407,CHEMBL2178573,Cc1cnc(C(=O)c2ncnc3[nH]ccc23)c(NS(=O)(=O)c2ccc...,99.91,Homo sapiens
1977,CHEMBL2178573,Cc1cnc(C(=O)c2ncnc3[nH]ccc23)c(NS(=O)(=O)c2ccc...,99.31,Mus musculus
2545,CHEMBL2178573,Cc1cnc(C(=O)c2ncnc3[nH]ccc23)c(NS(=O)(=O)c2ccc...,99.79,Rattus norvegicus

Cc1cnc(Nc2ccc(OCCN3CCCC3)cc2)nc1Nc1cccc(S(=O)(=O)NC(C)(C)C)c1

,Drug_ID,SMILES,Y,Species
122,CHEMBL1287853,Cc1cnc(Nc2ccc(OCCN3CCCC3)cc2)nc1Nc1cccc(S(=O)(...,80.29,Canis lupus familiaris
2825,CHEMBL1287853,Cc1cnc(Nc2ccc(OCCN3CCCC3)cc2)nc1Nc1cccc(S(=O)(...,79.55,Rattus norvegicus

Cc1n[nH]c(C)c1Cc1sc2c(c1C(=O)N1C[C@H](O)CO1)c(=O)n(C)c(=O)n2CC(C)C

,Drug_ID,SMILES,Y,Species
97,CHEMBL375166,Cc1n[nH]c(C)c1Cc1sc2c(c1C(=O)N1C[C@H](O)CO1)c(...,34.42,Canis lupus familiaris
1393,CHEMBL375166,Cc1n[nH]c(C)c1Cc1sc2c(c1C(=O)N1C[C@H](O)CO1)c(...,51.15,Homo sapiens

Cc1nc(-c2c(F)cc(Cl)cc2-c2cnc([C@@H](C)NC(=O)[C@@](C)(O)C(F)(F)F)c(F)c2)no1

,Drug_ID,SMILES,Y,Species
1761,CHEMBL402831,Cc1nc(-c2c(F)cc(Cl)cc2-c2cnc([C@@H](C)NC(=O)[C...,98.00,Homo sapiens
2070,CHEMBL402831,Cc1nc(-c2c(F)cc(Cl)cc2-c2cnc([C@@H](C)NC(=O)[C...,97.49,Mus musculus
2332,CHEMBL402831,Cc1nc(-c2c(F)cc(Cl)cc2-c2cnc([C@@H](C)NC(=O)[C...,96.42,Rattus norvegicus

Cc1nc(C(C)C)c(-c2ccc([C@H]3CC[C@H](CC(=O)O)CC3)cc2)nc1C(N)=O

,Drug_ID,SMILES,Y,Species
1804,CHEMBL2178931,Cc1nc(C(C)C)c(-c2ccc([C@H]3CC[C@H](CC(=O)O)CC3...,97.81,Homo sapiens
2739,CHEMBL2178931,Cc1nc(C(C)C)c(-c2ccc([C@H]3CC[C@H](CC(=O)O)CC3...,98.81,Rattus norvegicus

Cc1nc(C(C)C)c(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](CC(=O)O)CC2)cc1

,Drug_ID,SMILES,Y,Species
474,CHEMBL2178390,Cc1nc(C(C)C)c(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](C...,97.38,Homo sapiens
2230,CHEMBL2178390,Cc1nc(C(C)C)c(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](C...,98.81,Rattus norvegicus

Cc1nc(C(F)F)c(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](CC(=O)O)CC2)cc1

,Drug_ID,SMILES,Y,Species
1685,CHEMBL2178388,Cc1nc(C(F)F)c(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](C...,94.56,Homo sapiens
2463,CHEMBL2178388,Cc1nc(C(F)F)c(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](C...,96.17,Rattus norvegicus

Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(=O)NC(C)(C)C(=O)O)CC3)cc2)nc1C(N)=O

,Drug_ID,SMILES,Y,Species
482,CHEMBL2178937,Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(=O)NC(C)(C)C...,92.16,Homo sapiens
2777,CHEMBL2178937,Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(=O)NC(C)(C)C...,97.49,Rattus norvegicus

Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(=O)NS(C)(=O)=O)CC3)cc2)nc1C(N)=O

,Drug_ID,SMILES,Y,Species
1344,CHEMBL2178939,Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(=O)NS(C)(=O)...,89.05,Homo sapiens
2801,CHEMBL2178939,Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(=O)NS(C)(=O)...,96.79,Rattus norvegicus

Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(N)=O)CC3)cc2)nc1C(N)=O

,Drug_ID,SMILES,Y,Species
826,CHEMBL2178935,Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(N)=O)CC3)cc2...,87.11,Homo sapiens
2552,CHEMBL2178935,Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CC(N)=O)CC3)cc2...,94.44,Rattus norvegicus

Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CCO)CC3)cc2)nc1C(N)=O

,Drug_ID,SMILES,Y,Species
1055,CHEMBL2178933,Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CCO)CC3)cc2)nc1...,97.00,Homo sapiens
2781,CHEMBL2178933,Cc1nc(C)c(-c2ccc([C@H]3CC[C@H](CCO)CC3)cc2)nc1...,98.61,Rattus norvegicus

Cc1nc2ccc(NS(=O)(=O)c3ccc(C)c(C)c3)cc2s1

,Drug_ID,SMILES,Y,Species
862,CHEMBL1509029,Cc1nc2ccc(NS(=O)(=O)c3ccc(C)c(C)c3)cc2s1,99.90,Homo sapiens
2543,CHEMBL1509029,Cc1nc2ccc(NS(=O)(=O)c3ccc(C)c(C)c3)cc2s1,99.76,Rattus norvegicus

Cc1nc2ccc(NS(=O)(=O)c3ccc4c(c3)OCCO4)cc2s1

,Drug_ID,SMILES,Y,Species
1476,CHEMBL1539841,Cc1nc2ccc(NS(=O)(=O)c3ccc4c(c3)OCCO4)cc2s1,99.67,Homo sapiens
2664,CHEMBL1539841,Cc1nc2ccc(NS(=O)(=O)c3ccc4c(c3)OCCO4)cc2s1,99.33,Rattus norvegicus

Cc1nc2n(c(=O)c1CCN1CCC(c3noc4cc(F)ccc34)CC1)CCCC2

,Drug_ID,SMILES,Y,Species
1123,CHEMBL85,Cc1nc2n(c(=O)c1CCN1CCC(c3noc4cc(F)ccc34)CC1)CCCC2,84.60,Homo sapiens
2613,CHEMBL85,Cc1nc2n(c(=O)c1CCN1CCC(c3noc4cc(F)ccc34)CC1)CCCC2,94.56,Rattus norvegicus

Cc1ncc(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](CC(=O)O)CC2)cc1

,Drug_ID,SMILES,Y,Species
498,CHEMBL2178951,Cc1ncc(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](CC(=O)O)...,94.32,Homo sapiens
2802,CHEMBL2178951,Cc1ncc(C(N)=O)nc1-c1ccc([C@H]2CC[C@H](CC(=O)O)...,96.57,Rattus norvegicus

Cc1ncc(C(N)=S)nc1-c1ccc([C@H]2CC[C@H](CC(=O)O)CC2)cc1

,Drug_ID,SMILES,Y,Species
540,CHEMBL2178384,Cc1ncc(C(N)=S)nc1-c1ccc([C@H]2CC[C@H](CC(=O)O)...,97.20,Homo sapiens
2398,CHEMBL2178384,Cc1ncc(C(N)=S)nc1-c1ccc([C@H]2CC[C@H](CC(=O)O)...,99.01,Rattus norvegicus

Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2

,Drug_ID,SMILES,Y,Species
223,CHEMBL655,Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,98.00,Canis lupus familiaris
1635,CHEMBL655,Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,98.25,Homo sapiens
2237,CHEMBL655,Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,95.43,Rattus norvegicus

Cc1nccc(-c2ccc(-c3nc4ccncc4c(O)c3C#N)cc2)c1Cl

,Drug_ID,SMILES,Y,Species
1588,CHEMBL1957460,Cc1nccc(-c2ccc(-c3nc4ccncc4c(O)c3C#N)cc2)c1Cl,99.86,Homo sapiens
1967,CHEMBL1957460,Cc1nccc(-c2ccc(-c3nc4ccncc4c(O)c3C#N)cc2)c1Cl,99.12,Mus musculus
2481,CHEMBL1957460,Cc1nccc(-c2ccc(-c3nc4ccncc4c(O)c3C#N)cc2)c1Cl,99.86,Rattus norvegicus

Cc1ncccc1Oc1ncnc(OC2CCN(C(=O)OC(C)C)CC2)c1C

,Drug_ID,SMILES,Y,Species
625,CHEMBL1766081,Cc1ncccc1Oc1ncnc(OC2CCN(C(=O)OC(C)C)CC2)c1C,99.21,Homo sapiens
2028,CHEMBL1766081,Cc1ncccc1Oc1ncnc(OC2CCN(C(=O)OC(C)C)CC2)c1C,98.51,Mus musculus
2465,CHEMBL1766081,Cc1ncccc1Oc1ncnc(OC2CCN(C(=O)OC(C)C)CC2)c1C,96.87,Rattus norvegicus

Cc1nccn1-c1sc(Nc2cnccn2)nc1-c1cccc(C#N)c1

,Drug_ID,SMILES,Y,Species
1457,CHEMBL2113096,Cc1nccn1-c1sc(Nc2cnccn2)nc1-c1cccc(C#N)c1,95.63,Homo sapiens
2073,CHEMBL2113096,Cc1nccn1-c1sc(Nc2cnccn2)nc1-c1cccc(C#N)c1,96.65,Mus musculus
2285,CHEMBL2113096,Cc1nccn1-c1sc(Nc2cnccn2)nc1-c1cccc(C#N)c1,95.63,Rattus norvegicus

Cc1ncsc1C(=O)N(Cc1cc(=O)[nH]c2c(F)cccc12)c1cccc(Cl)c1

,Drug_ID,SMILES,Y,Species
850,CHEMBL522771,Cc1ncsc1C(=O)N(Cc1cc(=O)[nH]c2c(F)cccc12)c1ccc...,97.91,Homo sapiens
1984,CHEMBL522771,Cc1ncsc1C(=O)N(Cc1cc(=O)[nH]c2c(F)cccc12)c1ccc...,92.64,Mus musculus
2762,CHEMBL522771,Cc1ncsc1C(=O)N(Cc1cc(=O)[nH]c2c(F)cccc12)c1ccc...,91.64,Rattus norvegicus

Cc1nn(-c2ccc(F)cc2)c(NS(=O)(=O)c2ccc(C#N)cc2)c1C(=O)N[C@@H](C)C(C)(C)C

,Drug_ID,SMILES,Y,Species
570,CHEMBL1916288,Cc1nn(-c2ccc(F)cc2)c(NS(=O)(=O)c2ccc(C#N)cc2)c...,95.63,Homo sapiens
2642,CHEMBL1916288,Cc1nn(-c2ccc(F)cc2)c(NS(=O)(=O)c2ccc(C#N)cc2)c...,91.99,Rattus norvegicus

Cc1nn(-c2ccc(F)cc2)c(NS(=O)(=O)c2ccc(C(F)(F)F)cc2)c1C(=O)N[C@@H](C)C(C)(C)C

,Drug_ID,SMILES,Y,Species
289,CHEMBL1916289,Cc1nn(-c2ccc(F)cc2)c(NS(=O)(=O)c2ccc(C(F)(F)F)...,92.64,Cavia porcellus
1485,CHEMBL1916289,Cc1nn(-c2ccc(F)cc2)c(NS(=O)(=O)c2ccc(C(F)(F)F)...,98.64,Homo sapiens
2302,CHEMBL1916289,Cc1nn(-c2ccc(F)cc2)c(NS(=O)(=O)c2ccc(C(F)(F)F)...,97.07,Rattus norvegicus

Cc1nn(-c2ccccc2)c(N)c1-c1ccccc1

,Drug_ID,SMILES,Y,Species
193,CHEMBL1416617,Cc1nn(-c2ccccc2)c(N)c1-c1ccccc1,96.87,Canis lupus familiaris
305,CHEMBL1416617,Cc1nn(-c2ccccc2)c(N)c1-c1ccccc1,96.72,Cavia porcellus
705,CHEMBL1416617,Cc1nn(-c2ccccc2)c(N)c1-c1ccccc1,98.70,Homo sapiens
2319,CHEMBL1416617,Cc1nn(-c2ccccc2)c(N)c1-c1ccccc1,95.43,Rattus norvegicus

Cc1nn(-c2ccccc2)c(NS(=O)(=O)C2CCCCC2)c1C(=O)N[C@@H](C)C(C)(C)C

,Drug_ID,SMILES,Y,Species
1509,CHEMBL1916286,Cc1nn(-c2ccccc2)c(NS(=O)(=O)C2CCCCC2)c1C(=O)N[...,98.51,Homo sapiens
2736,CHEMBL1916286,Cc1nn(-c2ccccc2)c(NS(=O)(=O)C2CCCCC2)c1C(=O)N[...,98.37,Rattus norvegicus

Cc1nn(-c2ccccc2)nc1C(=O)N[C@@H]1COc2cccc(N3CCN(C)CC3)c2C1

,Drug_ID,SMILES,Y,Species
779,CHEMBL2069403,Cc1nn(-c2ccccc2)nc1C(=O)N[C@@H]1COc2cccc(N3CCN...,95.82,Homo sapiens
2330,CHEMBL2069403,Cc1nn(-c2ccccc2)nc1C(=O)N[C@@H]1COc2cccc(N3CCN...,96.17,Rattus norvegicus

Cc1nn(C)c(C)c1-c1ccc(-c2nc3ccncc3c(O)c2C#N)cc1

,Drug_ID,SMILES,Y,Species
1608,CHEMBL1957462,Cc1nn(C)c(C)c1-c1ccc(-c2nc3ccncc3c(O)c2C#N)cc1,99.64,Homo sapiens
2110,CHEMBL1957462,Cc1nn(C)c(C)c1-c1ccc(-c2nc3ccncc3c(O)c2C#N)cc1,96.57,Mus musculus

Cc1nn(C2CCCCC2)c(N)c1-c1ccccc1

            Drug_ID                          SMILES      Y            Species
307   CHEMBL1364767  Cc1nn(C2CCCCC2)c(N)c1-c1ccccc1  89.49    Cavia porcellus
491   CHEMBL1364767  Cc1nn(C2CCCCC2)c(N)c1-c1ccccc1  95.53       Homo sapiens
2700  CHEMBL1364767  Cc1nn(C2CCCCC2)c(N)c1-c1ccccc1  89.91  Rattus norvegicus

Cc1nn(C2CCOCC2)c(NS(=O)(=O)c2ccc(C3CC3)cc2)c1C(=O)N[C@@H](C)C(C)(C)C

,Drug_ID,SMILES,Y,Species
25,CHEMBL1934426,Cc1nn(C2CCOCC2)c(NS(=O)(=O)c2ccc(C3CC3)cc2)c1C...,89.27,Canis lupus familiaris
1680,CHEMBL1934426,Cc1nn(C2CCOCC2)c(NS(=O)(=O)c2ccc(C3CC3)cc2)c1C...,92.64,Homo sapiens
2812,CHEMBL1934426,Cc1nn(C2CCOCC2)c(NS(=O)(=O)c2ccc(C3CC3)cc2)c1C...,89.05,Rattus norvegicus

Cc1nnc(-c2ccc(N3CCC(Oc4cc(F)ccc4Cl)CC3)nn2)o1

,Drug_ID,SMILES,Y,Species
722,CHEMBL226646,Cc1nnc(-c2ccc(N3CCC(Oc4cc(F)ccc4Cl)CC3)nn2)o1,98.21,Homo sapiens
2433,CHEMBL226646,Cc1nnc(-c2ccc(N3CCC(Oc4cc(F)ccc4Cl)CC3)nn2)o1,99.18,Rattus norvegicus

Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@@H](NC(=O)Cn4cnnn4)[C@H]3SC2)s1

,Drug_ID,SMILES,Y,Species
152,CHEMBL1435,Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@@H](NC(=O)Cn4cn...,27.55,Canis lupus familiaris
915,CHEMBL1435,Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@@H](NC(=O)Cn4cn...,90.32,Homo sapiens

Cc1noc(NS(=O)(=O)c2ccc(N)cc2)c1C

,Drug_ID,SMILES,Y,Species
55,CHEMBL453,Cc1noc(NS(=O)(=O)c2ccc(N)cc2)c1C,86.59,Canis lupus familiaris
617,CHEMBL453,Cc1noc(NS(=O)(=O)c2ccc(N)cc2)c1C,91.28,Homo sapiens
2460,CHEMBL453,Cc1noc(NS(=O)(=O)c2ccc(N)cc2)c1C,98.47,Rattus norvegicus

Cc1nocc1C(=O)Nc1ccc(-c2ccccc2OC(F)(F)F)c(N)n1

,Drug_ID,SMILES,Y,Species
817,CHEMBL2324355,Cc1nocc1C(=O)Nc1ccc(-c2ccccc2OC(F)(F)F)c(N)n1,98.40,Homo sapiens
2328,CHEMBL2324355,Cc1nocc1C(=O)Nc1ccc(-c2ccccc2OC(F)(F)F)c(N)n1,96.34,Rattus norvegicus

Cc1oc(CN2CCNCC2)cc1C(=O)NCC12CC3CC(CC(C3)C1)C2

,Drug_ID,SMILES,Y,Species
148,CHEMBL427851,Cc1oc(CN2CCNCC2)cc1C(=O)NCC12CC3CC(CC(C3)C1)C2,56.30,Canis lupus familiaris
1025,CHEMBL427851,Cc1oc(CN2CCNCC2)cc1C(=O)NCC12CC3CC(CC(C3)C1)C2,85.19,Homo sapiens

Cc1onc(-c2c(Cl)cccc2Cl)c1CC(=O)NCc1ccc(OCC(F)(F)F)nc1

,Drug_ID,SMILES,Y,Species
1945,CHEMBL1797410,Cc1onc(-c2c(Cl)cccc2Cl)c1CC(=O)NCc1ccc(OCC(F)(...,99.10,Homo sapiens
2666,CHEMBL1797410,Cc1onc(-c2c(Cl)cccc2Cl)c1CC(=O)NCc1ccc(OCC(F)(...,95.43,Rattus norvegicus

Cc1onc(-c2c(Cl)cccc2Cl)c1NC(=O)OCc1c(F)cccc1Cl

,Drug_ID,SMILES,Y,Species
604,CHEMBL1797387,Cc1onc(-c2c(Cl)cccc2Cl)c1NC(=O)OCc1c(F)cccc1Cl,99.8,Homo sapiens
2432,CHEMBL1797387,Cc1onc(-c2c(Cl)cccc2Cl)c1NC(=O)OCc1c(F)cccc1Cl,99.7,Rattus norvegicus

Cc1onc(-c2ccccc2)c1-c1ccc(S(N)(=O)=O)cc1

,Drug_ID,SMILES,Y,Species
293,CHEMBL865,Cc1onc(-c2ccccc2)c1-c1ccc(S(N)(=O)=O)cc1,94.56,Cavia porcellus
846,CHEMBL865,Cc1onc(-c2ccccc2)c1-c1ccc(S(N)(=O)=O)cc1,97.55,Homo sapiens

Cc1onc(-c2ccccc2)c1C(=O)N(C)c1ccc(Cl)cc1

,Drug_ID,SMILES,Y,Species
1880,CHEMBL601882,Cc1onc(-c2ccccc2)c1C(=O)N(C)c1ccc(Cl)cc1,95.82,Homo sapiens
2488,CHEMBL601882,Cc1onc(-c2ccccc2)c1C(=O)N(C)c1ccc(Cl)cc1,92.48,Rattus norvegicus

Cc1sc2c(c1C)C(c1ccc(Cl)cc1)=N[C@@H](CC(=O)OC(C)(C)C)c1nnc(C)n1-2

,Drug_ID,SMILES,Y,Species
1373,CHEMBL1957266,Cc1sc2c(c1C)C(c1ccc(Cl)cc1)=N[C@@H](CC(=O)OC(C...,99.14,Homo sapiens
2532,CHEMBL1957266,Cc1sc2c(c1C)C(c1ccc(Cl)cc1)=N[C@@H](CC(=O)OC(C...,98.47,Rattus norvegicus

Clc1ccc(OCc2cn3ccccc3n2)c2ncccc12

,Drug_ID,SMILES,Y,Species
953,CHEMBL1412533,Clc1ccc(OCc2cn3ccccc3n2)c2ncccc12,99.4,Homo sapiens
2150,CHEMBL1412533,Clc1ccc(OCc2cn3ccccc3n2)c2ncccc12,99.3,Rattus norvegicus

Clc1ccc2c(c1)C(N1CCNCC1)=Nc1ccccc1O2

,Drug_ID,SMILES,Y,Species
1022,CHEMBL1113,Clc1ccc2c(c1)C(N1CCNCC1)=Nc1ccccc1O2,89.05,Homo sapiens
2813,CHEMBL1113,Clc1ccc2c(c1)C(N1CCNCC1)=Nc1ccccc1O2,89.91,Rattus norvegicus

Clc1ccc2c(c1)CCc1cccnc1C2=C1CCNCC1

         Drug_ID                              SMILES      Y            Species
2023  CHEMBL1172  Clc1ccc2c(c1)CCc1cccnc1C2=C1CCNCC1  81.71       Mus musculus
2634  CHEMBL1172  Clc1ccc2c(c1)CCc1cccnc1C2=C1CCNCC1  85.48  Rattus norvegicus

Cn1c(-c2cc(=O)c(O)c[nH]2)nn(S(=O)(=O)NC(=O)N2C[C@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c3csc(N)n3)C2=O)c1=O

,Drug_ID,SMILES,Y,Species
1293,CHEMBL2021696,Cn1c(-c2cc(=O)c(O)c[nH]2)nn(S(=O)(=O)NC(=O)N2C...,95.53,Homo sapiens
2247,CHEMBL2021696,Cn1c(-c2cc(=O)c(O)c[nH]2)nn(S(=O)(=O)NC(=O)N2C...,98.51,Rattus norvegicus

Cn1c(-c2cccc(F)c2)nc2c(N)nc(C#CC3(O)CCCC3)nc21

,Drug_ID,SMILES,Y,Species
853,CHEMBL297685,Cn1c(-c2cccc(F)c2)nc2c(N)nc(C#CC3(O)CCCC3)nc21,88.11,Homo sapiens
2031,CHEMBL297685,Cn1c(-c2cccc(F)c2)nc2c(N)nc(C#CC3(O)CCCC3)nc21,92.48,Mus musculus

Cn1c(=O)c2c(ncn2C)n(C)c1=O

        Drug_ID                      SMILES      Y                 Species
104   CHEMBL113  Cn1c(=O)c2c(ncn2C)n(C)c1=O  14.52  Canis lupus familiaris
1259  CHEMBL113  Cn1c(=O)c2c(ncn2C)n(C)c1=O  24.45            Homo sapiens
2380  CHEMBL113  Cn1c(=O)c2c(ncn2C)n(C)c1=O  13.68       Rattus norvegicus

Cn1c(=O)c2nc[nH]c2n(C)c1=O

        Drug_ID                      SMILES      Y                 Species
32    CHEMBL190  Cn1c(=O)c2nc[nH]c2n(C)c1=O  14.81  Canis lupus familiaris
1508  CHEMBL190  Cn1c(=O)c2nc[nH]c2n(C)c1=O  43.70            Homo sapiens
2621  CHEMBL190  Cn1c(=O)c2nc[nH]c2n(C)c1=O  43.14       Rattus norvegicus

Cn1cc(-c2ccncc2)c(-c2ccc(OCc3ccc4ccccc4n3)cc2)n1

,Drug_ID,SMILES,Y,Species
1494,CHEMBL562318,Cn1cc(-c2ccncc2)c(-c2ccc(OCc3ccc4ccccc4n3)cc2)n1,99.88,Homo sapiens
2005,CHEMBL562318,Cn1cc(-c2ccncc2)c(-c2ccc(OCc3ccc4ccccc4n3)cc2)n1,99.61,Mus musculus
2205,CHEMBL562318,Cn1cc(-c2ccncc2)c(-c2ccc(OCc3ccc4ccccc4n3)cc2)n1,99.83,Rattus norvegicus

Cn1cc(C(=O)NC[C@@H](O)CN2CCC(Oc3ccc(Cl)c(Cl)c3)CC2)c(C(F)(F)F)cc1=O

,Drug_ID,SMILES,Y,Species
238,CHEMBL2207665,Cn1cc(C(=O)NC[C@@H](O)CN2CCC(Oc3ccc(Cl)c(Cl)c3...,95.12,Canis lupus familiaris
1379,CHEMBL2207665,Cn1cc(C(=O)NC[C@@H](O)CN2CCC(Oc3ccc(Cl)c(Cl)c3...,93.53,Homo sapiens
2699,CHEMBL2207665,Cn1cc(C(=O)NC[C@@H](O)CN2CCC(Oc3ccc(Cl)c(Cl)c3...,89.70,Rattus norvegicus

Cn1cc[nH]c1=S

         Drug_ID         SMILES      Y            Species
1264  CHEMBL1515  Cn1cc[nH]c1=S  18.99       Homo sapiens
2473  CHEMBL1515  Cn1cc[nH]c1=S  18.64  Rattus norvegicus

FC(F)(F)Oc1ccc(-c2nnc(CCCCc3ccc4cccnc4n3)o2)cc1Cl

,Drug_ID,SMILES,Y,Species
1161,CHEMBL2153595,FC(F)(F)Oc1ccc(-c2nnc(CCCCc3ccc4cccnc4n3)o2)cc1Cl,99.92,Homo sapiens
2059,CHEMBL2153595,FC(F)(F)Oc1ccc(-c2nnc(CCCCc3ccc4cccnc4n3)o2)cc1Cl,99.57,Mus musculus

Fc1ccc(-c2cnc(C3CCN(Cc4ccn(-c5ccc(C(F)(F)F)cc5)c4)CC3)[nH]2)cc1

,Drug_ID,SMILES,Y,Species
1007,CHEMBL510193,Fc1ccc(-c2cnc(C3CCN(Cc4ccn(-c5ccc(C(F)(F)F)cc5...,99.91,Homo sapiens
2009,CHEMBL510193,Fc1ccc(-c2cnc(C3CCN(Cc4ccn(-c5ccc(C(F)(F)F)cc5...,99.77,Mus musculus

Fc1ccc([C@@H]2CCNC[C@H]2COc2ccc3c(c2)OCO3)cc1

,Drug_ID,SMILES,Y,Species
874,CHEMBL490,Fc1ccc([C@@H]2CCNC[C@H]2COc2ccc3c(c2)OCO3)cc1,89.91,Homo sapiens
2122,CHEMBL490,Fc1ccc([C@@H]2CCNC[C@H]2COc2ccc3c(c2)OCO3)cc1,94.68,Rattus norvegicus

N#CCOc1ccccc1-c1ccc(-c2nc3ccncc3c(O)c2C#N)cc1

,Drug_ID,SMILES,Y,Species
646,CHEMBL1957367,N#CCOc1ccccc1-c1ccc(-c2nc3ccncc3c(O)c2C#N)cc1,99.89,Homo sapiens
2088,CHEMBL1957367,N#CCOc1ccccc1-c1ccc(-c2nc3ccncc3c(O)c2C#N)cc1,98.51,Mus musculus

N#CC[C@H](C1CCCC1)n1cc(-c2ncnc3[nH]ccc23)cn1

,Drug_ID,SMILES,Y,Species
220,CHEMBL1789941,N#CC[C@H](C1CCCC1)n1cc(-c2ncnc3[nH]ccc23)cn1,83.37,Canis lupus familiaris
1811,CHEMBL1789941,N#CC[C@H](C1CCCC1)n1cc(-c2ncnc3[nH]ccc23)cn1,94.68,Homo sapiens
2688,CHEMBL1789941,N#CC[C@H](C1CCCC1)n1cc(-c2ncnc3[nH]ccc23)cn1,82.72,Rattus norvegicus

N#C[C@@]1(NC(=O)[C@@H](N)Cc2cccs2)C[C@@H]1c1ccccc1

,Drug_ID,SMILES,Y,Species
1663,CHEMBL1078411,N#C[C@@]1(NC(=O)[C@@H](N)Cc2cccs2)C[C@@H]1c1cc...,54.02,Homo sapiens
2597,CHEMBL1078411,N#C[C@@]1(NC(=O)[C@@H](N)Cc2cccs2)C[C@@H]1c1cc...,65.58,Rattus norvegicus

N#Cc1c(-c2ccc(-c3ccccc3Cl)cc2)nc2ccncc2c1O

,Drug_ID,SMILES,Y,Species
616,CHEMBL1957369,N#Cc1c(-c2ccc(-c3ccccc3Cl)cc2)nc2ccncc2c1O,99.92,Homo sapiens
2006,CHEMBL1957369,N#Cc1c(-c2ccc(-c3ccccc3Cl)cc2)nc2ccncc2c1O,99.78,Mus musculus

N#Cc1cc(F)c(Cl)cc1O[C@H](CCN)c1ccccc1

,Drug_ID,SMILES,Y,Species
76,CHEMBL1789186,N#Cc1cc(F)c(Cl)cc1O[C@H](CCN)c1ccccc1,95.43,Canis lupus familiaris
251,CHEMBL1789186,N#Cc1cc(F)c(Cl)cc1O[C@H](CCN)c1ccccc1,89.91,Cavia porcellus
578,CHEMBL1789186,N#Cc1cc(F)c(Cl)cc1O[C@H](CCN)c1ccccc1,71.05,Homo sapiens

N#Cc1cc(S(=O)(=O)Nc2ncc(Cl)s2)ccc1Oc1ccc(Cl)cc1-c1ccnn1C1CNC1

,Drug_ID,SMILES,Y,Species
1346,CHEMBL2325635,N#Cc1cc(S(=O)(=O)Nc2ncc(Cl)s2)ccc1Oc1ccc(Cl)cc...,99.19,Homo sapiens
2415,CHEMBL2325635,N#Cc1cc(S(=O)(=O)Nc2ncc(Cl)s2)ccc1Oc1ccc(Cl)cc...,98.58,Rattus norvegicus

N#Cc1cc(S(=O)(=O)Nc2ncns2)ccc1Oc1ccc(C(F)(F)F)cc1-c1ccnnc1

,Drug_ID,SMILES,Y,Species
1763,CHEMBL2325021,N#Cc1cc(S(=O)(=O)Nc2ncns2)ccc1Oc1ccc(C(F)(F)F)...,99.41,Homo sapiens
2659,CHEMBL2325021,N#Cc1cc(S(=O)(=O)Nc2ncns2)ccc1Oc1ccc(C(F)(F)F)...,97.91,Rattus norvegicus

N#Cc1ccc(C(F)(F)F)nc1O[C@H](CCN)c1ccno1

,Drug_ID,SMILES,Y,Species
49,CHEMBL1789187,N#Cc1ccc(C(F)(F)F)nc1O[C@H](CCN)c1ccno1,46.55,Canis lupus familiaris
1535,CHEMBL1789187,N#Cc1ccc(C(F)(F)F)nc1O[C@H](CCN)c1ccno1,44.27,Homo sapiens

N#Cc1ccc(C[C@@H](C(=O)O)N2CCC(CN3CCC(Oc4ccc(Cl)c(Cl)c4)CC3)CC2)cc1

,Drug_ID,SMILES,Y,Species
233,CHEMBL2158771,N#Cc1ccc(C[C@@H](C(=O)O)N2CCC(CN3CCC(Oc4ccc(Cl...,83.37,Canis lupus familiaris
991,CHEMBL2158771,N#Cc1ccc(C[C@@H](C(=O)O)N2CCC(CN3CCC(Oc4ccc(Cl...,94.79,Homo sapiens
2049,CHEMBL2158771,N#Cc1ccc(C[C@@H](C(=O)O)N2CCC(CN3CCC(Oc4ccc(Cl...,80.29,Mus musculus
2200,CHEMBL2158771,N#Cc1ccc(C[C@@H](C(=O)O)N2CCC(CN3CCC(Oc4ccc(Cl...,90.32,Rattus norvegicus

N#Cc1ccc(Cl)cc1S[C@H](CCN)c1ccccc1

,Drug_ID,SMILES,Y,Species
118,CHEMBL1789155,N#Cc1ccc(Cl)cc1S[C@H](CCN)c1ccccc1,87.37,Canis lupus familiaris
994,CHEMBL1789155,N#Cc1ccc(Cl)cc1S[C@H](CCN)c1ccccc1,41.45,Homo sapiens

N#Cc1ccc(NC(=O)Nc2ccccc2Br)c2nn[nH]c12

,Drug_ID,SMILES,Y,Species
139,CHEMBL38182,N#Cc1ccc(NC(=O)Nc2ccccc2Br)c2nn[nH]c12,99.51,Canis lupus familiaris
1640,CHEMBL38182,N#Cc1ccc(NC(=O)Nc2ccccc2Br)c2nn[nH]c12,99.58,Homo sapiens

N#Cc1ccc2c(c1)N(CCN1CCC(NCc3ccc4c(n3)NC(=O)CO4)CC1)C(=O)CO2

,Drug_ID,SMILES,Y,Species
313,CHEMBL1824041,N#Cc1ccc2c(c1)N(CCN1CCC(NCc3ccc4c(n3)NC(=O)CO4...,40.89,Cavia porcellus
890,CHEMBL1824041,N#Cc1ccc2c(c1)N(CCN1CCC(NCc3ccc4c(n3)NC(=O)CO4...,77.21,Homo sapiens

N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4cc5c(cn4)OCCO5)[C@@H](O)C3)c2c1

,Drug_ID,SMILES,Y,Species
83,CHEMBL2164741,N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4cc5c(cn4)OC...,39.78,Canis lupus familiaris
748,CHEMBL2164741,N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4cc5c(cn4)OC...,79.17,Homo sapiens
2408,CHEMBL2164741,N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4cc5c(cn4)OC...,52.88,Rattus norvegicus

N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4ccc5c(n4)NC(=O)CO5)[C@@H](F)C3)c2c1

,Drug_ID,SMILES,Y,Species
165,CHEMBL2165066,N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4ccc5c(n4)NC...,40.89,Canis lupus familiaris
279,CHEMBL2165066,N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4ccc5c(n4)NC...,28.47,Cavia porcellus
1573,CHEMBL2165066,N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4ccc5c(n4)NC...,79.55,Homo sapiens
1959,CHEMBL2165066,N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4ccc5c(n4)NC...,53.45,Mus musculus
2466,CHEMBL2165066,N#Cc1ccc2ccc(=O)n(CCN3CC[C@@H](NCc4ccc5c(n4)NC...,71.53,Rattus norvegicus

N#Cc1ccc2ccc(=O)n(CCN3CC[C@H](NCc4cc5c(cn4)OCCO5)[C@H](O)C3)c2c1

,Drug_ID,SMILES,Y,Species
66,CHEMBL2164740,N#Cc1ccc2ccc(=O)n(CCN3CC[C@H](NCc4cc5c(cn4)OCC...,39.23,Canis lupus familiaris
2420,CHEMBL2164740,N#Cc1ccc2ccc(=O)n(CCN3CC[C@H](NCc4cc5c(cn4)OCC...,26.64,Rattus norvegicus

N#Cc1cccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c1

,Drug_ID,SMILES,Y,Species
162,CHEMBL1778628,N#Cc1cccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c1,96.42,Canis lupus familiaris
351,CHEMBL1778628,N#Cc1cccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c1,98.61,Homo sapiens
2185,CHEMBL1778628,N#Cc1cccc(-c2cc(C(F)(F)F)ccc2OCC(=O)O)c1,96.50,Rattus norvegicus

N#Cc1cccc(-c2cc(Cl)ccc2OCC(=O)O)c1

,Drug_ID,SMILES,Y,Species
211,CHEMBL1778636,N#Cc1cccc(-c2cc(Cl)ccc2OCC(=O)O)c1,97.66,Canis lupus familiaris
1781,CHEMBL1778636,N#Cc1cccc(-c2cc(Cl)ccc2OCC(=O)O)c1,99.25,Homo sapiens
2355,CHEMBL1778636,N#Cc1cccc(-c2cc(Cl)ccc2OCC(=O)O)c1,96.57,Rattus norvegicus

N#Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(Cl)c(Cl)c3)CC2)CC1

,Drug_ID,SMILES,Y,Species
142,CHEMBL2158769,N#Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(...,93.39,Canis lupus familiaris
1513,CHEMBL2158769,N#Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(...,90.91,Homo sapiens
2284,CHEMBL2158769,N#Cc1ccccc1C[C@@H](C(=O)O)N1CCC(CN2CCC(Oc3ccc(...,77.62,Rattus norvegicus

N/C(=N\C(=O)c1nc(Cl)c(N)nc1N)NCCCCc1ccc(OCC(O)CO)cc1

,Drug_ID,SMILES,Y,Species
321,CHEMBL212432,N/C(=N\C(=O)c1nc(Cl)c(N)nc1N)NCCCCc1ccc(OCC(O)...,70.10,Cavia porcellus
1355,CHEMBL212432,N/C(=N\C(=O)c1nc(Cl)c(N)nc1N)NCCCCc1ccc(OCC(O)...,75.12,Homo sapiens
2194,CHEMBL212432,N/C(=N\C(=O)c1nc(Cl)c(N)nc1N)NCCCCc1ccc(OCC(O)...,68.63,Rattus norvegicus

N=C(N)NC(=O)c1nc(Cl)c(N)nc1N

        Drug_ID                        SMILES      Y            Species
1075  CHEMBL945  N=C(N)NC(=O)c1nc(Cl)c(N)nc1N  27.09       Homo sapiens
2453  CHEMBL945  N=C(N)NC(=O)c1nc(Cl)c(N)nc1N  31.37  Rattus norvegicus

NC(=O)C(c1ccccc1)(c1ccccc1)[C@@H]1CCN(CCc2ccc3c(c2)CCO3)C1

,Drug_ID,SMILES,Y,Species
260,CHEMBL1346,NC(=O)C(c1ccccc1)(c1ccccc1)[C@@H]1CCN(CCc2ccc3...,89.91,Cavia porcellus
1780,CHEMBL1346,NC(=O)C(c1ccccc1)(c1ccccc1)[C@@H]1CCN(CCc2ccc3...,95.12,Homo sapiens
2752,CHEMBL1346,NC(=O)C(c1ccccc1)(c1ccccc1)[C@@H]1CCN(CCc2ccc3...,92.16,Rattus norvegicus

NC(=O)N1c2ccccc2C=Cc2ccccc21

        Drug_ID                        SMILES      Y                 Species
39    CHEMBL108  NC(=O)N1c2ccccc2C=Cc2ccccc21  72.91  Canis lupus familiaris
296   CHEMBL108  NC(=O)N1c2ccccc2C=Cc2ccccc21  75.97         Cavia porcellus
1214  CHEMBL108  NC(=O)N1c2ccccc2C=Cc2ccccc21  70.58            Homo sapiens
2124  CHEMBL108  NC(=O)N1c2ccccc2C=Cc2ccccc21  73.36       Rattus norvegicus

NC(=O)NC(=O)C(Nc1ccc2c(c1)CCC2)c1ccccc1

,Drug_ID,SMILES,Y,Species
1812,CHEMBL1734492,NC(=O)NC(=O)C(Nc1ccc2c(c1)CCC2)c1ccccc1,97.00,Homo sapiens
2728,CHEMBL1734492,NC(=O)NC(=O)C(Nc1ccc2c(c1)CCC2)c1ccccc1,94.19,Rattus norvegicus

NC(=O)[C@@H](CCC(F)(F)F)N(Cc1ccc(-c2ncon2)cc1F)S(=O)(=O)c1ccc(Cl)cc1

,Drug_ID,SMILES,Y,Species
329,CHEMBL1090771,NC(=O)[C@@H](CCC(F)(F)F)N(Cc1ccc(-c2ncon2)cc1F...,99.19,Cavia porcellus
391,CHEMBL1090771,NC(=O)[C@@H](CCC(F)(F)F)N(Cc1ccc(-c2ncon2)cc1F...,98.33,Homo sapiens
2062,CHEMBL1090771,NC(=O)[C@@H](CCC(F)(F)F)N(Cc1ccc(-c2ncon2)cc1F...,98.51,Mus musculus
2687,CHEMBL1090771,NC(=O)[C@@H](CCC(F)(F)F)N(Cc1ccc(-c2ncon2)cc1F...,98.81,Rattus norvegicus

NC(=O)c1cc(C(N)=O)n(-c2cccc(-c3cc(C(F)(F)F)ccc3C(F)(F)F)c2)n1

,Drug_ID,SMILES,Y,Species
1325,CHEMBL1631095,NC(=O)c1cc(C(N)=O)n(-c2cccc(-c3cc(C(F)(F)F)ccc...,96.72,Homo sapiens
2531,CHEMBL1631095,NC(=O)c1cc(C(N)=O)n(-c2cccc(-c3cc(C(F)(F)F)ccc...,94.32,Rattus norvegicus

NC(=O)c1ccc(-n2nnnc2Oc2ccc(Br)cc2)cc1

,Drug_ID,SMILES,Y,Species
1973,CHEMBL1890471,NC(=O)c1ccc(-n2nnnc2Oc2ccc(Br)cc2)cc1,91.46,Mus musculus
2445,CHEMBL1890471,NC(=O)c1ccc(-n2nnnc2Oc2ccc(Br)cc2)cc1,91.28,Rattus norvegicus

NC(=O)c1cnc(N[C@@H]2CCCC[C@@H]2N)nc1Nc1cccc(-n2nccn2)c1

,Drug_ID,SMILES,Y,Species
288,CHEMBL2177736,NC(=O)c1cnc(N[C@@H]2CCCC[C@@H]2N)nc1Nc1cccc(-n...,89.91,Cavia porcellus
1591,CHEMBL2177736,NC(=O)c1cnc(N[C@@H]2CCCC[C@@H]2N)nc1Nc1cccc(-n...,91.82,Homo sapiens
2401,CHEMBL2177736,NC(=O)c1cnc(N[C@@H]2CCCC[C@@H]2N)nc1Nc1cccc(-n...,91.82,Rattus norvegicus

NC(=O)c1cnc(N[C@H]2CCCNC2)c2cc(-c3ccccc3)sc12

,Drug_ID,SMILES,Y,Species
227,CHEMBL1287920,NC(=O)c1cnc(N[C@H]2CCCNC2)c2cc(-c3ccccc3)sc12,96.34,Canis lupus familiaris
2669,CHEMBL1287920,NC(=O)c1cnc(N[C@H]2CCCNC2)c2cc(-c3ccccc3)sc12,77.62,Rattus norvegicus

NC(=O)c1cncc(-c2ccc([C@H]3CC[C@H](CC(=O)O)CC3)cc2)n1

,Drug_ID,SMILES,Y,Species
552,CHEMBL2178952,NC(=O)c1cncc(-c2ccc([C@H]3CC[C@H](CC(=O)O)CC3)...,96.50,Homo sapiens
2148,CHEMBL2178952,NC(=O)c1cncc(-c2ccc([C@H]3CC[C@H](CC(=O)O)CC3)...,99.37,Rattus norvegicus

NC(=O)c1cncc(-c2ccc([C@H]3CC[C@H](CCO)CC3)cc2)n1

,Drug_ID,SMILES,Y,Species
651,CHEMBL2178934,NC(=O)c1cncc(-c2ccc([C@H]3CC[C@H](CCO)CC3)cc2)n1,97.2,Homo sapiens
2684,CHEMBL2178934,NC(=O)c1cncc(-c2ccc([C@H]3CC[C@H](CCO)CC3)cc2)n1,98.7,Rattus norvegicus

NC1=NC(c2cccc(-c3cncnc3)c2)(c2ccnc(C(F)(F)F)c2)c2cccc(F)c21

,Drug_ID,SMILES,Y,Species
623,CHEMBL2177906,NC1=NC(c2cccc(-c3cncnc3)c2)(c2ccnc(C(F)(F)F)c2...,95.43,Homo sapiens
1949,CHEMBL2177906,NC1=NC(c2cccc(-c3cncnc3)c2)(c2ccnc(C(F)(F)F)c2...,95.91,Mus musculus

NC1=NC(c2cccc(-c3cncnc3)c2)(c2ccnc(C3CC3)c2)c2cccc(F)c21

,Drug_ID,SMILES,Y,Species
1911,CHEMBL2177113,NC1=NC(c2cccc(-c3cncnc3)c2)(c2ccnc(C3CC3)c2)c2...,98.51,Homo sapiens
2082,CHEMBL2177113,NC1=NC(c2cccc(-c3cncnc3)c2)(c2ccnc(C3CC3)c2)c2...,97.20,Mus musculus

NC1=NC(c2ccnc(C(F)(F)F)c2)(c2ccc(F)c(-c3cncnc3)c2)c2cccc(F)c21

,Drug_ID,SMILES,Y,Species
1690,CHEMBL2177908,NC1=NC(c2ccnc(C(F)(F)F)c2)(c2ccc(F)c(-c3cncnc3...,97.07,Homo sapiens
1963,CHEMBL2177908,NC1=NC(c2ccnc(C(F)(F)F)c2)(c2ccc(F)c(-c3cncnc3...,95.91,Mus musculus

NC1C2CN(c3nc4c(cc3F)c(=O)c(C(=O)O)cn4-c3ccc(F)cc3F)CC12

,Drug_ID,SMILES,Y,Species
154,CHEMBL1624529,NC1C2CN(c3nc4c(cc3F)c(=O)c(C(=O)O)cn4-c3ccc(F)...,71.99,Canis lupus familiaris
2180,CHEMBL1624529,NC1C2CN(c3nc4c(cc3F)c(=O)c(C(=O)O)cn4-c3ccc(F)...,91.64,Rattus norvegicus

NS(=O)(=O)c1cc(C(=O)O)c(NCc2ccco2)cc1Cl

,Drug_ID,SMILES,Y,Species
87,CHEMBL35,NS(=O)(=O)c1cc(C(=O)O)c(NCc2ccco2)cc1Cl,96.93,Canis lupus familiaris
1659,CHEMBL35,NS(=O)(=O)c1cc(C(=O)O)c(NCc2ccco2)cc1Cl,98.37,Homo sapiens
2604,CHEMBL35,NS(=O)(=O)c1cc(C(=O)O)c(NCc2ccco2)cc1Cl,97.95,Rattus norvegicus

N[C@@H](CC(=O)N1CCn2c(nnc2C(F)(F)F)C1)Cc1cc(F)c(F)cc1F

,Drug_ID,SMILES,Y,Species
502,CHEMBL1422,N[C@@H](CC(=O)N1CCn2c(nnc2C(F)(F)F)C1)Cc1cc(F)...,23.19,Homo sapiens
2094,CHEMBL1422,N[C@@H](CC(=O)N1CCn2c(nnc2C(F)(F)F)C1)Cc1cc(F)...,28.95,Mus musculus
2367,CHEMBL1422,N[C@@H](CC(=O)N1CCn2c(nnc2C(F)(F)F)C1)Cc1cc(F)...,21.99,Rattus norvegicus

N[C@H]1CCN(c2c(Cl)cccc2/C=C2\SC(=O)NC2=O)C1

,Drug_ID,SMILES,Y,Species
135,CHEMBL2048863,N[C@H]1CCN(c2c(Cl)cccc2/C=C2\SC(=O)NC2=O)C1,94.19,Canis lupus familiaris
1072,CHEMBL2048863,N[C@H]1CCN(c2c(Cl)cccc2/C=C2\SC(=O)NC2=O)C1,97.66,Homo sapiens
2389,CHEMBL2048863,N[C@H]1CCN(c2c(Cl)cccc2/C=C2\SC(=O)NC2=O)C1,95.33,Rattus norvegicus

Nc1[nH]ncc1-c1cc(Cl)ccc1Oc1cc(F)c(S(=O)(=O)Nc2cscn2)cc1Cl

,Drug_ID,SMILES,Y,Species
31,CHEMBL2325014,Nc1[nH]ncc1-c1cc(Cl)ccc1Oc1cc(F)c(S(=O)(=O)Nc2...,99.52,Canis lupus familiaris
759,CHEMBL2325014,Nc1[nH]ncc1-c1cc(Cl)ccc1Oc1cc(F)c(S(=O)(=O)Nc2...,99.76,Homo sapiens
2346,CHEMBL2325014,Nc1[nH]ncc1-c1cc(Cl)ccc1Oc1cc(F)c(S(=O)(=O)Nc2...,99.45,Rattus norvegicus

Nc1n[nH]cc1-c1cc(C(F)(F)F)ccc1Oc1cc(F)c(S(=O)(=O)Nc2cscn2)cc1Cl

,Drug_ID,SMILES,Y,Species
1249,CHEMBL2325601,Nc1n[nH]cc1-c1cc(C(F)(F)F)ccc1Oc1cc(F)c(S(=O)(...,99.66,Homo sapiens
2276,CHEMBL2325601,Nc1n[nH]cc1-c1cc(C(F)(F)F)ccc1Oc1cc(F)c(S(=O)(...,99.28,Rattus norvegicus

Nc1nc(-c2nn(Cc3ccccc3F)c3ncccc23)nc(N)c1N1CCOCC1

,Drug_ID,SMILES,Y,Species
1222,CHEMBL1916024,Nc1nc(-c2nn(Cc3ccccc3F)c3ncccc23)nc(N)c1N1CCOCC1,92.32,Homo sapiens
2259,CHEMBL1916024,Nc1nc(-c2nn(Cc3ccccc3F)c3ncccc23)nc(N)c1N1CCOCC1,88.35,Rattus norvegicus

Nc1nc(O)c(Cl)c(-c2ccccc2)n1

           Drug_ID                       SMILES      Y            Species
1129  CHEMBL301856  Nc1nc(O)c(Cl)c(-c2ccccc2)n1  95.23       Homo sapiens
2510  CHEMBL301856  Nc1nc(O)c(Cl)c(-c2ccccc2)n1  93.39  Rattus norvegicus

Nc1nc(O)c2ncn(COCCO)c2n1

        Drug_ID                    SMILES      Y                 Species
101   CHEMBL184  Nc1nc(O)c2ncn(COCCO)c2n1  25.75  Canis lupus familiaris
2507  CHEMBL184  Nc1nc(O)c2ncn(COCCO)c2n1  10.09       Rattus norvegicus

Nc1nc2ccc(F)cc2s1

          Drug_ID             SMILES      Y            Species
1677  CHEMBL98406  Nc1nc2ccc(F)cc2s1  84.00       Homo sapiens
2452  CHEMBL98406  Nc1nc2ccc(F)cc2s1  75.12  Rattus norvegicus

Nc1nnc(-c2cccc(Cl)c2Cl)c(N)n1

        Drug_ID                         SMILES      Y            Species
1559  CHEMBL741  Nc1nnc(-c2cccc(Cl)c2Cl)c(N)n1  55.73       Homo sapiens
2172  CHEMBL741  Nc1nnc(-c2cccc(Cl)c2Cl)c(N)n1  48.85  Rattus norvegicus

Nc1scc2c(C(=O)NC3CC3)nn(-c3ccc(Cl)cc3)c(=O)c12

,Drug_ID,SMILES,Y,Species
387,CHEMBL1096418,Nc1scc2c(C(=O)NC3CC3)nn(-c3ccc(Cl)cc3)c(=O)c12,98.21,Homo sapiens
2037,CHEMBL1096418,Nc1scc2c(C(=O)NC3CC3)nn(-c3ccc(Cl)cc3)c(=O)c12,96.79,Mus musculus

Nc1scc2c(C(=O)NC3CC3)nn(-c3ccc(F)cc3)c(=O)c12

,Drug_ID,SMILES,Y,Species
510,CHEMBL2058280,Nc1scc2c(C(=O)NC3CC3)nn(-c3ccc(F)cc3)c(=O)c12,93.10,Homo sapiens
1993,CHEMBL2058280,Nc1scc2c(C(=O)NC3CC3)nn(-c3ccc(F)cc3)c(=O)c12,89.05,Mus musculus

O=C(CC(c1ccccc1)c1ccccc1)N1CCN(C(c2ccccc2)c2ccccc2)CC1

,Drug_ID,SMILES,Y,Species
766,CHEMBL604710,O=C(CC(c1ccccc1)c1ccccc1)N1CCN(C(c2ccccc2)c2cc...,99.9,Homo sapiens
2388,CHEMBL604710,O=C(CC(c1ccccc1)c1ccccc1)N1CCN(C(c2ccccc2)c2cc...,50.0,Rattus norvegicus

O=C(CC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cc3)c2)CC1)NC(c1ccncc1)c1ccc(Cl)cc1

,Drug_ID,SMILES,Y,Species
453,CHEMBL551924,O=C(CC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cc3)c2)CC1)N...,98.70,Homo sapiens
2090,CHEMBL551924,O=C(CC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cc3)c2)CC1)N...,99.49,Mus musculus

O=C(CC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)NC(c1ccc(F)cc1)c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
61,CHEMBL538936,O=C(CC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)N...,99.60,Canis lupus familiaris
292,CHEMBL538936,O=C(CC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)N...,98.70,Cavia porcellus
426,CHEMBL538936,O=C(CC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)N...,99.47,Homo sapiens
2623,CHEMBL538936,O=C(CC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)N...,99.67,Rattus norvegicus

O=C(CCCN1CCC(O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
861,CHEMBL54,O=C(CCCN1CCC(O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1,85.48,Homo sapiens
2119,CHEMBL54,O=C(CCCN1CCC(O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1,81.36,Rattus norvegicus

O=C(CCCN1CCC(O)(c2cccc(C(F)(F)F)c2)CC1)c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
1582,CHEMBL15023,O=C(CCCN1CCC(O)(c2cccc(C(F)(F)F)c2)CC1)c1ccc(F...,92.32,Homo sapiens
2261,CHEMBL15023,O=C(CCCN1CCC(O)(c2cccc(C(F)(F)F)c2)CC1)c1ccc(F...,89.05,Rattus norvegicus

O=C(CCCN1CC[Si](O)(c2cccc(C(F)(F)F)c2)CC1)c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
1650,CHEMBL2204344,O=C(CCCN1CC[Si](O)(c2cccc(C(F)(F)F)c2)CC1)c1cc...,95.91,Homo sapiens
2340,CHEMBL2204344,O=C(CCCN1CC[Si](O)(c2cccc(C(F)(F)F)c2)CC1)c1cc...,95.53,Rattus norvegicus

O=C(CCCc1ccc2cccnc2n1)NCc1cc(-c2ccc(F)c(C(F)(F)F)c2)no1

,Drug_ID,SMILES,Y,Species
1512,CHEMBL2153581,O=C(CCCc1ccc2cccnc2n1)NCc1cc(-c2ccc(F)c(C(F)(F...,99.91,Homo sapiens
2742,CHEMBL2153581,O=C(CCCc1ccc2cccnc2n1)NCc1cc(-c2ccc(F)c(C(F)(F...,98.81,Rattus norvegicus

O=C(CN1CCN(CCC2CCOCC2)CC1)NC12CC3CC(CC(C3)C1)C2

,Drug_ID,SMILES,Y,Species
105,CHEMBL2337982,O=C(CN1CCN(CCC2CCOCC2)CC1)NC12CC3CC(CC(C3)C1)C2,56.86,Canis lupus familiaris
576,CHEMBL2337982,O=C(CN1CCN(CCC2CCOCC2)CC1)NC12CC3CC(CC(C3)C1)C2,47.12,Homo sapiens
2568,CHEMBL2337982,O=C(CN1CCN(CCC2CCOCC2)CC1)NC12CC3CC(CC(C3)C1)C2,60.77,Rattus norvegicus

O=C(CN1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)NC(c1ccc(F)cc1)c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
185,CHEMBL541944,O=C(CN1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)N...,99.94,Canis lupus familiaris
1498,CHEMBL541944,O=C(CN1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)N...,99.86,Homo sapiens
2106,CHEMBL541944,O=C(CN1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)N...,99.87,Mus musculus
2611,CHEMBL541944,O=C(CN1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cn3)c2)CC1)N...,99.89,Rattus norvegicus

O=C(CO)N1CCC(c2[nH]nc(-c3ccc(Cl)cc3F)c2-c2ccncn2)CC1

,Drug_ID,SMILES,Y,Species
975,CHEMBL1614705,O=C(CO)N1CCC(c2[nH]nc(-c3ccc(Cl)cc3F)c2-c2ccnc...,74.69,Homo sapiens
2593,CHEMBL1614705,O=C(CO)N1CCC(c2[nH]nc(-c3ccc(Cl)cc3F)c2-c2ccnc...,67.63,Rattus norvegicus

O=C(Cc1ccc(Cl)c(C(F)(F)F)c1)Nc1cccc2c(=O)n(CCO)ccc12

,Drug_ID,SMILES,Y,Species
970,CHEMBL560219,O=C(Cc1ccc(Cl)c(C(F)(F)F)c1)Nc1cccc2c(=O)n(CCO...,99.03,Homo sapiens
2703,CHEMBL560219,O=C(Cc1ccc(Cl)c(C(F)(F)F)c1)Nc1cccc2c(=O)n(CCO...,92.80,Rattus norvegicus

O=C(Cn1c(Cl)cnc(NCC(F)(F)c2ccccn2)c1=O)NCc1ncccc1F

,Drug_ID,SMILES,Y,Species
6,CHEMBL30054,O=C(Cn1c(Cl)cnc(NCC(F)(F)c2ccccn2)c1=O)NCc1ncc...,60.77,Canis lupus familiaris
893,CHEMBL30054,O=C(Cn1c(Cl)cnc(NCC(F)(F)c2ccccn2)c1=O)NCc1ncc...,71.99,Homo sapiens
2292,CHEMBL30054,O=C(Cn1c(Cl)cnc(NCC(F)(F)c2ccccn2)c1=O)NCc1ncc...,79.17,Rattus norvegicus

O=C(NC12CC3CC(CC(C3)C1)C2)OCCNC1CCCCC1

,Drug_ID,SMILES,Y,Species
57,CHEMBL1625921,O=C(NC12CC3CC(CC(C3)C1)C2)OCCNC1CCCCC1,84.00,Canis lupus familiaris
1363,CHEMBL1625921,O=C(NC12CC3CC(CC(C3)C1)C2)OCCNC1CCCCC1,89.05,Homo sapiens
2196,CHEMBL1625921,O=C(NC12CC3CC(CC(C3)C1)C2)OCCNC1CCCCC1,87.11,Rattus norvegicus

O=C(NC1CC1)c1cn(-c2cccc(C#Cc3cccnc3)c2)c2ncccc2c1=O

,Drug_ID,SMILES,Y,Species
1233,CHEMBL521509,O=C(NC1CC1)c1cn(-c2cccc(C#Cc3cccnc3)c2)c2ncccc...,98.33,Homo sapiens
2691,CHEMBL521509,O=C(NC1CC1)c1cn(-c2cccc(C#Cc3cccnc3)c2)c2ncccc...,99.18,Rattus norvegicus

O=C(NCC1(O)CCCCCC1)c1cc(-c2ccccc2C(=O)O)ccc1Cl

,Drug_ID,SMILES,Y,Species
772,CHEMBL564737,O=C(NCC1(O)CCCCCC1)c1cc(-c2ccccc2C(=O)O)ccc1Cl,91.10,Homo sapiens
2151,CHEMBL564737,O=C(NCC1(O)CCCCCC1)c1cc(-c2ccccc2C(=O)O)ccc1Cl,90.91,Rattus norvegicus

O=C(NCC1(O)CCCCCC1)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl

,Drug_ID,SMILES,Y,Species
902,CHEMBL560423,O=C(NCC1(O)CCCCCC1)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl,75.97,Homo sapiens
2648,CHEMBL560423,O=C(NCC1(O)CCCCCC1)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl,87.11,Rattus norvegicus

O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl

,Drug_ID,SMILES,Y,Species
999,CHEMBL551170,O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(-n2ncc(=O)[nH]...,98.13,Homo sapiens
2251,CHEMBL551170,O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(-n2ncc(=O)[nH]...,98.29,Rattus norvegicus

O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(CN2CCNCC2)ccc1Cl

,Drug_ID,SMILES,Y,Species
178,CHEMBL235789,O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(CN2CCNCC2)ccc1Cl,84.30,Canis lupus familiaris
1037,CHEMBL235789,O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(CN2CCNCC2)ccc1Cl,91.28,Homo sapiens
2309,CHEMBL235789,O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(CN2CCNCC2)ccc1Cl,93.80,Rattus norvegicus

O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(CN2C[C@@H]3C[C@H]2CN3)ccc1Cl

,Drug_ID,SMILES,Y,Species
146,CHEMBL392559,O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(CN2C[C@@H]3C[C...,88.59,Canis lupus familiaris
1478,CHEMBL392559,O=C(NCC12CC3CC(CC(C3)C1)C2)c1cc(CN2C[C@@H]3C[C...,90.32,Homo sapiens

O=C(NCC1CCCCN1)c1cc(OCC(F)(F)F)ccc1OCC(F)(F)F

,Drug_ID,SMILES,Y,Species
325,CHEMBL652,O=C(NCC1CCCCN1)c1cc(OCC(F)(F)F)ccc1OCC(F)(F)F,42.57,Cavia porcellus
1001,CHEMBL652,O=C(NCC1CCCCN1)c1cc(OCC(F)(F)F)ccc1OCC(F)(F)F,38.14,Homo sapiens
2234,CHEMBL652,O=C(NCC1CCCCN1)c1cc(OCC(F)(F)F)ccc1OCC(F)(F)F,46.55,Rattus norvegicus

O=C(NCCc1ccccc1)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl

,Drug_ID,SMILES,Y,Species
1561,CHEMBL1779503,O=C(NCCc1ccccc1)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl,97.49,Homo sapiens
2271,CHEMBL1779503,O=C(NCCc1ccccc1)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl,96.09,Rattus norvegicus

O=C(NCCc1ccccc1Cl)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl

,Drug_ID,SMILES,Y,Species
1765,CHEMBL559968,O=C(NCCc1ccccc1Cl)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl,97.20,Homo sapiens
2454,CHEMBL559968,O=C(NCCc1ccccc1Cl)c1cc(-n2ncc(=O)[nH]c2=O)ccc1Cl,97.76,Rattus norvegicus

O=C(NC[C@@H](O)CN1CCC(Oc2ccc(Cl)c(Cl)c2)CC1)c1c[nH]c(=O)c2ccccc12

,Drug_ID,SMILES,Y,Species
71,CHEMBL2207666,O=C(NC[C@@H](O)CN1CCC(Oc2ccc(Cl)c(Cl)c2)CC1)c1...,97.71,Canis lupus familiaris
246,CHEMBL2207666,O=C(NC[C@@H](O)CN1CCC(Oc2ccc(Cl)c(Cl)c2)CC1)c1...,98.37,Cavia porcellus
842,CHEMBL2207666,O=C(NC[C@@H](O)CN1CCC(Oc2ccc(Cl)c(Cl)c2)CC1)c1...,98.17,Homo sapiens

O=C(NCc1ccc(F)c(C(F)(F)F)c1)C1c2ccccc2C(=O)N1CCc1ncc(F)cn1

,Drug_ID,SMILES,Y,Species
1740,CHEMBL2164044,O=C(NCc1ccc(F)c(C(F)(F)F)c1)C1c2ccccc2C(=O)N1C...,95.23,Homo sapiens
2547,CHEMBL2164044,O=C(NCc1ccc(F)c(C(F)(F)F)c1)C1c2ccccc2C(=O)N1C...,87.11,Rattus norvegicus

O=C(NCc1ccc(F)c(OC(F)(F)F)c1)C1c2ccccc2C(=O)N1CCc1ncc(F)cn1

,Drug_ID,SMILES,Y,Species
1250,CHEMBL2164043,O=C(NCc1ccc(F)c(OC(F)(F)F)c1)C1c2ccccc2C(=O)N1...,96.79,Homo sapiens
2229,CHEMBL2164043,O=C(NCc1ccc(F)c(OC(F)(F)F)c1)C1c2ccccc2C(=O)N1...,90.12,Rattus norvegicus

O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2cccc(O)c2C(=O)N1CCc1ncc(F)cn1

,Drug_ID,SMILES,Y,Species
1436,CHEMBL2164045,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2cccc(O)c2C(=O)N1...,98.21,Homo sapiens
2404,CHEMBL2164045,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2cccc(O)c2C(=O)N1...,95.82,Rattus norvegicus

O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C1CCC(F)(F)CC1

,Drug_ID,SMILES,Y,Species
1656,CHEMBL2164373,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C1C...,98.00,Homo sapiens
2727,CHEMBL2164373,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C1C...,96.57,Rattus norvegicus

O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C1CCOCC1

,Drug_ID,SMILES,Y,Species
914,CHEMBL2164371,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C1C...,90.52,Homo sapiens
2299,CHEMBL2164371,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C1C...,86.85,Rattus norvegicus

O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc1ccccn1

,Drug_ID,SMILES,Y,Species
807,CHEMBL2164389,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc...,96.42,Homo sapiens
2603,CHEMBL2164389,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc...,95.53,Rattus norvegicus

O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc1ncc(F)cn1

,Drug_ID,SMILES,Y,Species
1299,CHEMBL2164366,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc...,95.23,Homo sapiens
2137,CHEMBL2164366,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc...,90.72,Rattus norvegicus

O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc1ncccn1

,Drug_ID,SMILES,Y,Species
1590,CHEMBL2164364,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc...,91.82,Homo sapiens
2138,CHEMBL2164364,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1CCc...,87.11,Rattus norvegicus

O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C[C@@H]1CCCO1

,Drug_ID,SMILES,Y,Species
1422,CHEMBL2164372,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C[C...,96.42,Homo sapiens
2759,CHEMBL2164372,O=C(NCc1ccc(OC(F)(F)F)cc1)C1c2ccccc2C(=O)N1C[C...,93.94,Rattus norvegicus

O=C(NCc1ccc(OCC(F)(F)F)nc1)C1c2ccccc2C(=O)N1CCc1ccccn1

,Drug_ID,SMILES,Y,Species
1624,CHEMBL2164395,O=C(NCc1ccc(OCC(F)(F)F)nc1)C1c2ccccc2C(=O)N1CC...,90.72,Homo sapiens
2457,CHEMBL2164395,O=C(NCc1ccc(OCC(F)(F)F)nc1)C1c2ccccc2C(=O)N1CC...,62.94,Rattus norvegicus

O=C(NCc1cccc(F)c1)NC1CCN(Cc2ccn(-c3ccc(C(F)(F)F)cc3)c2)CC1

,Drug_ID,SMILES,Y,Species
167,CHEMBL550410,O=C(NCc1cccc(F)c1)NC1CCN(Cc2ccn(-c3ccc(C(F)(F)...,97.81,Canis lupus familiaris
318,CHEMBL550410,O=C(NCc1cccc(F)c1)NC1CCN(Cc2ccn(-c3ccc(C(F)(F)...,94.32,Cavia porcellus
1859,CHEMBL550410,O=C(NCc1cccc(F)c1)NC1CCN(Cc2ccn(-c3ccc(C(F)(F)...,97.32,Homo sapiens
2177,CHEMBL550410,O=C(NCc1cccc(F)c1)NC1CCN(Cc2ccn(-c3ccc(C(F)(F)...,97.76,Rattus norvegicus

O=C(NCc1cccc(OC(F)(F)F)c1)C1c2ccccc2C(=O)N1CCc1ncc(F)cn1

,Drug_ID,SMILES,Y,Species
1809,CHEMBL2164042,O=C(NCc1cccc(OC(F)(F)F)c1)C1c2ccccc2C(=O)N1CCc...,95.53,Homo sapiens
2689,CHEMBL2164042,O=C(NCc1cccc(OC(F)(F)F)c1)C1c2ccccc2C(=O)N1CCc...,82.05,Rattus norvegicus

O=C(NCc1ccccn1)c1cc(-c2ccccc2)nc2ccccc12

,Drug_ID,SMILES,Y,Species
440,CHEMBL1277809,O=C(NCc1ccccn1)c1cc(-c2ccccc2)nc2ccccc12,98.7,Homo sapiens
2657,CHEMBL1277809,O=C(NCc1ccccn1)c1cc(-c2ccccc2)nc2ccccc12,98.0,Rattus norvegicus

O=C(N[C@@H]1COc2cccc(-c3ccc(CO)nc3)c2C1)c1ccc(OCC(F)(F)F)nc1

,Drug_ID,SMILES,Y,Species
91,CHEMBL2069411,O=C(N[C@@H]1COc2cccc(-c3ccc(CO)nc3)c2C1)c1ccc(...,95.23,Canis lupus familiaris
270,CHEMBL2069411,O=C(N[C@@H]1COc2cccc(-c3ccc(CO)nc3)c2C1)c1ccc(...,89.05,Cavia porcellus
1463,CHEMBL2069411,O=C(N[C@@H]1COc2cccc(-c3ccc(CO)nc3)c2C1)c1ccc(...,96.26,Homo sapiens
2793,CHEMBL2069411,O=C(N[C@@H]1COc2cccc(-c3ccc(CO)nc3)c2C1)c1ccc(...,92.48,Rattus norvegicus

O=C(N[C@@H]1COc2cccc(-c3ccc(CO)nc3)c2C1)c1ccc(OCCOCC(F)(F)F)nc1

,Drug_ID,SMILES,Y,Species
1592,CHEMBL2069413,O=C(N[C@@H]1COc2cccc(-c3ccc(CO)nc3)c2C1)c1ccc(...,95.91,Homo sapiens
2485,CHEMBL2069413,O=C(N[C@@H]1COc2cccc(-c3ccc(CO)nc3)c2C1)c1ccc(...,91.10,Rattus norvegicus

O=C(N[C@H](Cc1ccc(Cl)cc1)C(=O)N1CCC(Cn2cncn2)(C2CCCCC2)CC1)[C@H]1Cc2ccccc2CN1

,Drug_ID,SMILES,Y,Species
838,CHEMBL339053,O=C(N[C@H](Cc1ccc(Cl)cc1)C(=O)N1CCC(Cn2cncn2)(...,99.30,Homo sapiens
2307,CHEMBL339053,O=C(N[C@H](Cc1ccc(Cl)cc1)C(=O)N1CCC(Cn2cncn2)(...,99.48,Rattus norvegicus

O=C(Nc1c(Cl)cncc1Cl)c1ccc(OC(F)F)c(OCC2CC2)c1

,Drug_ID,SMILES,Y,Species
1138,CHEMBL193240,O=C(Nc1c(Cl)cncc1Cl)c1ccc(OC(F)F)c(OCC2CC2)c1,99.50,Homo sapiens
2337,CHEMBL193240,O=C(Nc1c(Cl)cncc1Cl)c1ccc(OC(F)F)c(OCC2CC2)c1,98.86,Rattus norvegicus

O=C(Nc1ccc(CN2CCNCC2)cc1-c1nc2ccccc2[nH]1)c1cnc2ccccc2n1

,Drug_ID,SMILES,Y,Species
811,CHEMBL482552,O=C(Nc1ccc(CN2CCNCC2)cc1-c1nc2ccccc2[nH]1)c1cn...,99.91,Homo sapiens
2085,CHEMBL482552,O=C(Nc1ccc(CN2CCNCC2)cc1-c1nc2ccccc2[nH]1)c1cn...,99.67,Mus musculus
2559,CHEMBL482552,O=C(Nc1ccc(CN2CCNCC2)cc1-c1nc2ccccc2[nH]1)c1cn...,91.99,Rattus norvegicus

O=C(Nc1ccc(Cl)c(C(=O)Nc2cccnc2)c1)c1cccc(C(F)(F)F)c1

,Drug_ID,SMILES,Y,Species
610,CHEMBL510386,O=C(Nc1ccc(Cl)c(C(=O)Nc2cccnc2)c1)c1cccc(C(F)(...,99.70,Homo sapiens
2015,CHEMBL510386,O=C(Nc1ccc(Cl)c(C(=O)Nc2cccnc2)c1)c1cccc(C(F)(...,98.81,Mus musculus

O=C(Nc1ccc(Cl)c(S(=O)(=O)N2CCNCC2)c1O)Nc1cccc(F)c1Cl

,Drug_ID,SMILES,Y,Species
228,CHEMBL2178579,O=C(Nc1ccc(Cl)c(S(=O)(=O)N2CCNCC2)c1O)Nc1cccc(...,98.73,Canis lupus familiaris
1164,CHEMBL2178579,O=C(Nc1ccc(Cl)c(S(=O)(=O)N2CCNCC2)c1O)Nc1cccc(...,99.71,Homo sapiens
2176,CHEMBL2178579,O=C(Nc1ccc(Cl)c(S(=O)(=O)N2CCNCC2)c1O)Nc1cccc(...,98.94,Rattus norvegicus

O=C(Nc1ccc(Cl)nc1)c1ccc(F)c(F)c1

           Drug_ID                            SMILES      Y            Species
921   CHEMBL402146  O=C(Nc1ccc(Cl)nc1)c1ccc(F)c(F)c1  90.72       Homo sapiens
2535  CHEMBL402146  O=C(Nc1ccc(Cl)nc1)c1ccc(F)c(F)c1  88.11  Rattus norvegicus

O=C(Nc1ccc(N2CCNCC2)cc1)c1ccc(-c2ccc(Cl)cc2)o1

,Drug_ID,SMILES,Y,Species
724,CHEMBL1938680,O=C(Nc1ccc(N2CCNCC2)cc1)c1ccc(-c2ccc(Cl)cc2)o1,97.32,Homo sapiens
2021,CHEMBL1938680,O=C(Nc1ccc(N2CCNCC2)cc1)c1ccc(-c2ccc(Cl)cc2)o1,97.00,Mus musculus
2711,CHEMBL1938680,O=C(Nc1ccc(N2CCNCC2)cc1)c1ccc(-c2ccc(Cl)cc2)o1,99.45,Rattus norvegicus

O=C(Nc1cccc(Cl)c1)Nc1nnc(-c2ccncc2)s1

,Drug_ID,SMILES,Y,Species
605,CHEMBL1387923,O=C(Nc1cccc(Cl)c1)Nc1nnc(-c2ccncc2)s1,99.80,Homo sapiens
2139,CHEMBL1387923,O=C(Nc1cccc(Cl)c1)Nc1nnc(-c2ccncc2)s1,99.54,Rattus norvegicus

O=C(Nc1ccccc1-c1ccccc1)OC1CCN(CCCCCCCCCNC[C@H](O)c2ccc(O)c3[nH]c(=O)ccc23)CC1

,Drug_ID,SMILES,Y,Species
317,CHEMBL1683934,O=C(Nc1ccccc1-c1ccccc1)OC1CCN(CCCCCCCCCNC[C@H]...,91.82,Cavia porcellus
869,CHEMBL1683934,O=C(Nc1ccccc1-c1ccccc1)OC1CCN(CCCCCCCCCNC[C@H]...,88.11,Homo sapiens

O=C(Nc1ccccc1F)N[C@H]1N=C(c2ccccc2)c2ccccc2NC1=O

,Drug_ID,SMILES,Y,Species
132,CHEMBL223402,O=C(Nc1ccccc1F)N[C@H]1N=C(c2ccccc2)c2ccccc2NC1=O,96.93,Canis lupus familiaris
1930,CHEMBL223402,O=C(Nc1ccccc1F)N[C@H]1N=C(c2ccccc2)c2ccccc2NC1=O,96.34,Homo sapiens
2702,CHEMBL223402,O=C(Nc1ccccc1F)N[C@H]1N=C(c2ccccc2)c2ccccc2NC1=O,97.26,Rattus norvegicus

O=C(O)CCc1nc(-c2ccccc2)c(-c2ccccc2)o1

,Drug_ID,SMILES,Y,Species
1620,CHEMBL1071,O=C(O)CCc1nc(-c2ccccc2)c(-c2ccccc2)o1,99.95,Homo sapiens
2478,CHEMBL1071,O=C(O)CCc1nc(-c2ccccc2)c(-c2ccccc2)o1,99.76,Rattus norvegicus

O=C(O)CCn1c2c(c3ccccc31)C[C@H](NS(=O)(=O)c1ccc(F)cc1)CC2

,Drug_ID,SMILES,Y,Species
114,CHEMBL361812,O=C(O)CCn1c2c(c3ccccc31)C[C@H](NS(=O)(=O)c1ccc...,95.63,Canis lupus familiaris
544,CHEMBL361812,O=C(O)CCn1c2c(c3ccccc31)C[C@H](NS(=O)(=O)c1ccc...,97.26,Homo sapiens
2729,CHEMBL361812,O=C(O)CCn1c2c(c3ccccc31)C[C@H](NS(=O)(=O)c1ccc...,96.72,Rattus norvegicus

O=C(O)CNC(=O)c1ncccc1O

            Drug_ID                  SMILES      Y            Species
891   CHEMBL1256568  O=C(O)CNC(=O)c1ncccc1O  76.81       Homo sapiens
2197  CHEMBL1256568  O=C(O)CNC(=O)c1ncccc1O  75.97  Rattus norvegicus

O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1

,Drug_ID,SMILES,Y,Species
43,CHEMBL1000,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,90.12,Canis lupus familiaris
297,CHEMBL1000,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,40.34,Cavia porcellus
411,CHEMBL1000,O=C(O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,81.01,Homo sapiens

O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)Cc2ccccc2)CC1

,Drug_ID,SMILES,Y,Species
217,CHEMBL1689111,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)Cc2ccccc2)CC1,96.57,Canis lupus familiaris
372,CHEMBL1689111,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)Cc2ccccc2)CC1,99.33,Homo sapiens
2267,CHEMBL1689111,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)Cc2ccccc2)CC1,88.59,Rattus norvegicus

O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)c2ccc(F)cc2)CC1

,Drug_ID,SMILES,Y,Species
136,CHEMBL1689117,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)c2ccc(F)cc...,92.32,Canis lupus familiaris
363,CHEMBL1689117,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)c2ccc(F)cc...,98.99,Homo sapiens
2252,CHEMBL1689117,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)c2ccc(F)cc...,91.10,Rattus norvegicus

O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)c2ccccc2)CC1

,Drug_ID,SMILES,Y,Species
98,CHEMBL1689109,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)c2ccccc2)CC1,96.00,Canis lupus familiaris
626,CHEMBL1689109,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)c2ccccc2)CC1,96.17,Homo sapiens
2518,CHEMBL1689109,O=C(O)COc1ccc(Cl)cc1CN1CCN(S(=O)(=O)c2ccccc2)CC1,86.85,Rattus norvegicus

O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
241,CHEMBL1201753,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2cccc...,97.07,Canis lupus familiaris
1334,CHEMBL1201753,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2cccc...,98.00,Homo sapiens
2558,CHEMBL1201753,O=C(O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2cccc...,99.36,Rattus norvegicus

O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl

        Drug_ID                          SMILES      Y            Species
1472  CHEMBL139  O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl  99.68       Homo sapiens
2431  CHEMBL139  O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl  99.28  Rattus norvegicus

O=C(O)[C@H](Cc1ccc(F)cc1)N1CCC(CN2CCC(Oc3ccc(Cl)c(Cl)c3)CC2)CC1

,Drug_ID,SMILES,Y,Species
58,CHEMBL2158841,O=C(O)[C@H](Cc1ccc(F)cc1)N1CCC(CN2CCC(Oc3ccc(C...,77.62,Canis lupus familiaris
1024,CHEMBL2158841,O=C(O)[C@H](Cc1ccc(F)cc1)N1CCC(CN2CCC(Oc3ccc(C...,88.59,Homo sapiens
2423,CHEMBL2158841,O=C(O)[C@H](Cc1ccc(F)cc1)N1CCC(CN2CCC(Oc3ccc(C...,78.01,Rattus norvegicus

O=C(O)[C@H](Cc1ccccc1)N1CCC(CN2CCC(Oc3ccc(Cl)c(Cl)c3)CC2)CC1

,Drug_ID,SMILES,Y,Species
205,CHEMBL2158835,O=C(O)[C@H](Cc1ccccc1)N1CCC(CN2CCC(Oc3ccc(Cl)c...,89.05,Canis lupus familiaris
304,CHEMBL2158835,O=C(O)[C@H](Cc1ccccc1)N1CCC(CN2CCC(Oc3ccc(Cl)c...,42.01,Cavia porcellus
2002,CHEMBL2158835,O=C(O)[C@H](Cc1ccccc1)N1CCC(CN2CCC(Oc3ccc(Cl)c...,84.60,Mus musculus
2566,CHEMBL2158835,O=C(O)[C@H](Cc1ccccc1)N1CCC(CN2CCC(Oc3ccc(Cl)c...,81.71,Rattus norvegicus

O=C(O)c1c(O)c(Cc2ccc(Cl)cc2)nc2c3c(ccc12)CCCC3

,Drug_ID,SMILES,Y,Species
595,CHEMBL219046,O=C(O)c1c(O)c(Cc2ccc(Cl)cc2)nc2c3c(ccc12)CCCC3,99.93,Homo sapiens
2204,CHEMBL219046,O=C(O)c1c(O)c(Cc2ccc(Cl)cc2)nc2c3c(ccc12)CCCC3,99.86,Rattus norvegicus

O=C(O)c1cc(-c2ccc(F)cc2F)ccc1O

        Drug_ID                          SMILES      Y            Species
1486  CHEMBL898  O=C(O)c1cc(-c2ccc(F)cc2F)ccc1O  99.79       Homo sapiens
2435  CHEMBL898  O=C(O)c1cc(-c2ccc(F)cc2F)ccc1O  99.82  Rattus norvegicus

O=C(O)c1ccc(-c2ccc(Cl)c(C(=O)NCC34CC5CC(CC(C5)C3)C4)c2)cc1

,Drug_ID,SMILES,Y,Species
1874,CHEMBL564607,O=C(O)c1ccc(-c2ccc(Cl)c(C(=O)NCC34CC5CC(CC(C5)...,99.23,Homo sapiens
2173,CHEMBL564607,O=C(O)c1ccc(-c2ccc(Cl)c(C(=O)NCC34CC5CC(CC(C5)...,99.26,Rattus norvegicus

O=C(O)c1cccnc1

        Drug_ID          SMILES      Y            Species
515   CHEMBL573  O=C(O)c1cccnc1  44.84       Homo sapiens
2236  CHEMBL573  O=C(O)c1cccnc1  45.41  Rattus norvegicus

O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O

,Drug_ID,SMILES,Y,Species
53,CHEMBL8,O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O,31.37,Canis lupus familiaris
713,CHEMBL8,O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O,34.42,Homo sapiens
2620,CHEMBL8,O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O,43.14,Rattus norvegicus

O=C(c1c2ccccc2cc2ccccc12)N1CCC(N2CCC[C@@H](C(=O)N3CCOCC3)C2)CC1

,Drug_ID,SMILES,Y,Species
198,CHEMBL208943,O=C(c1c2ccccc2cc2ccccc12)N1CCC(N2CCC[C@@H](C(=...,71.05,Canis lupus familiaris
1771,CHEMBL208943,O=C(c1c2ccccc2cc2ccccc12)N1CCC(N2CCC[C@@H](C(=...,93.39,Homo sapiens
1985,CHEMBL208943,O=C(c1c2ccccc2cc2ccccc12)N1CCC(N2CCC[C@@H](C(=...,73.36,Mus musculus
2427,CHEMBL208943,O=C(c1c2ccccc2cc2ccccc12)N1CCC(N2CCC[C@@H](C(=...,73.36,Rattus norvegicus

O=C(c1c[nH]c(=O)c2ccccc12)N1CCC(N2CCC(Oc3ccc(Cl)c(Cl)c3)CC2)CC1

,Drug_ID,SMILES,Y,Species
240,CHEMBL2171020,O=C(c1c[nH]c(=O)c2ccccc12)N1CCC(N2CCC(Oc3ccc(C...,95.12,Canis lupus familiaris
247,CHEMBL2171020,O=C(c1c[nH]c(=O)c2ccccc12)N1CCC(N2CCC(Oc3ccc(C...,83.04,Cavia porcellus
919,CHEMBL2171020,O=C(c1c[nH]c(=O)c2ccccc12)N1CCC(N2CCC(Oc3ccc(C...,91.10,Homo sapiens

O=C(c1ccc(-c2ccc(Cl)cc2)o1)N(Cc1ccccn1)c1ccc(N2CCNCC2)cc1

,Drug_ID,SMILES,Y,Species
527,CHEMBL1938681,O=C(c1ccc(-c2ccc(Cl)cc2)o1)N(Cc1ccccn1)c1ccc(N...,97.32,Homo sapiens
2232,CHEMBL1938681,O=C(c1ccc(-c2ccc(Cl)cc2)o1)N(Cc1ccccn1)c1ccc(N...,97.81,Rattus norvegicus

O=C(c1ccc(F)cc1)C1CCN(CCn2c(=O)[nH]c3ccccc3c2=O)CC1

,Drug_ID,SMILES,Y,Species
1155,CHEMBL51,O=C(c1ccc(F)cc1)C1CCN(CCn2c(=O)[nH]c3ccccc3c2=...,90.32,Homo sapiens
2471,CHEMBL51,O=C(c1ccc(F)cc1)C1CCN(CCn2c(=O)[nH]c3ccccc3c2=...,99.36,Rattus norvegicus

O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2cc(O)ccc12

,Drug_ID,SMILES,Y,Species
16,CHEMBL81,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2...,99.43,Canis lupus familiaris
362,CHEMBL81,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2...,99.50,Homo sapiens
2310,CHEMBL81,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2...,99.50,Rattus norvegicus

O=C(c1cccc(N2Cc3cccc(Cl)c3C2=O)c1)N1CCC2(CC1)CCN(c1ccncc1)CC2

,Drug_ID,SMILES,Y,Species
1059,CHEMBL1254945,O=C(c1cccc(N2Cc3cccc(Cl)c3C2=O)c1)N1CCC2(CC1)C...,99.05,Homo sapiens
2095,CHEMBL1254945,O=C(c1cccc(N2Cc3cccc(Cl)c3C2=O)c1)N1CCC2(CC1)C...,95.72,Mus musculus
2219,CHEMBL1254945,O=C(c1cccc(N2Cc3cccc(Cl)c3C2=O)c1)N1CCC2(CC1)C...,95.82,Rattus norvegicus

O=C1C(CC[S+]([O-])c2ccccc2)C(=O)N(c2ccccc2)N1c1ccccc1

,Drug_ID,SMILES,Y,Species
160,CHEMBL832,O=C1C(CC[S+]([O-])c2ccccc2)C(=O)N(c2ccccc2)N1c...,94.32,Canis lupus familiaris
345,CHEMBL832,O=C1C(CC[S+]([O-])c2ccccc2)C(=O)N(c2ccccc2)N1c...,99.31,Homo sapiens
2207,CHEMBL832,O=C1C(CC[S+]([O-])c2ccccc2)C(=O)N(c2ccccc2)N1c...,99.77,Rattus norvegicus

O=C1CC2(CCCC2)CC(=O)N1CCCCN1CCN(c2ncccn2)CC1

,Drug_ID,SMILES,Y,Species
108,CHEMBL49,O=C1CC2(CCCC2)CC(=O)N1CCCCN1CCN(c2ncccn2)CC1,67.12,Canis lupus familiaris
889,CHEMBL49,O=C1CC2(CCCC2)CC(=O)N1CCCCN1CCN(c2ncccn2)CC1,77.62,Homo sapiens
2365,CHEMBL49,O=C1CC2(CCCC2)CC(=O)N1CCCCN1CCN(c2ncccn2)CC1,75.12,Rattus norvegicus

O=C1CCc2cc(-c3cncc4ccccc34)ccc2N1

,Drug_ID,SMILES,Y,Species
684,CHEMBL456390,O=C1CCc2cc(-c3cncc4ccccc34)ccc2N1,96.42,Homo sapiens
2029,CHEMBL456390,O=C1CCc2cc(-c3cncc4ccccc34)ccc2N1,96.87,Mus musculus
2407,CHEMBL456390,O=C1CCc2cc(-c3cncc4ccccc34)ccc2N1,96.87,Rattus norvegicus

O=C1COc2c(CCNCCN(C(=O)CCNCCc3ccc(Cl)c(Cl)c3)C3CCCCC3)ccc(O)c2N1

,Drug_ID,SMILES,Y,Species
265,CHEMBL2169920,O=C1COc2c(CCNCCN(C(=O)CCNCCc3ccc(Cl)c(Cl)c3)C3...,82.72,Cavia porcellus
1388,CHEMBL2169920,O=C1COc2c(CCNCCN(C(=O)CCNCCc3ccc(Cl)c(Cl)c3)C3...,96.87,Homo sapiens
2560,CHEMBL2169920,O=C1COc2c(CCNCCN(C(=O)CCNCCc3ccc(Cl)c(Cl)c3)C3...,91.99,Rattus norvegicus

O=C1COc2nccc(-c3ccccc3F)c2CN1Cc1cc(C(F)(F)F)cc(C(F)(F)F)c1

,Drug_ID,SMILES,Y,Species
954,CHEMBL2181247,O=C1COc2nccc(-c3ccccc3F)c2CN1Cc1cc(C(F)(F)F)cc...,99.37,Homo sapiens
2075,CHEMBL2181247,O=C1COc2nccc(-c3ccccc3F)c2CN1Cc1cc(C(F)(F)F)cc...,99.05,Mus musculus
2189,CHEMBL2181247,O=C1COc2nccc(-c3ccccc3F)c2CN1Cc1cc(C(F)(F)F)cc...,99.19,Rattus norvegicus

O=C1Cc2cc(CCN3CCN(c4nsc5ccccc45)CC3)c(Cl)cc2N1

,Drug_ID,SMILES,Y,Species
1649,CHEMBL708,O=C1Cc2cc(CCN3CCN(c4nsc5ccccc45)CC3)c(Cl)cc2N1,99.9,Homo sapiens
2760,CHEMBL708,O=C1Cc2cc(CCN3CCN(c4nsc5ccccc45)CC3)c(Cl)cc2N1,99.7,Rattus norvegicus

O=C1N(c2ccccc2)c2ccccc2C1(Cc1ccncc1)Cc1ccncc1

,Drug_ID,SMILES,Y,Species
692,CHEMBL319111,O=C1N(c2ccccc2)c2ccccc2C1(Cc1ccncc1)Cc1ccncc1,99.60,Homo sapiens
2092,CHEMBL319111,O=C1N(c2ccccc2)c2ccccc2C1(Cc1ccncc1)Cc1ccncc1,82.05,Mus musculus
2289,CHEMBL319111,O=C1N(c2ccccc2)c2ccccc2C1(Cc1ccncc1)Cc1ccncc1,89.91,Rattus norvegicus

O=C1N=C(O)NC1(c1ccccc1)c1ccccc1

       Drug_ID                           SMILES      Y            Species
1117  CHEMBL16  O=C1N=C(O)NC1(c1ccccc1)c1ccccc1  87.11       Homo sapiens
2756  CHEMBL16  O=C1N=C(O)NC1(c1ccccc1)c1ccccc1  82.05  Rattus norvegicus

O=C1NC(=O)C(c2cnc3ccccn23)=C1c1cn2c3c(cccc13)CN(C(=O)N1CCOCC1)CC2

,Drug_ID,SMILES,Y,Species
1491,CHEMBL178737,O=C1NC(=O)C(c2cnc3ccccn23)=C1c1cn2c3c(cccc13)C...,85.77,Homo sapiens
2186,CHEMBL178737,O=C1NC(=O)C(c2cnc3ccccn23)=C1c1cn2c3c(cccc13)C...,88.59,Rattus norvegicus

O=C1Nc2cc(C(F)(F)F)ccc2C1(O)c1cc(Cl)ccc1O

,Drug_ID,SMILES,Y,Species
1487,CHEMBL282479,O=C1Nc2cc(C(F)(F)F)ccc2C1(O)c1cc(Cl)ccc1O,98.51,Homo sapiens
1994,CHEMBL282479,O=C1Nc2cc(C(F)(F)F)ccc2C1(O)c1cc(Cl)ccc1O,97.81,Mus musculus
2359,CHEMBL282479,O=C1Nc2cc(C(F)(F)F)ccc2C1(O)c1cc(Cl)ccc1O,98.89,Rattus norvegicus

O=CNc1cc([C@@H](O)CNCCc2ccc(NC[C@H](O)c3ccccc3)cc2)ccc1O

,Drug_ID,SMILES,Y,Species
334,CHEMBL1940832,O=CNc1cc([C@@H](O)CNCCc2ccc(NC[C@H](O)c3ccccc3...,80.65,Cavia porcellus
352,CHEMBL1940832,O=CNc1cc([C@@H](O)CNCCc2ccc(NC[C@H](O)c3ccccc3...,71.53,Homo sapiens

O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)Cc1ccccn1

,Drug_ID,SMILES,Y,Species
280,CHEMBL2313229,O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)Cc1ccccn1,43.14,Cavia porcellus
423,CHEMBL2313229,O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)Cc1ccccn1,99.51,Homo sapiens
1970,CHEMBL2313229,O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)Cc1ccccn1,90.32,Mus musculus

O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)c1cccnc1

,Drug_ID,SMILES,Y,Species
100,CHEMBL2313226,O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)c1cccnc1,79.17,Canis lupus familiaris
257,CHEMBL2313226,O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)c1cccnc1,70.10,Cavia porcellus
820,CHEMBL2313226,O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)c1cccnc1,97.66,Homo sapiens
1953,CHEMBL2313226,O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)c1cccnc1,83.04,Mus musculus
2819,CHEMBL2313226,O=P(c1ccccc1)(c1ccccc1)N(Cc1ccccn1)c1cccnc1,85.48,Rattus norvegicus

O=P1(N(CCCl)CCCl)NCCCO1

       Drug_ID                   SMILES      Y            Species
505   CHEMBL88  O=P1(N(CCCl)CCCl)NCCCO1  20.08       Homo sapiens
2413  CHEMBL88  O=P1(N(CCCl)CCCl)NCCCO1  14.23  Rattus norvegicus

O=S(=O)(CCCOCCc1ccccc1)CCNCCc1ccc(O)c2nc(O)sc12

,Drug_ID,SMILES,Y,Species
312,CHEMBL82663,O=S(=O)(CCCOCCc1ccccc1)CCNCCc1ccc(O)c2nc(O)sc12,89.91,Cavia porcellus
731,CHEMBL82663,O=S(=O)(CCCOCCc1ccccc1)CCNCCc1ccc(O)c2nc(O)sc12,94.44,Homo sapiens
2616,CHEMBL82663,O=S(=O)(CCCOCCc1ccccc1)CCNCCc1ccc(O)c2nc(O)sc12,92.16,Rattus norvegicus

O=S(=O)(NC1CCNCC1)c1cc(S(=O)(=O)c2ccccc2)ccc1C(F)(F)F

,Drug_ID,SMILES,Y,Species
1221,CHEMBL495575,O=S(=O)(NC1CCNCC1)c1cc(S(=O)(=O)c2ccccc2)ccc1C...,92.48,Homo sapiens
2486,CHEMBL495575,O=S(=O)(NC1CCNCC1)c1cc(S(=O)(=O)c2ccccc2)ccc1C...,77.62,Rattus norvegicus

O=S(=O)(N[C@H](CO)C(C(F)(F)F)C(F)(F)F)c1ccc(Cl)s1

,Drug_ID,SMILES,Y,Species
707,CHEMBL463981,O=S(=O)(N[C@H](CO)C(C(F)(F)F)C(F)(F)F)c1ccc(Cl)s1,90.91,Homo sapiens
2211,CHEMBL463981,O=S(=O)(N[C@H](CO)C(C(F)(F)F)C(F)(F)F)c1ccc(Cl)s1,89.05,Rattus norvegicus

O=S(=O)(Nc1ccc2sc(CO)nc2c1)c1ccc(Br)cc1

,Drug_ID,SMILES,Y,Species
1173,CHEMBL2088414,O=S(=O)(Nc1ccc2sc(CO)nc2c1)c1ccc(Br)cc1,99.31,Homo sapiens
2823,CHEMBL2088414,O=S(=O)(Nc1ccc2sc(CO)nc2c1)c1ccc(Br)cc1,99.82,Rattus norvegicus

O=S(=O)(Nc1ncns1)c1cc(F)c(Oc2ccc(Cl)cc2-c2ccnn2C2CNC2)cc1F

,Drug_ID,SMILES,Y,Species
155,CHEMBL2325642,O=S(=O)(Nc1ncns1)c1cc(F)c(Oc2ccc(Cl)cc2-c2ccnn...,95.63,Canis lupus familiaris
1424,CHEMBL2325642,O=S(=O)(Nc1ncns1)c1cc(F)c(Oc2ccc(Cl)cc2-c2ccnn...,98.00,Homo sapiens
2606,CHEMBL2325642,O=S(=O)(Nc1ncns1)c1cc(F)c(Oc2ccc(Cl)cc2-c2ccnn...,94.68,Rattus norvegicus

O=S(=O)(c1ccccc1)N(CC(F)(F)F)c1ccc(C(O)(C(F)(F)F)C(F)(F)F)cc1

,Drug_ID,SMILES,Y,Species
1295,CHEMBL62136,O=S(=O)(c1ccccc1)N(CC(F)(F)F)c1ccc(C(O)(C(F)(F...,99.56,Homo sapiens
2542,CHEMBL62136,O=S(=O)(c1ccccc1)N(CC(F)(F)F)c1ccc(C(O)(C(F)(F...,99.71,Rattus norvegicus

O=[N+]([O-])c1c(Nc2ccc(-n3cncn3)cc2)ncnc1N1CCC(Sc2ccccn2)CC1

,Drug_ID,SMILES,Y,Species
863,CHEMBL1092240,O=[N+]([O-])c1c(Nc2ccc(-n3cncn3)cc2)ncnc1N1CCC...,99.83,Homo sapiens
2769,CHEMBL1092240,O=[N+]([O-])c1c(Nc2ccc(-n3cncn3)cc2)ncnc1N1CCC...,99.71,Rattus norvegicus

O=c1[nH]c2c(O)ccc([C@@H](O)CNCCCSCCOCCc3cccc4ccccc34)c2s1

,Drug_ID,SMILES,Y,Species
309,CHEMBL1807820,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCCSCCOCCc3cccc4c...,99.12,Cavia porcellus
414,CHEMBL1807820,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCCSCCOCCc3cccc4c...,99.33,Homo sapiens
2692,CHEMBL1807820,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCCSCCOCCc3cccc4c...,99.18,Rattus norvegicus

O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3cccc(Cl)c3)c2s1

,Drug_ID,SMILES,Y,Species
302,CHEMBL1807827,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3cccc(C...,85.48,Cavia porcellus
813,CHEMBL1807827,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3cccc(C...,84.30,Homo sapiens

O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3cccc(Cl)c3Cl)c2s1

,Drug_ID,SMILES,Y,Species
323,CHEMBL1807829,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3cccc(C...,96.00,Cavia porcellus
1091,CHEMBL1807829,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3cccc(C...,94.06,Homo sapiens
2792,CHEMBL1807829,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3cccc(C...,91.64,Rattus norvegicus

O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3ccccc3)c2s1

,Drug_ID,SMILES,Y,Species
264,CHEMBL1807823,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3ccccc3...,52.88,Cavia porcellus
1668,CHEMBL1807823,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3ccccc3...,52.88,Homo sapiens
2383,CHEMBL1807823,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCSCCCNCCc3ccccc3...,55.73,Rattus norvegicus

O=c1[nH]c2c(O)ccc([C@@H](O)CNCCc3cccc(CNCCc4ccccc4F)c3)c2s1

,Drug_ID,SMILES,Y,Species
330,CHEMBL1944691,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCc3cccc(CNCCc4cc...,89.27,Cavia porcellus
2534,CHEMBL1944691,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCc3cccc(CNCCc4cc...,86.59,Rattus norvegicus

O=c1[nH]c2c(O)ccc([C@@H](O)CNCCc3cccc(CNCCc4ccccn4)c3)c2s1

,Drug_ID,SMILES,Y,Species
212,CHEMBL1945033,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCc3cccc(CNCCc4cc...,70.10,Canis lupus familiaris
266,CHEMBL1945033,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCc3cccc(CNCCc4cc...,80.65,Cavia porcellus
1902,CHEMBL1945033,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCc3cccc(CNCCc4cc...,82.39,Homo sapiens
2805,CHEMBL1945033,O=c1[nH]c2c(O)ccc([C@@H](O)CNCCc3cccc(CNCCc4cc...,85.19,Rattus norvegicus

O=c1[nH]c2c(O)ccc([C@@H](O)CN[C@H]3CCC[C@@H]3OCc3ccccc3)c2s1

,Drug_ID,SMILES,Y,Species
630,CHEMBL1221681,O=c1[nH]c2c(O)ccc([C@@H](O)CN[C@H]3CCC[C@@H]3O...,93.10,Homo sapiens
2757,CHEMBL1221681,O=c1[nH]c2c(O)ccc([C@@H](O)CN[C@H]3CCC[C@@H]3O...,82.05,Rattus norvegicus

O=c1[nH]c2cc(C(F)(F)F)ccc2n1-c1cc(C(F)(F)F)ccc1O

,Drug_ID,SMILES,Y,Species
1495,CHEMBL384903,O=c1[nH]c2cc(C(F)(F)F)ccc2n1-c1cc(C(F)(F)F)ccc1O,99.87,Homo sapiens
2101,CHEMBL384903,O=c1[nH]c2cc(C(F)(F)F)ccc2n1-c1cc(C(F)(F)F)ccc1O,99.79,Mus musculus
2438,CHEMBL384903,O=c1[nH]c2cc(C(F)(F)F)ccc2n1-c1cc(C(F)(F)F)ccc1O,99.89,Rattus norvegicus

O=c1[nH]c2ccccc2n1CCCN1CCC(n2c(=O)[nH]c3cc(Cl)ccc32)CC1

,Drug_ID,SMILES,Y,Species
161,CHEMBL219916,O=c1[nH]c2ccccc2n1CCCN1CCC(n2c(=O)[nH]c3cc(Cl)...,91.28,Canis lupus familiaris
688,CHEMBL219916,O=c1[nH]c2ccccc2n1CCCN1CCC(n2c(=O)[nH]c3cc(Cl)...,96.65,Homo sapiens
2489,CHEMBL219916,O=c1[nH]c2ccccc2n1CCCN1CCC(n2c(=O)[nH]c3cc(Cl)...,93.10,Rattus norvegicus

O=c1c2cc(-c3ccc(Cl)cc3)oc2ccn1-c1ccc2c(cnn2CCN2CCCC2)c1

,Drug_ID,SMILES,Y,Species
1858,CHEMBL1290383,O=c1c2cc(-c3ccc(Cl)cc3)oc2ccn1-c1ccc2c(cnn2CCN...,99.34,Homo sapiens
1999,CHEMBL1290383,O=c1c2cc(-c3ccc(Cl)cc3)oc2ccn1-c1ccc2c(cnn2CCN...,99.57,Mus musculus

O=c1cc(Cn2c(C3CCC3)nc3nccnc32)c2ccc(F)c(F)c2[nH]1

,Drug_ID,SMILES,Y,Species
1703,CHEMBL1801504,O=c1cc(Cn2c(C3CCC3)nc3nccnc32)c2ccc(F)c(F)c2[nH]1,79.92,Homo sapiens
2803,CHEMBL1801504,O=c1cc(Cn2c(C3CCC3)nc3nccnc32)c2ccc(F)c(F)c2[nH]1,84.00,Rattus norvegicus

O=c1cc(N2CCOCC2)nc(NCc2c(Cl)cccc2Cl)[nH]1

,Drug_ID,SMILES,Y,Species
917,CHEMBL2158441,O=c1cc(N2CCOCC2)nc(NCc2c(Cl)cccc2Cl)[nH]1,96.00,Homo sapiens
2462,CHEMBL2158441,O=c1cc(N2CCOCC2)nc(NCc2c(Cl)cccc2Cl)[nH]1,95.82,Rattus norvegicus

O=c1cc(N2CCOCC2)nc(NCc2cccc(Cl)c2)[nH]1

,Drug_ID,SMILES,Y,Species
1000,CHEMBL2158438,O=c1cc(N2CCOCC2)nc(NCc2cccc(Cl)c2)[nH]1,92.95,Homo sapiens
2235,CHEMBL2158438,O=c1cc(N2CCOCC2)nc(NCc2cccc(Cl)c2)[nH]1,95.23,Rattus norvegicus

O=c1cc(N2CCOCC2)nc(NCc2cccc(Cl)c2Cl)[nH]1

,Drug_ID,SMILES,Y,Species
1496,CHEMBL2158437,O=c1cc(N2CCOCC2)nc(NCc2cccc(Cl)c2Cl)[nH]1,97.91,Homo sapiens
2569,CHEMBL2158437,O=c1cc(N2CCOCC2)nc(NCc2cccc(Cl)c2Cl)[nH]1,98.21,Rattus norvegicus

O=c1cc(N2CCOCC2)nc(NCc2cccc3ccccc23)[nH]1

,Drug_ID,SMILES,Y,Species
1442,CHEMBL2158436,O=c1cc(N2CCOCC2)nc(NCc2cccc3ccccc23)[nH]1,96.79,Homo sapiens
2596,CHEMBL2158436,O=c1cc(N2CCOCC2)nc(NCc2cccc3ccccc23)[nH]1,97.49,Rattus norvegicus

O=c1cc(N2CCOCC2)nc(NCc2ccccc2)[nH]1

,Drug_ID,SMILES,Y,Species
1169,CHEMBL2158390,O=c1cc(N2CCOCC2)nc(NCc2ccccc2)[nH]1,73.36,Homo sapiens
2573,CHEMBL2158390,O=c1cc(N2CCOCC2)nc(NCc2ccccc2)[nH]1,81.01,Rattus norvegicus

O=c1cc(N2CCOCC2)nc2n(Cc3cccc(Cl)c3)ccn12

,Drug_ID,SMILES,Y,Species
619,CHEMBL1957848,O=c1cc(N2CCOCC2)nc2n(Cc3cccc(Cl)c3)ccn12,89.91,Homo sapiens
2277,CHEMBL1957848,O=c1cc(N2CCOCC2)nc2n(Cc3cccc(Cl)c3)ccn12,89.05,Rattus norvegicus

O=c1cc(N2CCOCC2)nc2n(Cc3cccc(Cl)c3Cl)ccn12

,Drug_ID,SMILES,Y,Species
209,CHEMBL1957840,O=c1cc(N2CCOCC2)nc2n(Cc3cccc(Cl)c3Cl)ccn12,95.01,Canis lupus familiaris
1749,CHEMBL1957840,O=c1cc(N2CCOCC2)nc2n(Cc3cccc(Cl)c3Cl)ccn12,96.34,Homo sapiens

O=c1cc(N2CCOCC2)nc2n(Cc3cccc4ccccc34)ccn12

,Drug_ID,SMILES,Y,Species
206,CHEMBL1957841,O=c1cc(N2CCOCC2)nc2n(Cc3cccc4ccccc34)ccn12,93.24,Canis lupus familiaris
1386,CHEMBL1957841,O=c1cc(N2CCOCC2)nc2n(Cc3cccc4ccccc34)ccn12,96.93,Homo sapiens
2338,CHEMBL1957841,O=c1cc(N2CCOCC2)nc2n(Cc3cccc4ccccc34)ccn12,95.23,Rattus norvegicus

O=c1cc(OCc2ccccc2)ccn1-c1ccc2c(cnn2CCN2CCCC2)c1

,Drug_ID,SMILES,Y,Species
234,CHEMBL1289283,O=c1cc(OCc2ccccc2)ccn1-c1ccc2c(cnn2CCN2CCCC2)c1,84.00,Canis lupus familiaris
1462,CHEMBL1289283,O=c1cc(OCc2ccccc2)ccn1-c1ccc2c(cnn2CCN2CCCC2)c1,83.04,Homo sapiens
2034,CHEMBL1289283,O=c1cc(OCc2ccccc2)ccn1-c1ccc2c(cnn2CCN2CCCC2)c1,86.32,Mus musculus
2826,CHEMBL1289283,O=c1cc(OCc2ccccc2)ccn1-c1ccc2c(cnn2CCN2CCCC2)c1,88.11,Rattus norvegicus

O=c1n(CCCN2CCN(c3cccc(Cl)c3)CC2)nc2ccccn12

,Drug_ID,SMILES,Y,Species
1385,CHEMBL621,O=c1n(CCCN2CCN(c3cccc(Cl)c3)CC2)nc2ccccn12,97.00,Homo sapiens
2224,CHEMBL621,O=c1n(CCCN2CCN(c3cccc(Cl)c3)CC2)nc2ccccn12,87.62,Rattus norvegicus

O=c1nc(N2CCOCC2)cc(N(CCO)Cc2cccc3ccccc23)[nH]1

,Drug_ID,SMILES,Y,Species
1120,CHEMBL2165180,O=c1nc(N2CCOCC2)cc(N(CCO)Cc2cccc3ccccc23)[nH]1,86.05,Homo sapiens
2254,CHEMBL2165180,O=c1nc(N2CCOCC2)cc(N(CCO)Cc2cccc3ccccc23)[nH]1,84.90,Rattus norvegicus

OCCN1CCN(CCCN2c3ccccc3Sc3ccc(Cl)cc32)CC1

,Drug_ID,SMILES,Y,Species
1725,CHEMBL567,OCCN1CCN(CCCN2c3ccccc3Sc3ccc(Cl)cc32)CC1,98.51,Homo sapiens
2599,CHEMBL567,OCCN1CCN(CCCN2c3ccccc3Sc3ccc(Cl)cc32)CC1,98.54,Rattus norvegicus

OCCO[C@H]1C[C@@H](n2nnc3c(N[C@@H]4C[C@H]4c4ccc(F)c(F)c4)nc(SCCC(F)(F)F)nc32)[C@H](O)[C@@H]1O

,Drug_ID,SMILES,Y,Species
157,CHEMBL249790,OCCO[C@H]1C[C@@H](n2nnc3c(N[C@@H]4C[C@H]4c4ccc...,99.54,Canis lupus familiaris
1239,CHEMBL249790,OCCO[C@H]1C[C@@H](n2nnc3c(N[C@@H]4C[C@H]4c4ccc...,99.85,Homo sapiens

OC[C@H](Nc1ncc(Cl)c(Nc2cc(C3CC3)[nH]n2)n1)c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
77,CHEMBL514257,OC[C@H](Nc1ncc(Cl)c(Nc2cc(C3CC3)[nH]n2)n1)c1cc...,95.01,Canis lupus familiaris
783,CHEMBL514257,OC[C@H](Nc1ncc(Cl)c(Nc2cc(C3CC3)[nH]n2)n1)c1cc...,95.63,Homo sapiens

OC[C@H]1C[C@@H](n2nnc3c(N[C@@H]4C[C@H]4c4ccc(F)c(F)c4)nc(SCCC(F)(F)F)nc32)[C@H](O)[C@@H]1O

,Drug_ID,SMILES,Y,Species
189,CHEMBL249789,OC[C@H]1C[C@@H](n2nnc3c(N[C@@H]4C[C@H]4c4ccc(F...,99.80,Canis lupus familiaris
1500,CHEMBL249789,OC[C@H]1C[C@@H](n2nnc3c(N[C@@H]4C[C@H]4c4ccc(F...,99.85,Homo sapiens

OCc1cc(C(O)CNCCCCCCOCCCCc2ccccc2)ccc1O

,Drug_ID,SMILES,Y,Species
222,CHEMBL1263,OCc1cc(C(O)CNCCCCCCOCCCCc2ccccc2)ccc1O,98.21,Canis lupus familiaris
331,CHEMBL1263,OCc1cc(C(O)CNCCCCCCOCCCCc2ccccc2)ccc1O,95.23,Cavia porcellus
1910,CHEMBL1263,OCc1cc(C(O)CNCCCCCCOCCCCc2ccccc2)ccc1O,93.39,Homo sapiens
2615,CHEMBL1263,OCc1cc(C(O)CNCCCCCCOCCCCc2ccccc2)ccc1O,92.64,Rattus norvegicus

Oc1ccc2cc(CNCCc3ccc(Br)cc3)c(-c3ccsc3)nc2c1

,Drug_ID,SMILES,Y,Species
1642,CHEMBL1257491,Oc1ccc2cc(CNCCc3ccc(Br)cc3)c(-c3ccsc3)nc2c1,99.85,Homo sapiens
2027,CHEMBL1257491,Oc1ccc2cc(CNCCc3ccc(Br)cc3)c(-c3ccsc3)nc2c1,99.71,Mus musculus
2770,CHEMBL1257491,Oc1ccc2cc(CNCCc3ccc(Br)cc3)c(-c3ccsc3)nc2c1,99.70,Rattus norvegicus

c1ccc([C@@H]([C@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1

,Drug_ID,SMILES,Y,Species
332,CHEMBL2152524,c1ccc([C@@H]([C@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1,51.15,Cavia porcellus
407,CHEMBL2152524,c1ccc([C@@H]([C@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1,83.04,Homo sapiens
2054,CHEMBL2152524,c1ccc([C@@H]([C@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1,66.10,Mus musculus
2458,CHEMBL2152524,c1ccc([C@@H]([C@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1,67.12,Rattus norvegicus

c1ccc([C@@H]([C@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1

,Drug_ID,SMILES,Y,Species
1040,CHEMBL2152522,c1ccc([C@@H]([C@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1,90.12,Homo sapiens
2108,CHEMBL2152522,c1ccc([C@@H]([C@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1,73.81,Mus musculus
2514,CHEMBL2152522,c1ccc([C@@H]([C@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1,68.13,Rattus norvegicus

c1ccc([C@H]([C@@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1

,Drug_ID,SMILES,Y,Species
269,CHEMBL2152525,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1,51.15,Cavia porcellus
1194,CHEMBL2152525,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1,83.04,Homo sapiens
2089,CHEMBL2152525,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1,72.91,Mus musculus
2117,CHEMBL2152525,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCC2)N2CCCC2)cc1,66.10,Rattus norvegicus

c1ccc([C@H]([C@@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1

,Drug_ID,SMILES,Y,Species
117,CHEMBL2152523,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1,83.68,Canis lupus familiaris
286,CHEMBL2152523,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1,50.00,Cavia porcellus
644,CHEMBL2152523,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1,93.94,Homo sapiens
1961,CHEMBL2152523,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1,74.69,Mus musculus
2624,CHEMBL2152523,c1ccc([C@H]([C@@H](c2ccccc2)N2CCCCC2)N2CCCCC2)cc1,63.47,Rattus norvegicus

c1ccc2[nH]c(CCc3nc4ccccc4[nH]3)nc2c1

,Drug_ID,SMILES,Y,Species
615,CHEMBL48966,c1ccc2[nH]c(CCc3nc4ccccc4[nH]3)nc2c1,84.00,Homo sapiens
1995,CHEMBL48966,c1ccc2[nH]c(CCc3nc4ccccc4[nH]3)nc2c1,81.01,Mus musculus
2695,CHEMBL48966,c1ccc2[nH]c(CCc3nc4ccccc4[nH]3)nc2c1,79.92,Rattus norvegicus

c1ccc2c(c1)CC(N1CCN(c3cccc4c3OCCO4)CC1)C2

,Drug_ID,SMILES,Y,Species
1562,CHEMBL49247,c1ccc2c(c1)CC(N1CCN(c3cccc4c3OCCO4)CC1)C2,97.38,Homo sapiens
2016,CHEMBL49247,c1ccc2c(c1)CC(N1CCN(c3cccc4c3OCCO4)CC1)C2,93.39,Mus musculus
2343,CHEMBL49247,c1ccc2c(c1)CC(N1CCN(c3cccc4c3OCCO4)CC1)C2,95.72,Rattus norvegicus

c1ccc2c(c1)CCC[C@H]2Nc1nc2ccccc2[nH]1

,Drug_ID,SMILES,Y,Species
1940,CHEMBL510780,c1ccc2c(c1)CCC[C@H]2Nc1nc2ccccc2[nH]1,99.30,Homo sapiens
2324,CHEMBL510780,c1ccc2c(c1)CCC[C@H]2Nc1nc2ccccc2[nH]1,95.63,Rattus norvegicus

c1ccc2nc(COc3ccc(-c4n[nH]cc4-c4ccncc4)cc3)ccc2c1

,Drug_ID,SMILES,Y,Species
158,CHEMBL560377,c1ccc2nc(COc3ccc(-c4n[nH]cc4-c4ccncc4)cc3)ccc2c1,99.80,Canis lupus familiaris
870,CHEMBL560377,c1ccc2nc(COc3ccc(-c4n[nH]cc4-c4ccncc4)cc3)ccc2c1,99.80,Homo sapiens
1969,CHEMBL560377,c1ccc2nc(COc3ccc(-c4n[nH]cc4-c4ccncc4)cc3)ccc2c1,99.87,Mus musculus
2822,CHEMBL560377,c1ccc2nc(COc3ccc(-c4n[nH]cc4-c4ccncc4)cc3)ccc2c1,99.82,Rattus norvegicus

c1cncc(Nc2ncc(-c3ccncn3)c(-c3ccco3)n2)c1

,Drug_ID,SMILES,Y,Species
809,CHEMBL375293,c1cncc(Nc2ncc(-c3ccncn3)c(-c3ccco3)n2)c1,86.05,Homo sapiens
1950,CHEMBL375293,c1cncc(Nc2ncc(-c3ccncn3)c(-c3ccco3)n2)c1,84.00,Mus musculus
2806,CHEMBL375293,c1cncc(Nc2ncc(-c3ccncn3)c(-c3ccco3)n2)c1,86.05,Rattus norvegicus

In [6]:
conflicting_smiles = conflicting_smiles[conflicting_smiles > 1].index.tolist()

if conflicting_smiles:
    print("Removing conflicting SMILES:")
    labels_df_filtered = labels_df[~labels_df['SMILES'].isin(conflicting_smiles)]
    print("Done")
    display(labels_df_filtered)
    print("Conflicting SMILES removed")
else:
    labels_df_filtered = labels_df.copy()

Removing conflicting SMILES:
Done

,Drug_ID,SMILES,Y,Species
28,CHEMBL1922660,CCOc1ccc(-c2ccc(Cn3c(CC(C)(C)C(=O)O)c(SC(C)(C)...,99.92,Canis lupus familiaris
30,CHEMBL403225,C[C@H](CO)Nc1nc(SCc2cccc(Cl)c2F)nc2[nH]c(=O)sc12,99.95,Canis lupus familiaris
45,CHEMBL1790041,CNC(=C[N+](=O)[O-])NCCSCc1ccc(CN(C)C)o1,28.95,Canis lupus familiaris
62,CHEMBL2171021,Cc1c(Cl)ccc(OC2CCN(C3CCN(C(=O)c4cccc(S(C)(=O)=...,96.50,Canis lupus familiaris
92,CHEMBL1516,CCCc1nc(C(C)(C)O)c(C(=O)O)n1Cc1ccc(-c2ccccc2-c...,98.81,Canis lupus familiaris
...,...,...,...,...
2791,CHEMBL1580912,O=C(NCCc1ccc(Cl)cc1)c1cccnc1,91.46,Rattus norvegicus
2796,CHEMBL31354,COc1ccccc1N1CCN(CCN(C(=O)C2CCCCC2)c2ccccn2)CC1,79.17,Rattus norvegicus
2797,CHEMBL2325638,O=S(=O)(Nc1ncns1)c1cc(F)c(Oc2cc(F)c(Cl)cc2-c2c...,99.80,Rattus norvegicus
2800,CHEMBL2059859,Cc1ccc(-c2nc3ccccc3[nH]2)cc1NC(=O)c1ccc(OCc2cc...,94.68,Rattus norvegicus
2820,CHEMBL2069424,Cc1ncc(-c2cccc3c2C[C@H](NC(=O)c2ccc(OCC(F)(F)F...,92.32,Rattus norvegicus

Conflicting SMILES removed

In [7]:
repeated_smiles = labels_df_filtered['SMILES'].value_counts()
repeated_smiles = repeated_smiles[repeated_smiles > 1].index.tolist()
repeated_smiles

if repeated_smiles:
    print(len(repeated_smiles)," duplicate SMILES found:")
    for smiles in repeated_smiles:
        print(smiles)
        display(labels_df_filtered[labels_df_filtered['SMILES'] == smiles])
    print("Removing duplicate SMILES from dataframe")
    labels_df_unique = labels_df_filtered.drop_duplicates(subset=['SMILES'], keep='first')
    print("Done")
    display(labels_df_unique)
else:
    labels_df_unique = labels_df_filtered.copy()
    print("No repeated SMILES found.")

10  duplicate SMILES found:
CC(C)N1C(=O)[C@H](NC(=O)[C@@H](Cc2ccccc2OC(F)(F)F)NC(=O)OC(C)(C)C)CCc2ccccc21

,Drug_ID,SMILES,Y,Species
1471,CHEMBL247828,CC(C)N1C(=O)[C@H](NC(=O)[C@@H](Cc2ccccc2OC(F)(...,99.7,Homo sapiens
2130,CHEMBL247828,CC(C)N1C(=O)[C@H](NC(=O)[C@@H](Cc2ccccc2OC(F)(...,99.7,Rattus norvegicus

O=C(CCCN1CC[Si](O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1

,Drug_ID,SMILES,Y,Species
730,CHEMBL2204343,O=C(CCCN1CC[Si](O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1,94.56,Homo sapiens
2484,CHEMBL2204343,O=C(CCCN1CC[Si](O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1,94.56,Rattus norvegicus

COc1cccc([C@H](O)C2CCN(CCc3ccc(F)cc3)CC2)c1OC

,Drug_ID,SMILES,Y,Species
1314,CHEMBL74355,COc1cccc([C@H](O)C2CCN(CCc3ccc(F)cc3)CC2)c1OC,34.94,Homo sapiens
2649,CHEMBL74355,COc1cccc([C@H](O)C2CCN(CCc3ccc(F)cc3)CC2)c1OC,34.94,Rattus norvegicus

N#Cc1c(O)nc(N)nc1-c1ccccc1

           Drug_ID                      SMILES      Y            Species
1929  CHEMBL563498  N#Cc1c(O)nc(N)nc1-c1ccccc1  96.34       Homo sapiens
2225  CHEMBL563498  N#Cc1c(O)nc(N)nc1-c1ccccc1  96.34  Rattus norvegicus

Cc1c(Cl)ccc(OC2CCN(C3CCN(C(=O)c4cccc(S(C)(=O)=O)c4)CC3)CC2)c1Cl

,Drug_ID,SMILES,Y,Species
62,CHEMBL2171021,Cc1c(Cl)ccc(OC2CCN(C3CCN(C(=O)c4cccc(S(C)(=O)=...,96.5,Canis lupus familiaris
1724,CHEMBL2171021,Cc1c(Cl)ccc(OC2CCN(C3CCN(C(=O)c4cccc(S(C)(=O)=...,96.5,Homo sapiens

CNCCC=C1c2ccccc2CCc2ccccc21

        Drug_ID                       SMILES      Y            Species
880   CHEMBL445  CNCCC=C1c2ccccc2CCc2ccccc21  86.85       Homo sapiens
2118  CHEMBL445  CNCCC=C1c2ccccc2CCc2ccccc21  86.85  Rattus norvegicus

CC[C@H](CO)Nc1nc(NCc2ccccc2)c2ncn(C(C)C)c2n1

,Drug_ID,SMILES,Y,Species
1052,CHEMBL14762,CC[C@H](CO)Nc1nc(NCc2ccccc2)c2ncn(C(C)C)c2n1,92.8,Homo sapiens
2734,CHEMBL14762,CC[C@H](CO)Nc1nc(NCc2ccccc2)c2ncn(C(C)C)c2n1,92.8,Rattus norvegicus

Cc1cccc(C)c1OCC(C)N

        Drug_ID               SMILES      Y            Species
1673  CHEMBL558  Cc1cccc(C)c1OCC(C)N  36.53       Homo sapiens
2579  CHEMBL558  Cc1cccc(C)c1OCC(C)N  36.53  Rattus norvegicus

CC(C)c1nc2ccccc2n1-c1nc(N2CCOCC2)c2nc(OC3CN(C4CCS(=O)(=O)CC4)C3)n(C)c2n1

,Drug_ID,SMILES,Y,Species
800,CHEMBL2216902,CC(C)c1nc2ccccc2n1-c1nc(N2CCOCC2)c2nc(OC3CN(C4...,78.01,Homo sapiens
2680,CHEMBL2216902,CC(C)c1nc2ccccc2n1-c1nc(N2CCOCC2)c2nc(OC3CN(C4...,78.01,Rattus norvegicus

OCCN1CCN(CCCN2c3ccccc3Sc3ccc(C(F)(F)F)cc32)CC1

,Drug_ID,SMILES,Y,Species
450,CHEMBL726,OCCN1CCN(CCCN2c3ccccc3Sc3ccc(C(F)(F)F)cc32)CC1,98.81,Homo sapiens
2741,CHEMBL726,OCCN1CCN(CCCN2c3ccccc3Sc3ccc(C(F)(F)F)cc32)CC1,98.81,Rattus norvegicus

Removing duplicate SMILES from dataframe
Done

,Drug_ID,SMILES,Y,Species
28,CHEMBL1922660,CCOc1ccc(-c2ccc(Cn3c(CC(C)(C)C(=O)O)c(SC(C)(C)...,99.92,Canis lupus familiaris
30,CHEMBL403225,C[C@H](CO)Nc1nc(SCc2cccc(Cl)c2F)nc2[nH]c(=O)sc12,99.95,Canis lupus familiaris
45,CHEMBL1790041,CNC(=C[N+](=O)[O-])NCCSCc1ccc(CN(C)C)o1,28.95,Canis lupus familiaris
62,CHEMBL2171021,Cc1c(Cl)ccc(OC2CCN(C3CCN(C(=O)c4cccc(S(C)(=O)=...,96.50,Canis lupus familiaris
92,CHEMBL1516,CCCc1nc(C(C)(C)O)c(C(=O)O)n1Cc1ccc(-c2ccccc2-c...,98.81,Canis lupus familiaris
...,...,...,...,...
2791,CHEMBL1580912,O=C(NCCc1ccc(Cl)cc1)c1cccnc1,91.46,Rattus norvegicus
2796,CHEMBL31354,COc1ccccc1N1CCN(CCN(C(=O)C2CCCCC2)c2ccccn2)CC1,79.17,Rattus norvegicus
2797,CHEMBL2325638,O=S(=O)(Nc1ncns1)c1cc(F)c(Oc2cc(F)c(Cl)cc2-c2c...,99.80,Rattus norvegicus
2800,CHEMBL2059859,Cc1ccc(-c2nc3ccccc3[nH]2)cc1NC(=O)c1ccc(OCc2cc...,94.68,Rattus norvegicus
2820,CHEMBL2069424,Cc1ncc(-c2cccc3c2C[C@H](NC(=O)c2ccc(OCC(F)(F)F...,92.32,Rattus norvegicus

## Save Cleaned Dataset

In [11]:
labels_df_unique.to_csv(f"../data/{dataset}_cleaned.csv")

In [18]:
from ChemicalDice import smiles_to_embeddings

# Generate embeddings from CSV
CDI_embeddings = smiles_to_embeddings.collect_features_from_csv(
    filepath=f"../data/{dataset}_cleaned.csv",
    convert_to_canonical=False
)

CDI_embeddings

All SMILES are valid.
Saved canonical SMILES to temp file: /tmp/tmp2o4p8hj5.csv
Sent /tmp/tmp2o4p8hj5.csv. Receiving stream...

100%|██████████| 35/35 [00:12<00:00,  2.81batch/s]

Stream finished. Concatenating batches...

,SMILES,CDI1,CDI2,CDI3,CDI4,CDI5,CDI6,CDI7,CDI8,CDI9,...,CDI8183,CDI8184,CDI8185,CDI8186,CDI8187,CDI8188,CDI8189,CDI8190,CDI8191,CDI8192
0,CCOc1ccc(-c2ccc(Cn3c(CC(C)(C)C(=O)O)c(SC(C)(C)...,-0.112020,7.800903,0.348821,0.146076,0.351550,0.333945,0.248491,-0.358052,-0.259561,...,0.013584,-0.215027,-0.593232,-0.251186,6.750084,0.082696,-0.179041,0.122496,-0.065559,0.063309
1,C[C@H](CO)Nc1nc(SCc2cccc(Cl)c2F)nc2[nH]c(=O)sc12,-0.134578,7.678442,0.507060,0.361889,0.489886,0.490634,0.326738,-0.439593,-0.443664,...,0.110242,-0.290491,-0.718691,-0.278855,6.935112,0.172814,-0.184790,0.233132,-0.138361,0.116665
2,CNC(=C[N+](=O)[O-])NCCSCc1ccc(CN(C)C)o1,-0.109536,7.664749,0.540561,0.378041,0.510999,0.496168,0.359051,-0.443771,-0.475664,...,0.097660,-0.279299,-0.707880,-0.284046,6.904514,0.124977,-0.166997,0.236739,-0.165415,0.101713
3,Cc1c(Cl)ccc(OC2CCN(C3CCN(C(=O)c4cccc(S(C)(=O)=...,-0.112201,7.737064,0.429881,0.241949,0.405471,0.388015,0.326015,-0.365053,-0.381815,...,0.031259,-0.247952,-0.631331,-0.248380,6.784470,0.083950,-0.162076,0.170783,-0.111983,0.079092
4,CCCc1nc(C(C)(C)O)c(C(=O)O)n1Cc1ccc(-c2ccccc2-c...,-0.129556,7.730204,0.443079,0.269246,0.420570,0.432281,0.310673,-0.387100,-0.363025,...,0.075457,-0.250846,-0.674552,-0.233234,6.841152,0.125219,-0.193701,0.172335,-0.109051,0.096196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1101,O=C(NCCc1ccc(Cl)cc1)c1cccnc1,-0.123465,7.665267,0.535011,0.385863,0.514319,0.519569,0.339115,-0.460828,-0.463383,...,0.129401,-0.308271,-0.743065,-0.288260,6.966096,0.182305,-0.178383,0.258043,-0.157168,0.115244
1102,COc1ccccc1N1CCN(CCN(C(=O)C2CCCCC2)c2ccccn2)CC1,-0.104675,7.688484,0.481717,0.298994,0.462310,0.479108,0.361860,-0.389153,-0.417746,...,0.078062,-0.258481,-0.676209,-0.250144,6.857898,0.097341,-0.183338,0.177266,-0.152129,0.079398
1103,O=S(=O)(Nc1ncns1)c1cc(F)c(Oc2cc(F)c(Cl)cc2-c2c...,-0.139389,7.717937,0.463949,0.289015,0.452213,0.421328,0.308704,-0.418084,-0.405048,...,0.076613,-0.294134,-0.711747,-0.254912,6.882516,0.180593,-0.187847,0.214960,-0.094764,0.130814
1104,Cc1ccc(-c2nc3ccccc3[nH]2)cc1NC(=O)c1ccc(OCc2cc...,-0.123838,7.725387,0.427848,0.287655,0.424018,0.456291,0.287894,-0.430993,-0.342827,...,0.090751,-0.273563,-0.693734,-0.252290,6.921553,0.184151,-0.190561,0.201703,-0.119075,0.111428
1105,Cc1ncc(-c2cccc3c2C[C@H](NC(=O)c2ccc(OCC(F)(F)F...,-0.130916,7.726183,0.458708,0.266959,0.422871,0.412400,0.296526,-0.403066,-0.389697,...,0.063052,-0.274962,-0.687819,-0.247884,6.854118,0.132110,-0.174366,0.197940,-0.122583,0.099032

## Data Preparation for Modeling

In [19]:
labels_df_unique = labels_df_unique[labels_df_unique['SMILES'].isin(CDI_embeddings['SMILES'])]

In [20]:
X = CDI_embeddings.drop(columns=["SMILES"])

y = labels_df_unique[target_column_name]

## Target Variable Transformation

In [21]:

# Set the desired transformation method for the target variable 'y'.
# Options:
#   'yeo-johnson' -> Handles positive, zero, and negative values. (Recommended)
#   'log'         -> Use log(1+y) transform. Only works if all y > -1.
#   'none'        -> No transformation is applied.
TARGET_TRANSFORMATION = 'none'

y_orignal_copy= y.copy()
np.random.seed(42)

pt = None # Initialize PowerTransformer object
print(f"--- Target Variable Transformation Mode: {TARGET_TRANSFORMATION.upper()} ---")

if TARGET_TRANSFORMATION == 'yeo-johnson':
    print("Applying Yeo-Johnson transformation to the target variable.")
    pt = PowerTransformer(method='yeo-johnson')
    y_transformed = pt.fit_transform(y.values.reshape(-1, 1))
    y = pd.Series(y_transformed.flatten(), index=y.index)
    print("Transformation complete.")

elif TARGET_TRANSFORMATION == 'log':
    if (y <= -1).any():
        print("Error: Target variable contains values <= -1, which is invalid for log(1+y).")
        print("Please use 'yeo-johnson' or clean the data. Aborting transformation.")
        TARGET_TRANSFORMATION = 'none' # Revert to 'none' to avoid errors
    else:
        print("Applying log1p transformation to the target variable.")
        y = np.log1p(y)
        print("Transformation complete.")

else: # 'none'
    print("No transformation will be applied to the target variable.")

--- Target Variable Transformation Mode: NONE ---
No transformation will be applied to the target variable.

## Model Training and Evaluation

In [ ]:

os.makedirs(  f"../results/{dataset}_results", exist_ok=True)
descriptor_name = "CDI"

result_file = f"../results/{dataset}_results/"+descriptor_name+'_model_metrics.csv'


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models =  {
  "Gradient Boosting Regressor": GradientBoostingRegressor(),
  }
# models =  {
#   "Linear Regression": LinearRegression(),
#   "Ridge Regression": Ridge(),
#   "Lasso Regression": Lasso(),
#   "ElasticNet": ElasticNet(),
#   "Support Vector Regressor": SVR(),
#   "Random Forest Regressor": RandomForestRegressor(),#time taking models, run only  if recources are not limited
#   "Gradient Boosting Regressor": GradientBoostingRegressor(),
#   "Extra Trees Regressor": ExtraTreesRegressor(),
#   "XGBoost Regressor": XGBRegressor(),
#   "LightGBM Regressor": LGBMRegressor(),
#   "CatBoost Regressor": CatBoostRegressor(verbose=0) #time taking models, run only  if recources are not limited
#   }


print(f"Training set size: {X_train_scaled.shape[0]} samples, {X_train_scaled.shape[1]} features")
print(f"Testing set size: {X_test_scaled.shape[0]} samples, {X_test_scaled.shape[1]} features")
results = {}
for name, model in models.items():
    print(f"Training model: {name}")

    # --- Time tracking ---
    start_time = time.time()


    # --- Training ---
    model.fit(X_train_scaled, y_train)

    # # --- Predictions ---
    y_pred_test = model.predict(X_test_scaled)
    y_pred_train = model.predict(X_train_scaled)
    elapsed_time = round(time.time() - start_time, 4)

    # <<< TACKLE INFINITY VALUES >>>
    if TARGET_TRANSFORMATION != 'none':
        train_range = y_train.max() - y_train.min()
        safe_min = y_train.min() - 0.2 * train_range
        safe_max = y_train.max() + 0.2 * train_range
        if np.any(y_pred_train > safe_max) or np.any(y_pred_train < safe_min):
            print(f"    ⚠️ WARNING: Model '{name}' produced extreme predictions on TRAINING data.")
        if np.any(y_pred_test > safe_max) or np.any(y_pred_test < safe_min):
            print(f"    ⚠️ WARNING: Model '{name}' produced extreme predictions on TEST data.")
        y_pred_train = np.clip(y_pred_train, safe_min, safe_max)
        y_pred_test = np.clip(y_pred_test, safe_min, safe_max)

    # Inverse transform
    if TARGET_TRANSFORMATION == 'yeo-johnson':
        y_test_orig = pt.inverse_transform(y_test.values.reshape(-1, 1)).flatten()
        y_train_orig = pt.inverse_transform(y_train.values.reshape(-1, 1)).flatten()
        y_pred_test_orig = pt.inverse_transform(y_pred_test.reshape(-1, 1)).flatten()
        y_pred_train_orig = pt.inverse_transform(y_pred_train.reshape(-1, 1)).flatten()
    elif TARGET_TRANSFORMATION == 'log':
        y_test_orig, y_train_orig = np.expm1(y_test), np.expm1(y_train)
        y_pred_test_orig, y_pred_train_orig = np.expm1(y_pred_test), np.expm1(y_pred_train)
    else: # 'none'
        y_test_orig, y_train_orig = y_test, y_train
        y_pred_test_orig, y_pred_train_orig = y_pred_test, y_pred_train


    # Store metrics calculated on the original scale
    results[name] = {
        'Time Taken (s)': elapsed_time,
        'Test R2 Score': r2_score(y_test_orig, y_pred_test_orig),
        'Test MAE': mean_absolute_error(y_test_orig, y_pred_test_orig),
        'Test RMSE': np.sqrt(mean_squared_error(y_test_orig, y_pred_test_orig)),
        'Test MSE': mean_squared_error(y_test_orig, y_pred_test_orig),
        'Train R2 Score': r2_score(y_train_orig, y_pred_train_orig),
        'Train MAE': mean_absolute_error(y_train_orig, y_pred_train_orig),
        'Train RMSE': np.sqrt(mean_squared_error(y_train_orig, y_pred_train_orig)),
        'Train MSE': mean_squared_error(y_train_orig, y_pred_train_orig),
    }
# --- Save and display results ---
results_df = pd.DataFrame.from_dict(results, orient='index')
results_df.to_csv(result_file)
display(descriptor_name)
display(results_df)

Training set size: 884 samples, 8192 features
Testing set size: 222 samples, 8192 features
Training model: Linear Regression
Training model: Ridge Regression

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning: Ill-conditioned matrix (rcond=6.5711e-09): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)

Training model: Lasso Regression
Training model: ElasticNet
Training model: Support Vector Regressor
Training model: Random Forest Regressor
Training model: Gradient Boosting Regressor
Training model: Extra Trees Regressor
Training model: XGBoost Regressor
Training model: LightGBM Regressor

/usr/local/lib/python3.12/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.377597 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2088960
[LightGBM] [Info] Number of data points in the train set: 884, number of used features: 8192
[LightGBM] [Info] Start training from score 86.887704

/usr/local/lib/python3.12/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training model: CatBoost Regressor

'CDI'

,Time Taken (s),Test R2 Score,Test MAE,Test RMSE,Test MSE,Train R2 Score,Train MAE,Train RMSE,Train MSE
Linear Regression,1.2371,-0.592401,14.766258,20.611255,424.823833,0.834375,5.456710e+00,7.100819e+00,5.042162e+01
Ridge Regression,0.3444,-0.624934,15.019173,20.820737,433.503104,0.916325,3.842405e+00,5.047130e+00,2.547352e+01
Lasso Regression,0.3036,0.173560,10.822790,14.848544,220.479269,0.313540,1.040573e+01,1.445616e+01,2.089807e+02
ElasticNet,1.0090,0.186879,10.592384,14.728406,216.925930,0.350068,1.013703e+01,1.406628e+01,1.978603e+02
Support Vector Regressor,16.1657,0.005016,9.512508,16.292442,265.443675,0.080756,9.622534e+00,1.672865e+01,2.798477e+02
Random Forest Regressor,1260.0504,0.301302,9.282026,13.652838,186.399983,0.907536,3.659853e+00,5.305579e+00,2.814917e+01
Gradient Boosting Regressor,418.8366,0.301074,8.998697,13.655063,186.460751,0.924175,3.680859e+00,4.804548e+00,2.308368e+01
Extra Trees Regressor,279.1469,0.318238,9.287458,13.486357,181.881837,1.000000,9.124124e-14,1.088790e-13,1.185464e-26
XGBoost Regressor,256.1845,0.206126,9.426617,14.553053,211.791360,1.000000,6.352079e-03,8.645462e-03,7.474402e-05
LightGBM Regressor,123.5090,0.294402,9.035139,13.720086,188.240757,0.994496,6.287625e-01,1.294417e+00,1.675514e+00
CatBoost Regressor,2278.9437,0.355605,8.741664,13.111555,171.912865,0.997053,7.540581e-01,9.472381e-01,8.972600e-01